install all required packages

In [20]:


!pip install transformers[torch] datasets evaluate seqeval scikit-learn accelerate -q

print("✓ Libraries installed successfully")
print("✓ 'evaluate' library is now installed")

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

✓ Libraries installed successfully
✓ 'evaluate' library is now installed

In [21]:
import json
import torch
import numpy as np
import pandas as pd
from collections import defaultdict
from typing import List, Dict, Tuple
import warnings
warnings.filterwarnings('ignore')
import pickle   # <- standard library, always available
from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
import evaluate

# Check if GPU is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
print(f"GPU Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")

Using device: cuda
GPU Available: True
GPU Name: GRID V100S-32Q

In [22]:
# Define your custom entity types
# These are the categories you want the model to recognize

BASE_LABELS = [
    'CHANGE',       # transformation words (increased, decreased)
    'LOC',          # location names
    'LULC',         # Land Use/Land Cover (THIS IS YOUR MAIN FOCUS)
    'DATE',         # temporal references
    'PERCENT',      # percentage values
    'CARDINAL',     # numeric values
    'COORDINATES',  # geographic coordinates
    'SURFACE_UNIT', # area measurements
    'PROCESS',      # environmental processes
    'QUANTITY'      # other quantities
]

# Create IOB2 format labels (B- for Beginning, I- for Inside, O for Outside)
labels_list = ["O"]  # 'O' means the token is not part of any entity
for label in BASE_LABELS:
    labels_list.append(f"B-{label}")  # Beginning of entity
    labels_list.append(f"I-{label}")  # Inside/continuation of entity

# Create mappings between labels and IDs
label2id = {label: i for i, label in enumerate(labels_list)}
id2label = {i: label for i, label in enumerate(labels_list)}

print(f"Total number of labels: {len(labels_list)}")
print(f"\nLabel to ID mapping (first 10):")
for label, id in list(label2id.items()):
    print(f"  {label}: {id}")

Total number of labels: 21

Label to ID mapping (first 10):
  O: 0
  B-CHANGE: 1
  I-CHANGE: 2
  B-LOC: 3
  I-LOC: 4
  B-LULC: 5
  I-LULC: 6
  B-DATE: 7
  I-DATE: 8
  B-PERCENT: 9
  I-PERCENT: 10
  B-CARDINAL: 11
  I-CARDINAL: 12
  B-COORDINATES: 13
  I-COORDINATES: 14
  B-SURFACE_UNIT: 15
  I-SURFACE_UNIT: 16
  B-PROCESS: 17
  I-PROCESS: 18
  B-QUANTITY: 19
  I-QUANTITY: 20

In [23]:
# You're missing some imports
from sklearn.model_selection import train_test_split  # Add this
import re  # For pattern matching

# Also, you reference 'tokenizer' before defining it
# Add this after your label definitions:
model_name = "roberta-base"  # or "roberta-large" for better performance
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [5]:
# Load your data file
# Change this path to your actual data file
DATA_FILE = 'merged_file2.json'  # CHANGE THIS TO YOUR FILE


with open(DATA_FILE, 'r', encoding='utf-8') as f:
    raw_data = json.load(f)

print(f"Loaded {len(raw_data)} sentences from {DATA_FILE}")

# Explore the data structure
print("\nData structure example:")
print(f"Article ID: {raw_data[0]['article_id']}")
print(f"Text: {raw_data[4]['original_sentence']}")
print(f"\nEntities:")
for entity in raw_data[5]['entities']:
    print(f"  - '{entity['text']}' -> {entity['label']} (chars {entity['start_char']}-{entity['end_char']})")

# Count entities by type
entity_counts = defaultdict(int)
all_lulc_terms = []
article_counts = defaultdict(int)

for item in raw_data:
    article_counts[item['article_id']] += 1
    for entity in item['entities']:
        entity_counts[entity['label']] += 1
        
        # Collect LULC terms
        if entity['label'] == 'LULC':
            all_lulc_terms.append(entity['text'].lower())

print(f"\n📊 Dataset Statistics:")
print(f"Total sentences: {len(raw_data)}")
print(f"Total articles: {len(article_counts)}")
print(f"Average sentences per article: {len(raw_data) / len(article_counts):.1f}")

print("\n📈 Entity distribution in your data:")
for entity_type, count in sorted(entity_counts.items(), key=lambda x: x[1], reverse=True):
    print(f"  {entity_type}: {count}")

print(f"\n🏗️ LULC Statistics:")
print(f"Total LULC entities: {len(all_lulc_terms)}")
print(f"Unique LULC terms: {len(set(all_lulc_terms))}")
print("\nTop 10 most common LULC terms:")
from collections import Counter
lulc_counter = Counter(all_lulc_terms)
for term, count in lulc_counter.most_common(10):
    print(f"  • {term}: {count} occurrences")

Loaded 14522 sentences from merged_file2.json

Data structure example:
Article ID: Article_1
Text: The study observed a significant increase (12.77%) in built-up area from 2002 (52.88%) to 2018 (65.5%), followed by a slight increase in the cover of bare ground.

Entities:
  - 'forest' -> LULC (chars 17-23)
  - 'declined' -> CHANGE (chars 30-38)
  - '15.25%' -> PERCENT (chars 52-58)
  - 'agriculture' -> LULC (chars 72-83)
  - '1.01%' -> PERCENT (chars 85-90)

📊 Dataset Statistics:
Total sentences: 14522
Total articles: 968
Average sentences per article: 15.0

📈 Entity distribution in your data:
  CHANGE: 10233
  LULC: 6424
  CARDINAL: 5419
  DATE: 4644
  LOC: 3868
  PERCENT: 1551
  COORDINATES: 1388
  PROCESS: 1241
  SURFACE_UNIT: 924
  QUANTITY: 130
  RESEARCH_TERM: 17

🏗️ LULC Statistics:
Total LULC entities: 6424
Unique LULC terms: 102

Top 10 most common LULC terms:
  • forest: 1267 occurrences
  • water: 798 occurrences
  • urban: 782 occurrences
  • forests: 389 occurrences
  • city: 318 occurrences
  • agriculture: 316 occurrences
  • cropland: 266 occurrences
  • grassland: 164 occurrences
  • cities: 152 occurrences
  • tree: 147 occurrences

In [7]:
def align_labels_with_tokens_enhanced(sentence_data, tokenizer):
    """
    Enhanced version that adds pattern-based LULC detection
    """
    text = sentence_data['original_sentence']
    entities = sentence_data['entities'][:]  # Copy existing entities
    
    # Find additional LULC patterns
    pattern_matches = find_lulc_patterns(text)
    
    # Remove overlaps: if a pattern overlaps with existing entity, 
    # prioritize LULC if the existing entity is not LULC
    for pattern_match in pattern_matches:
        overlaps = False
        for existing_entity in entities:
            # Check for overlap
            if (pattern_match['end'] > existing_entity['start_char'] and 
                pattern_match['start'] < existing_entity['end_char']):
                overlaps = True
                # If existing entity is not LULC, replace it
                if existing_entity['label'] != 'LULC':
                    print(f"Replacing {existing_entity['label']} '{existing_entity['text']}' with LULC '{pattern_match['text']}'")
                    existing_entity['start_char'] = pattern_match['start']
                    existing_entity['end_char'] = pattern_match['end']
                    existing_entity['text'] = pattern_match['text']
                    existing_entity['label'] = 'LULC'
                break
        
        # If no overlap, add as new entity
        if not overlaps:
            entities.append({
                'start_char': pattern_match['start'],
                'end_char': pattern_match['end'],
                'text': pattern_match['text'],
                'label': 'LULC'
            })
    
    # Sort entities by start position
    entities.sort(key=lambda x: x['start_char'])
    
    # Now proceed with original tokenization logic
    encoding = tokenizer(
        text,
        truncation=False,
        max_length=1024,
        return_offsets_mapping=True,
        padding=False
    )
    
    tokens = tokenizer.convert_ids_to_tokens(encoding['input_ids'])
    offset_mapping = encoding['offset_mapping']
    
    # Initialize all labels as 'O'
    labels = ['O'] * len(tokens)
    
    # Process each entity (including newly added ones)
    for entity in entities:
        entity_start = entity['start_char']
        entity_end = entity['end_char']
        entity_label = entity['label']
        
        # Find tokens that overlap with this entity
        entity_tokens = []
        for idx, (token_start, token_end) in enumerate(offset_mapping):
            if token_start == 0 and token_end == 0:
                continue
                
            if token_end > entity_start and token_start < entity_end:
                entity_tokens.append(idx)
        
        # Assign labels
        if entity_tokens:
            labels[entity_tokens[0]] = f"B-{entity_label}"
            for idx in entity_tokens[1:]:
                labels[idx] = f"I-{entity_label}"
    
    return tokens, labels, offset_mapping

In [8]:
# Add this cell BEFORE your data processing
import re

def fix_missing_entities(data):
    """
    Automatically find and add missing LULC, LOC, and COORDINATES entities
    """
    print("🔧 Fixing missing entities...")
    
    fixed_data = []
    added_entities = 0
    
    for item in data:
        # Copy the original item
        fixed_item = {
            'original_sentence': item['original_sentence'],
            'entities': item['entities'][:],  # Copy existing entities
            'article_id': item.get('article_id', 'unknown')
        }
        
        text = item['original_sentence']
        
        # Get existing entity positions to avoid duplicates
        existing_spans = set()
        for entity in item['entities']:
            existing_spans.add((entity['start_char'], entity['end_char']))
        
        # PATTERN 1: Find "WORD area/land/zone" patterns for LULC
        lulc_patterns = [
            r'\b(forest\s+area)\b',           # "forest area" 
            r'\b(agricultural\s+land)\b',     # "agricultural land"
            r'\b(urban\s+areas?)\b',          # "urban area" or "urban areas"
            r'\b(crop\s*land)\b',             # "cropland" or "crop land"
            r'\b(grass\s*land)\b',            # "grassland" or "grass land"  
            r'\b(wet\s*lands?)\b',            # "wetland" or "wetlands"
            r'\b(residential\s+areas?)\b',    # "residential area"
            r'\b(commercial\s+areas?)\b',     # "commercial area"
            r'\b(industrial\s+areas?)\b',     # "industrial area"
            r'\b(urban\s+sprawl)\b',
            r'\b(built-?up\s+areas?)\b',
            r'\b(built\s+up\s+areas?)\b',
            r'\b(green\s+spaces?)\b'
        ]
        
        # PATTERN 2: Find "DIRECTION region/area/zone" patterns for LOC
        location_patterns = [
            r'\b(northern\s+region)\b',       # "northern region"
            r'\b(southern\s+region)\b',       # "southern region"  
            r'\b(eastern\s+region)\b',        # "eastern region"
            r'\b(western\s+region)\b',        # "western region"
            r'\b(central\s+region)\b',        # "central region"
            r'\b(coastal\s+areas?)\b',        # "coastal area"
            r'\b(rural\s+areas?)\b',          # "rural area"
            r'\b(mountain\s+regions?)\b',     # "mountain region"
        ]
        
        # PATTERN 3: Find coordinate patterns
        coordinate_patterns = [
            r'\b(\d+\.?\d*°[NSEW],?\s*\d+\.?\d*°[NSEW])\b',  # "23.5°N, 87.3°E"
            r'\b(\d+\.?\d*°[NSEW])\b',                        # "23.5°N"
        ]
        
        # Check each pattern type
        all_patterns = [
            (lulc_patterns, 'LULC'),
            (location_patterns, 'LOC'), 
            (coordinate_patterns, 'COORDINATES')
        ]
        
        for patterns, label_type in all_patterns:
            for pattern in patterns:
                # Find all matches in the text
                for match in re.finditer(pattern, text, re.IGNORECASE):
                    start_pos = match.start(1)  # Start of captured group
                    end_pos = match.end(1)     # End of captured group
                    matched_text = match.group(1)
                    
                    # Check if this position already has an entity
                    overlap = False
                    for existing_start, existing_end in existing_spans:
                        # Check if there's any overlap
                        if not (end_pos <= existing_start or start_pos >= existing_end):
                            overlap = True
                            break
                    
                    # If no overlap, add this as a new entity
                    if not overlap:
                        fixed_item['entities'].append({
                            'start_char': start_pos,
                            'end_char': end_pos,
                            'text': matched_text,
                            'label': label_type
                        })
                        existing_spans.add((start_pos, end_pos))
                        added_entities += 1
        
        fixed_data.append(fixed_item)
    
    print(f"✅ Added {added_entities} missing entities!")
    return fixed_data

# Test the function on a few examples first
test_sentences = [
    {
        'original_sentence': "The forest area decreased by 25% between 2010 and 2020 in the northern region.",
        'entities': [
            {'start_char': 4, 'end_char': 10, 'text': 'forest', 'label': 'LULC'},
            {'start_char': 16, 'end_char': 25, 'text': 'decreased', 'label': 'CHANGE'}
        ],
        'article_id': 'test1'
    },
    {
        'original_sentence': "Urban areas have replaced agricultural land at coordinates 23.5°N, 87.3°E.",
        'entities': [
            {'start_char': 0, 'end_char': 5, 'text': 'Urban', 'label': 'LULC'}
        ],
        'article_id': 'test2'
    },
    {
        'original_sentence': "The development of industrial parks replaced former wetlands and grasslands.",
        'entities': [
            {'start_char': 48, 'end_char': 56, 'text': 'wetlands', 'label': 'LULC'},
            {'start_char': 61, 'end_char': 71, 'text': 'grasslands', 'label': 'LULC'}
        ],
        'article_id': 'test2'
    }
]

print("🧪 Testing the fix function...")
fixed_test = fix_missing_entities(test_sentences)

print("\nBefore and after comparison:")
for i, (original, fixed) in enumerate(zip(test_sentences, fixed_test)):
    print(f"\nExample {i+1}: {original['original_sentence']}")
    print(f"  Original entities: {len(original['entities'])}")
    for entity in original['entities']:
        print(f"    - '{entity['text']}' → {entity['label']}")
    
    print(f"  Fixed entities: {len(fixed['entities'])}")
    for entity in fixed['entities']:
        print(f"    - '{entity['text']}' → {entity['label']}")

🧪 Testing the fix function...
🔧 Fixing missing entities...
✅ Added 3 missing entities!

Before and after comparison:

Example 1: The forest area decreased by 25% between 2010 and 2020 in the northern region.
  Original entities: 2
    - 'forest' → LULC
    - 'decreased' → CHANGE
  Fixed entities: 3
    - 'forest' → LULC
    - 'decreased' → CHANGE
    - 'northern region' → LOC

Example 2: Urban areas have replaced agricultural land at coordinates 23.5°N, 87.3°E.
  Original entities: 1
    - 'Urban' → LULC
  Fixed entities: 3
    - 'Urban' → LULC
    - 'agricultural land' → LULC
    - '23.5°N, 87.3°E' → COORDINATES

Example 3: The development of industrial parks replaced former wetlands and grasslands.
  Original entities: 2
    - 'wetlands' → LULC
    - 'grasslands' → LULC
  Fixed entities: 2
    - 'wetlands' → LULC
    - 'grasslands' → LULC

In [9]:
# Apply the fix to your actual data
print("🔧 Applying fixes to your training data...")

# IMPORTANT: Use the fixed data instead of raw_data
fixed_raw_data = fix_missing_entities(raw_data)

# Compare before and after
original_count = sum(len(item['entities']) for item in raw_data)
fixed_count = sum(len(item['entities']) for item in fixed_raw_data)

print(f"\n📊 Results:")
print(f"Original entities: {original_count}")
print(f"Fixed entities: {fixed_count}")
print(f"Added entities: {fixed_count - original_count}")

# Show some examples of what was added
print(f"\n🔍 Examples of added entities:")
examples_shown = 0
for original, fixed in zip(raw_data, fixed_raw_data):
    if len(fixed['entities']) > len(original['entities']) and examples_shown < 3:
        print(f"\nSentence: {original['original_sentence']}")
        original_entities = {(e['start_char'], e['end_char'], e['text']) for e in original['entities']}
        for entity in fixed['entities']:
            if (entity['start_char'], entity['end_char'], entity['text']) not in original_entities:
                print(f"  ➕ Added: '{entity['text']}' → {entity['label']}")
        examples_shown += 1

🔧 Applying fixes to your training data...
🔧 Fixing missing entities...
✅ Added 638 missing entities!

📊 Results:
Original entities: 35839
Fixed entities: 36477
Added entities: 638

🔍 Examples of added entities:

Sentence: The study observed a significant increase (12.77%) in built-up area from 2002 (52.88%) to 2018 (65.5%), followed by a slight increase in the cover of bare ground.
  ➕ Added: 'built-up area' → LULC

Sentence: Using the outputs from remote sensing imagery, field surveys, and topped expert knowledge of the study area, five LULC types were classified; water body, bare ground, built-up area, forest, and agriculture ( Fig.
  ➕ Added: 'built-up area' → LULC

Sentence: The resultant improvement in basic facilities combined with creation of additional jobs further attracted more immigration from rural areas and lesser developed cities, causing a boom in real estate and informal settlements and triggering significant changes in land uses.
  ➕ Added: 'rural areas' → LOC

In [11]:
def fix_buildup_labeling_consistency(fixed_raw_data):
    """
    Fix the inconsistent labeling of 'built-up area' patterns
    """
    print("🔧 FIXING BUILT-UP AREA LABELING CONSISTENCY...")
    
    import re
    fixed_count = 0
    sentences_fixed = 0
    
    # Patterns to fix
    buildup_patterns = [
        r'\b(built-up\s+areas?)\b',
        r'\b(built\s+up\s+areas?)\b',
        r'\b(build-up\s+areas?)\b'
    ]
    
    for item in raw_data:
        text = item['original_sentence']
        entities = item['entities']
        
        sentence_had_buildup = False
        
        # Check if sentence contains built-up area patterns
        for pattern in buildup_patterns:
            for match in re.finditer(pattern, text, re.IGNORECASE):
                sentence_had_buildup = True
                start_pos = match.start(1)
                end_pos = match.end(1)
                matched_text = match.group(1)
                
                # Check if this span is already labeled as LULC
                already_labeled_lulc = any(
                    entity['start_char'] <= start_pos < end_pos <= entity['end_char'] and 
                    entity['label'] == 'LULC'
                    for entity in entities
                )
                
                if not already_labeled_lulc:
                    # Check if it overlaps with any existing entity
                    overlaps = any(
                        not (end_pos <= entity['start_char'] or start_pos >= entity['end_char'])
                        for entity in entities
                    )
                    
                    if not overlaps:
                        # Add as LULC entity
                        item['entities'].append({
                            'start_char': start_pos,
                            'end_char': end_pos,
                            'text': matched_text,
                            'label': 'LULC'
                        })
                        fixed_count += 1
                        print(f"  ➕ Fixed: '{matched_text}' in sentence: {text[:50]}...")
                    else:
                        # Remove conflicting entities and add LULC
                        original_count = len(entities)
                        item['entities'] = [
                            entity for entity in entities
                            if (end_pos <= entity['start_char'] or start_pos >= entity['end_char'])
                        ]
                        removed_count = original_count - len(item['entities'])
                        
                        item['entities'].append({
                            'start_char': start_pos,
                            'end_char': end_pos,
                            'text': matched_text,
                            'label': 'LULC'
                        })
                        fixed_count += 1
                        print(f"  🔄 Replaced {removed_count} entities with LULC: '{matched_text}'")
        
        if sentence_had_buildup:
            sentences_fixed += 1
    
    print(f"\n✅ CONSISTENCY FIX COMPLETE:")
    print(f"   Fixed entities: {fixed_count}")
    print(f"   Sentences affected: {sentences_fixed}")
    
    return raw_data

# Apply the fix
print("Applying built-up area labeling consistency fix...")
fixed_raw_data = fix_buildup_labeling_consistency(raw_data.copy())

Applying built-up area labeling consistency fix...
🔧 FIXING BUILT-UP AREA LABELING CONSISTENCY...

✅ CONSISTENCY FIX COMPLETE:
   Fixed entities: 0
   Sentences affected: 256

In [12]:
def fix_enhanced_location_patterns(fixed_raw_data):
    """
    Enhanced location pattern detection for complex directional terms
    """
    print("🔧 FIXING ENHANCED LOCATION PATTERNS...")
    
    import re
    fixed_count = 0
    
    # Enhanced location patterns - more comprehensive
    enhanced_location_patterns = [
        # Basic directional regions
        r'\b(northern\s+region)\b',
        r'\b(southern\s+region)\b',
        r'\b(eastern\s+region)\b', 
        r'\b(western\s+region)\b',
        r'\b(central\s+region)\b',
        
        # Compound directional regions (the missing ones!)
        r'\b(northeastern\s+region)\b',
        r'\b(northwestern\s+region)\b', 
        r'\b(southeastern\s+region)\b',
        r'\b(southwestern\s+region)\b',
        r'\b(north-eastern\s+region)\b',
        r'\b(north-western\s+region)\b',
        r'\b(south-eastern\s+region)\b', 
        r'\b(south-western\s+region)\b',
        
        # Regional qualifiers with country/place names
        r'\b(northeastern\s+region\s+of\s+\w+)\b',
        r'\b(northwestern\s+region\s+of\s+\w+)\b',
        r'\b(southeastern\s+region\s+of\s+\w+)\b',
        r'\b(southwestern\s+region\s+of\s+\w+)\b',
        r'\b(northern\s+region\s+of\s+\w+)\b',
        r'\b(southern\s+region\s+of\s+\w+)\b',
        r'\b(eastern\s+region\s+of\s+\w+)\b',
        r'\b(western\s+region\s+of\s+\w+)\b',
        r'\b(central\s+region\s+of\s+\w+)\b',
        
        # Other location types
        r'\b(coastal\s+areas?)\b',
    ]
    
    for item in raw_data:
        text = item['original_sentence']
        entities = item['entities']
        existing_spans = {(e['start_char'], e['end_char']) for e in entities}
        
        for pattern in enhanced_location_patterns:
            for match in re.finditer(pattern, text, re.IGNORECASE):
                start_pos = match.start(1)
                end_pos = match.end(1) 
                matched_text = match.group(1)
                
                # Check if already labeled as LOC
                already_labeled_loc = any(
                    entity['start_char'] <= start_pos < end_pos <= entity['end_char'] and 
                    entity['label'] == 'LOC'
                    for entity in entities
                )
                
                if not already_labeled_loc:
                    # Check for overlaps
                    overlaps = any(
                        not (end_pos <= e_start or start_pos >= e_end)
                        for e_start, e_end in existing_spans
                    )
                    
                    if not overlaps:
                        # Add as LOC entity
                        item['entities'].append({
                            'start_char': start_pos,
                            'end_char': end_pos,
                            'text': matched_text,
                            'label': 'LOC'
                        })
                        existing_spans.add((start_pos, end_pos))
                        fixed_count += 1
                        print(f"  ➕ Fixed: '{matched_text}' as LOC")
    
    print(f"\n✅ Enhanced location patterns fixed: {fixed_count} entities")
    return fixed_raw_data

# Apply enhanced location fix
enhanced_fixed_data = fix_enhanced_location_patterns(fixed_raw_data.copy())

🔧 FIXING ENHANCED LOCATION PATTERNS...
  ➕ Fixed: 'southeastern region' as LOC
  ➕ Fixed: 'coastal area' as LOC
  ➕ Fixed: 'southeastern region' as LOC
  ➕ Fixed: 'northern region' as LOC
  ➕ Fixed: 'northern region' as LOC
  ➕ Fixed: 'eastern region' as LOC
  ➕ Fixed: 'western region' as LOC
  ➕ Fixed: 'northern region' as LOC
  ➕ Fixed: 'Northeastern region' as LOC
  ➕ Fixed: 'northwestern region' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal area' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'northern region' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal area' as LOC
  ➕ Fixed: 'northern region' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal area' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'Northeastern region' as LOC
  ➕ Fixed: 'northwestern region' as LOC
  ➕ Fixed: 'coastal areas' as LOC
  ➕ Fixed: 'Western region' as LOC
  ➕ Fixed: 'southeastern region' as LOC
  ➕ Fixed: 'eastern region' as LOC
  ➕ Fixed: 'western region' as LOC
  ➕ Fixed: 'western region' as LOC
  ➕ Fixed: 'northern region' as LOC
  ➕ Fixed: 'southern region' as LOC
  ➕ Fixed: 'northeastern region' as LOC
  ➕ Fixed: 'southwestern region' as LOC
  ➕ Fixed: 'southwestern region' as LOC
  ➕ Fixed: 'northern region' as LOC
  ➕ Fixed: 'southern region' as LOC

✅ Enhanced location patterns fixed: 41 entities

In [13]:
def fix_surface_unit_labeling(fixed_raw_data):
    """
    Fix missing SURFACE_UNIT labels for area measurements
    Following the same pattern as other fix functions
    """
    print("🔧 FIXING SURFACE_UNIT LABELING...")
    
    import re
    fixed_count = 0
    sentences_fixed = 0
    
    # Surface unit patterns
    surface_unit_patterns = [
        r'\b(hectares?)\b',                    # hectares, hectare
        r'\b(km²|km2)\b',                      # km², km2  
        r'\b(square\s+kilometers?)\b',         # square kilometer(s)
        r'\b(sq\.?\s*km)\b',                   # sq km, sq. km
        r'\b(m²|m2)\b',                        # m², m2
        r'\b(square\s+meters?)\b',             # square meter(s)
        r'\b(acres?)\b',                       # acres, acre
        r'\b(ha)\b',                           # ha (hectare abbreviation)
        r'\b(square\s+miles?)\b',              # square mile(s)
    
        # Number + hectares/ha patterns
        r'\b(\d+(?:,\d{3})*(?:\.\d+)?\s*(?:hectares?|ha))\b',           # 20,385ha, 1,500 hectares
        r'\b(\d+(?:\.\d+)?\s*(?:million|billion)\s+hectares?)\b',       # 1.5 million hectares
        
        # Number + km² patterns  
        r'\b(\d+(?:,\d{3})*(?:\.\d+)?\s*(?:km²|km2))\b',               # 500km², 1,200 km²
        r'\b(\d+(?:\.\d+)?\s*(?:million|billion)\s+km²)\b',            # 2.3 million km²
        
        # Number + square kilometers
        r'\b(\d+(?:,\d{3})*(?:\.\d+)?\s+square\s+kilometers?)\b',      # 500 square kilometers
        r'\b(\d+(?:\.\d+)?\s*(?:million|billion)\s+square\s+kilometers?)\b', # 1.5 million square kilometers
        
        # Number + acres
        r'\b(\d+(?:,\d{3})*(?:\.\d+)?\s*acres?)\b',                    # 1,500acres, 200 acres
        r'\b(\d+(?:\.\d+)?\s*(?:million|billion)\s+acres?)\b',         # 2.5 million acres
        
        # Number + square meters
        r'\b(\d+(?:,\d{3})*(?:\.\d+)?\s*(?:m²|m2))\b',                 # 5,000m²
        r'\b(\d+(?:,\d{3})*(?:\.\d+)?\s+square\s+meters?)\b',          # 1,000 square meters
        
        # Number + square miles
        r'\b(\d+(?:,\d{3})*(?:\.\d+)?\s*(?:square\s+miles?|sq\.?\s*mi))\b', # 100 square miles
        
        # Just units (when number is separate)
        r'\b(hectares?)\b',                    # hectares, hectare (standalone)
        r'\b(km²|km2)\b',                      # km², km2 (standalone)
        r'\b(acres?)\b',                       # acres, acre (standalone)
        r'\b(ha)\b',                           # ha (standalone)
    ]
    
    for item in fixed_raw_data:
        text = item['original_sentence']
        entities = item['entities']
        
        sentence_had_surface_unit = False
        
        # Check if sentence contains surface unit patterns
        for pattern in surface_unit_patterns:
            for match in re.finditer(pattern, text, re.IGNORECASE):
                sentence_had_surface_unit = True
                start_pos = match.start(1)
                end_pos = match.end(1)
                matched_text = match.group(1)
                
                # Check if this span is already labeled as SURFACE_UNIT
                already_labeled_surface_unit = any(
                    entity['start_char'] <= start_pos < end_pos <= entity['end_char'] and 
                    entity['label'] == 'SURFACE_UNIT'
                    for entity in entities
                )
                
                if not already_labeled_surface_unit:
                    # Check if it overlaps with any existing entity
                    overlaps = any(
                        not (end_pos <= entity['start_char'] or start_pos >= entity['end_char'])
                        for entity in entities
                    )
                    
                    if not overlaps:
                        # Add as SURFACE_UNIT entity
                        entities.append({
                            'start_char': start_pos,
                            'end_char': end_pos,
                            'text': matched_text,
                            'label': 'SURFACE_UNIT'
                        })
                        fixed_count += 1
                        print(f"  ➕ Fixed: '{matched_text}' in sentence: {text[:50]}...")
                    else:
                        # Remove conflicting entities and add SURFACE_UNIT
                        original_count = len(entities)
                        entities[:] = [
                            entity for entity in entities
                            if (end_pos <= entity['start_char'] or start_pos >= entity['end_char'])
                        ]
                        
                        entities.append({
                            'start_char': start_pos,
                            'end_char': end_pos,
                            'text': matched_text,
                            'label': 'SURFACE_UNIT'
                        })
                        fixed_count += 1
                        print(f"  🔄 Replaced entities with SURFACE_UNIT: '{matched_text}'")
        
        if sentence_had_surface_unit:
            sentences_fixed += 1
    
    print(f"\n✅ SURFACE_UNIT FIX COMPLETE:")
    print(f"   Fixed entities: {fixed_count}")
    print(f"   Sentences affected: {sentences_fixed}")
    
    return fixed_raw_data

# Apply the fix to your data (following the same pattern as your other fixes)
print("Applying SURFACE_UNIT fixes to your training data...")

# Apply the fix - this modifies your data directly like the other functions
fixed_raw_data = fix_surface_unit_labeling(fixed_raw_data.copy())

Applying SURFACE_UNIT fixes to your training data...
🔧 FIXING SURFACE_UNIT LABELING...
  ➕ Fixed: 'hectares' in sentence: It is also defined as urban expansion, as the proc...
  ➕ Fixed: 'hectares' in sentence: It is also defined as urban expansion, as the proc...
  ➕ Fixed: 'hectares' in sentence: It is also defined as urban expansion, as the proc...
  🔄 Replaced entities with SURFACE_UNIT: '13 billion hectares'
  🔄 Replaced entities with SURFACE_UNIT: '4.9 billion hectares'
  🔄 Replaced entities with SURFACE_UNIT: '420 million hectares'
  ➕ Fixed: 'hectares' in sentence: As for urban land, this area could expand from 40 ...
  🔄 Replaced entities with SURFACE_UNIT: '143 million hectares'
  ➕ Fixed: 'hectares' in sentence: In 2011-2015, following the data from MoNRE, Vietn...
  ➕ Fixed: 'hectares' in sentence: Economically, urbanization and industrialization h...
  🔄 Replaced entities with SURFACE_UNIT: '11 million hectares'
  ➕ Fixed: 'hectare' in sentence: From an organism's perspective land-use classifica...
  ➕ Fixed: 'ha' in sentence: The MUSLE  is where sed is the sediment yield on a...
  ➕ Fixed: 'ha' in sentence: The MUSLE  is where sed is the sediment yield on a...
  🔄 Replaced entities with SURFACE_UNIT: 'sq.km'
  ➕ Fixed: 'ha' in sentence: These are the total LULC in ha, the percentage LUL...
  🔄 Replaced entities with SURFACE_UNIT: '50.45ha'
  🔄 Replaced entities with SURFACE_UNIT: 'ha'
  ➕ Fixed: 'ha' in sentence: The dominant contributors to the decline of forest...
  🔄 Replaced entities with SURFACE_UNIT: '1983.87 ha'
  🔄 Replaced entities with SURFACE_UNIT: '5445.92 ha'
  ➕ Fixed: 'ha' in sentence: Likewise, the forest ecosystem, which covered1833....
  🔄 Replaced entities with SURFACE_UNIT: '15 ha'
  ➕ Fixed: 'km²' in sentence: A table showing the area in square kilometers was ...
  ➕ Fixed: 'square kilometers' in sentence: A table showing the area in square kilometers was ...
  ➕ Fixed: 'hectares' in sentence: This can be attributed to the recent reforestation...
  🔄 Replaced entities with SURFACE_UNIT: '12 million hectares'
  ➕ Fixed: 'square meters' in sentence: These are codes In addition to the map, the accura...
  ➕ Fixed: 'square meters' in sentence: The second table gives an overview of the possible...
  ➕ Fixed: 'square meters' in sentence: They also include a couple of error/Cross-Tabulati...
  ➕ Fixed: 'square meters' in sentence: Error matrixes show the area in square meters cove...
  ➕ Fixed: 'hectares' in sentence: The script generates a table containing the absolu...
  ➕ Fixed: 'ha' in sentence: During the period 2000-2018, the built-up area is ...
  🔄 Replaced entities with SURFACE_UNIT: '1840 ha'
  ➕ Fixed: 'ha' in sentence: We use the Vector table Field Calculator tool to c...
  ➕ Fixed: 'hectares' in sentence: -Remark -Area_Ha: Area of the polygon, in hectares...
  ➕ Fixed: 'hectares' in sentence: 2, chapter 4.1): We recalculate the CO 2 flux and ...
  ➕ Fixed: 'hectares' in sentence: 2, chapter 4.1): We recalculate the CO 2 flux and ...
  🔄 Replaced entities with SURFACE_UNIT: '43 million hectares'
  🔄 Replaced entities with SURFACE_UNIT: '2.9 million hectares'
  ➕ Fixed: 'ha' in sentence: Change analysis was performed by using the classif...
  ➕ Fixed: 'ha' in sentence: Change analysis was performed by using the classif...
  ➕ Fixed: 'ha' in sentence: Change analysis was performed by using the classif...
  ➕ Fixed: 'ha' in sentence: The predicted map showed a significant decrease tr...
  ➕ Fixed: 'ha' in sentence: The simulation illustrates that the 2025 projected...
  ➕ Fixed: 'ha' in sentence: where A k is the area of LULC type K, and VC K is ...
  ➕ Fixed: 'ha' in sentence: We also estimated the value provided by individual...
  ➕ Fixed: 'ha' in sentence: | Spatial-Temporal Features of Land Use Change and...
  ➕ Fixed: 'hectare' in sentence: 2.2) and per hectare effects of land-use change an...
  ➕ Fixed: 'ha' in sentence: 2.2) and per hectare effects of land-use change an...
  ➕ Fixed: 'hectare' in sentence: The overall purpose of the bookkeeping model is to...
  ➕ Fixed: 'hectares' in sentence: Each year a new age class of hectares is created i...
  ➕ Fixed: 'ha' in sentence: That is, rates of forest growth and rates of decay...
  ➕ Fixed: 'ha' in sentence: 2.2 Changes in land use (rates of conversion, ha y...
  ➕ Fixed: 'hectare' in sentence: For example, the rate of emissions from a hectare ...
  ➕ Fixed: 'hectare' in sentence: | Changes in carbon per hectare as a result of LUL...
  ➕ Fixed: 'hectare' in sentence: Slash was assigned exponential decay rates in the ...
  ➕ Fixed: 'ha' in sentence: The second adjustment reduced harvest intensity (M...
  ➕ Fixed: 'ha' in sentence: Trends in the area of shifting cultivation are unc...
  ➕ Fixed: 'ha' in sentence: Trends in the area of shifting cultivation are unc...
  🔄 Replaced entities with SURFACE_UNIT: '6 ha'
  🔄 Replaced entities with SURFACE_UNIT: '6 ha'
  ➕ Fixed: 'hectare' in sentence: : When a hectare is deforested, net and gross emis...
  ➕ Fixed: 'ha' in sentence: Among the agricultural activities, the class of pa...
  🔄 Replaced entities with SURFACE_UNIT: '60,156 ha'
  ➕ Fixed: 'ha' in sentence: Changes in land conditions from land cover change ...
  ➕ Fixed: 'hectares' in sentence: Globally, the area of the more open, other wooded ...
  🔄 Replaced entities with SURFACE_UNIT: '1 billion hectares'
  ➕ Fixed: 'ha' in sentence: Considering forest uses, about 30% (1.2 billion ha...
  ➕ Fixed: 'ha' in sentence: The roughly 1 billion ha of secondary and degraded...
  ➕ Fixed: 'ha' in sentence: The carbon stocks of tropical peatlands are among ...
  ➕ Fixed: 'ha' in sentence: There is medium confidence in the large carbon sto...
  ➕ Fixed: 'ha' in sentence: There is medium confidence in the large carbon sto...
  ➕ Fixed: 'hectare' in sentence: Global technical mitigation potential for conserva...
  ➕ Fixed: 'ha' in sentence: Mean ecosystem carbon stock in mangroves is 3131 t...
  ➕ Fixed: 'hectare' in sentence: In case of increasing soil carbon in croplands thr...
  ➕ Fixed: 'ha' in sentence: The magnitude of LULC change experienced between t...
  ➕ Fixed: 'ha' in sentence: The magnitude of LULC change experienced between t...
  ➕ Fixed: 'ha' in sentence: The magnitude of LULC change experienced between t...
  ➕ Fixed: 'ha' in sentence: The area of urban and built-up land in 2017 was mo...
  🔄 Replaced entities with SURFACE_UNIT: '203 ha'
  ➕ Fixed: 'ha' in sentence: The value of overall accuracy greater than 70% is ...
  ➕ Fixed: 'ha' in sentence: year where A i is the class area (ha) at the initi...
  ➕ Fixed: 'ha' in sentence: year where A i is the class area (ha) at the initi...
  ➕ Fixed: 'ha' in sentence: On the other hand, forests in Libya, like others i...
  ➕ Fixed: 'ha' in sentence: On the other hand, forests in Libya, like others i...
  🔄 Replaced entities with SURFACE_UNIT: '82 ha'
  🔄 Replaced entities with SURFACE_UNIT: '55 ha'
  ➕ Fixed: 'ha' in sentence: NMF areas, which amounted to 20,385ha (56.61%) in ...
  🔄 Replaced entities with SURFACE_UNIT: '270 ha'
  ➕ Fixed: 'ha' in sentence: NMF areas, which amounted to 20,385ha (56.61%) in ...
  ➕ Fixed: 'ha' in sentence: NMF areas, which amounted to 20,385ha (56.61%) in ...
  🔄 Replaced entities with SURFACE_UNIT: '270 ha'
  🔄 Replaced entities with SURFACE_UNIT: '121 ha'
  ➕ Fixed: 'ha' in sentence: The annual rate of increase during this period whi...
  🔄 Replaced entities with SURFACE_UNIT: '203 ha'
  ➕ Fixed: 'ha' in sentence: Geographically, it is located between 7 °5′ to 7 °...
  ➕ Fixed: 'km²' in sentence: We identify a global net loss of forest area of 0....
  🔄 Replaced entities with SURFACE_UNIT: '0.8 million km²'
  ➕ Fixed: 'km²' in sentence: cropland and pasture/ rangeland) of 1.0 and 0.9 mi...
  🔄 Replaced entities with SURFACE_UNIT: '0.9 million km²'
  ➕ Fixed: 'ha' in sentence: The built-up area expanded greatly (874 ha) while ...
  🔄 Replaced entities with SURFACE_UNIT: '874 ha'
  ➕ Fixed: 'square kilometers' in sentence: Area units were measured in square kilometers, and...
  ➕ Fixed: 'ha' in sentence: The total change for the period from 1987 to 2015 ...
  🔄 Replaced entities with SURFACE_UNIT: '3 ha'
  ➕ Fixed: 'ha' in sentence: The change percent recorded 24.5% and 12.4% for th...
  ➕ Fixed: 'ha' in sentence: Change area (ha.)...
  ➕ Fixed: 'ha' in sentence: However, change percent of urban sprawl followed a...
  ➕ Fixed: 'ha' in sentence: Change area (ha.)...
  ➕ Fixed: 'ha' in sentence: The area of urban and built-up land in 2017 was mo...
  🔄 Replaced entities with SURFACE_UNIT: '203 ha'
  ➕ Fixed: 'ha' in sentence: The value of overall accuracy greater than 70% is ...
  ➕ Fixed: 'ha' in sentence: year where A i is the class area (ha) at the initi...
  ➕ Fixed: 'ha' in sentence: year where A i is the class area (ha) at the initi...
  ➕ Fixed: 'ha' in sentence: On the other hand, forests in Libya, like others i...
  ➕ Fixed: 'ha' in sentence: On the other hand, forests in Libya, like others i...
  🔄 Replaced entities with SURFACE_UNIT: '82 ha'
  🔄 Replaced entities with SURFACE_UNIT: '55 ha'
  ➕ Fixed: 'ha' in sentence: NMF areas, which amounted to 20,385ha (56.61%) in ...
  🔄 Replaced entities with SURFACE_UNIT: '270 ha'
  ➕ Fixed: 'ha' in sentence: NMF areas, which amounted to 20,385ha (56.61%) in ...
  ➕ Fixed: 'ha' in sentence: NMF areas, which amounted to 20,385ha (56.61%) in ...
  🔄 Replaced entities with SURFACE_UNIT: '270 ha'
  🔄 Replaced entities with SURFACE_UNIT: '121 ha'
  ➕ Fixed: 'ha' in sentence: The annual rate of increase during this period whi...
  🔄 Replaced entities with SURFACE_UNIT: '203 ha'
  ➕ Fixed: 'ha' in sentence: The Cramer's V Coefficient (CVC), sometimes called...
  ➕ Fixed: 'ha' in sentence: where POC represents the percentage of change; ROC...
  ➕ Fixed: 'ha' in sentence: where POC represents the percentage of change; ROC...
  🔄 Replaced entities with SURFACE_UNIT: '3acres'
  ➕ Fixed: '10acres' in sentence: The average land sizes that are owned by the inhab...
  ➕ Fixed: 'hectares' in sentence: The Change Matrix indicates a change in area cover...
  ➕ Fixed: 'ha' in sentence: Change analysis was performed by using the classif...
  ➕ Fixed: 'ha' in sentence: Change analysis was performed by using the classif...
  ➕ Fixed: 'ha' in sentence: Change analysis was performed by using the classif...
  ➕ Fixed: 'ha' in sentence: Another example, using a 7 year wheat- rotation in...
  ➕ Fixed: 'ha' in sentence: In the period 1975-1990, 1.28 million ha 26% of na...
  ➕ Fixed: 'ha' in sentence: In the period 1975-1990, 1.28 million ha 26% of na...
  ➕ Fixed: 'ha' in sentence: Such a form of agroforestry is highly beneficial t...
  ➕ Fixed: 'hectare' in sentence: Using both seedlings provided by APAF and their us...

✅ SURFACE_UNIT FIX COMPLETE:
   Fixed entities: 141
   Sentences affected: 194

In [13]:
def prepare_dataset(data, tokenizer, label2id, max_length=512):
    def process_example(example):
        sentence = example['original_sentence']
        entities = example['entities']
        
        # Tokenize the sentence
        encoding = tokenizer(
            sentence, 
            truncation=True, 
            max_length=max_length, 
            return_offsets_mapping=True, 
            padding='max_length'
        )
        
        offset_mapping = encoding['offset_mapping']
        labels = ['O'] * len(offset_mapping)
        
        # Process each entity
        for entity in entities:
            start_char = entity['start_char']
            end_char = entity['end_char']
            entity_label = entity['label']
            
            # Skip if label not in our label set
            if entity_label not in BASE_LABELS:
                continue
            
            # Find tokens that belong to this entity
            entity_tokens = []
            for idx, (token_start, token_end) in enumerate(offset_mapping):
                # Skip special tokens
                if token_start == 0 and token_end == 0:
                    continue
                    
                # Check if token overlaps with entity
                if token_start < end_char and token_end > start_char:
                    entity_tokens.append(idx)
            
            # Assign labels
            if entity_tokens:
                labels[entity_tokens[0]] = f'B-{entity_label}'
                for idx in entity_tokens[1:]:
                    labels[idx] = f'I-{entity_label}'
        
        # Convert labels to IDs
        label_ids = []
        for label in labels:
            if label in label2id:
                label_ids.append(label2id[label])
            else:
                label_ids.append(label2id['O'])
        
        return {
            'input_ids': encoding['input_ids'],
            'attention_mask': encoding['attention_mask'],
            'labels': label_ids,
            'original_sentence': sentence
        }
    
    processed_data = []
    for i, example in enumerate(data):
        if i % 1000 == 0:
            print(f"🔄 Processed {i}/{len(data)}")
        processed_data.append(process_example(example))
    return processed_data

# Process the data
processed_data = prepare_dataset(fixed_raw_data, tokenizer, label2id)
# Split the data
print("\n✂️ Splitting data into train/test sets...")
train_data, test_data = train_test_split(
    processed_data, 
    test_size=0.1, 
    random_state=42, 
    shuffle=True
)

print(f"📊 Train set: {len(train_data)} examples")
print(f"📊 Test set: {len(test_data)} examples")

# Convert to HuggingFace Dataset format
train_dataset = Dataset.from_list(train_data)
test_dataset = Dataset.from_list(test_data)

dataset_dict = DatasetDict({
    'train': train_dataset,
    'test': test_dataset
})

print("\n✅ Dataset ready for training!")

# Analyze entity distribution in train set
def analyze_entity_distribution(dataset, id2label):
    entity_counts = defaultdict(int)
    total_entities = 0
    
    for example in dataset:
        for label_id in example['labels']:
            label = id2label[label_id]
            if label != 'O':
                if label.startswith('B-'):
                    entity_type = label[2:]
                    entity_counts[entity_type] += 1
                    total_entities += 1
    
    print("\n📊 Entity distribution in training set:")
    for entity_type, count in sorted(entity_counts.items(), key=lambda x: x[1], reverse=True):
        percentage = (count / total_entities) * 100 if total_entities > 0 else 0
        print(f"  {entity_type}: {count} ({percentage:.1f}%)")
        if entity_type == 'LULC':
            print(f"    ⭐ This is your main focus!")

analyze_entity_distribution(train_dataset, id2label)

# Save everything
dataset_dict.save_to_disk('./processed_dataset')
print("\n💾 Dataset saved to './processed_dataset'")

with open('label_mappings.pkl', 'wb') as f:
    pickle.dump({'label2id': label2id, 'id2label': id2label}, f)
print("✅ Label mappings saved to 'label_mappings.pkl'")

🔄 Processed 0/14522
🔄 Processed 1000/14522
🔄 Processed 2000/14522
🔄 Processed 3000/14522
🔄 Processed 4000/14522
🔄 Processed 5000/14522
🔄 Processed 6000/14522
🔄 Processed 7000/14522
🔄 Processed 8000/14522
🔄 Processed 9000/14522
🔄 Processed 10000/14522
🔄 Processed 11000/14522
🔄 Processed 12000/14522
🔄 Processed 13000/14522
🔄 Processed 14000/14522

✂️ Splitting data into train/test sets...
📊 Train set: 13069 examples
📊 Test set: 1453 examples

✅ Dataset ready for training!

📊 Entity distribution in training set:
  CHANGE: 9123 (28.2%)
  LULC: 5994 (18.5%)
    ⭐ This is your main focus!
  CARDINAL: 4878 (15.1%)
  DATE: 4178 (12.9%)
  LOC: 3493 (10.8%)
  PERCENT: 1391 (4.3%)
  COORDINATES: 1161 (3.6%)
  PROCESS: 1134 (3.5%)
  SURFACE_UNIT: 919 (2.8%)
  QUANTITY: 112 (0.3%)

Saving the dataset (0/1 shards):   0%|          | 0/13069 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1453 [00:00<?, ? examples/s]

💾 Dataset saved to './processed_dataset'
✅ Label mappings saved to 'label_mappings.pkl'

In [14]:
# Load pre-trained RoBERTa and configure it for token classification
model = AutoModelForTokenClassification.from_pretrained(
    "roberta-base",
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

# Move model to GPU if available
model = model.to(device)

print(f"Model loaded: {model.config._name_or_path}")
print(f"Number of parameters: {model.num_parameters():,}")
print(f"Number of labels: {model.config.num_labels}")

# This is what makes RoBERTa context-aware:
# - It has 12 transformer layers that process the entire sentence
# - Each token's representation is influenced by all other tokens
# - The self-attention mechanism learns which tokens to focus on

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model loaded: roberta-base
Number of parameters: 124,071,189
Number of labels: 21

In [15]:
# Load the seqeval metric for NER evaluation
seqeval_metric = evaluate.load("seqeval")

def compute_metrics(eval_pred):
    """
    Compute precision, recall, and F1 score for each entity type.
    This helps you understand how well the model performs on each category.
    """
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=2)
    
    # Convert predictions to label strings
    true_predictions = [
        [id2label[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [id2label[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    
    results = seqeval_metric.compute(predictions=true_predictions, references=true_labels)
    
    # Extract per-entity metrics
    per_entity_results = {}
    for entity in BASE_LABELS:
        if entity in results:
            per_entity_results[f"{entity}_f1"] = results[entity]["f1"]
            per_entity_results[f"{entity}_precision"] = results[entity]["precision"]
            per_entity_results[f"{entity}_recall"] = results[entity]["recall"]
    
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
        **per_entity_results
    }

print("Evaluation metrics configured.")
print("Will track performance for each entity type, especially LULC.")

Evaluation metrics configured.
Will track performance for each entity type, especially LULC.

In [16]:
# Training configuration
# These parameters control how the model learns

training_args = TrainingArguments(
    output_dir="./roberta_ner_model",           # Where to save the model
    learning_rate=3e-5,                         # How fast the model learns (don't set too high!)
    per_device_train_batch_size=8,              # Samples per batch (reduce if GPU memory issues)
    per_device_eval_batch_size=8,               
    num_train_epochs=6,                         # Number of complete passes through data
    weight_decay=0.01,                          # Regularization to prevent overfitting
    evaluation_strategy="epoch",                # When to evaluate
    save_strategy="epoch",                      # When to save checkpoints
    logging_steps=50,                           # How often to log progress
    load_best_model_at_end=True,               # Keep the best model
    metric_for_best_model="f1",                # What metric to use for "best"
    push_to_hub=False,                         # Don't upload to Hugging Face Hub
    report_to="none",                          # Disable wandb/tensorboard
    fp16=torch.cuda.is_available(),            # Use mixed precision if GPU available
    lr_scheduler_type = "linear",
    seed= 42
)

# Data collator handles batching and padding
data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer,
    pad_to_multiple_of=8 if torch.cuda.is_available() else None
)

print(f"Training configuration set:")
print(f"  - Epochs: {training_args.num_train_epochs}")
print(f"  - Batch size: {training_args.per_device_train_batch_size}")
print(f"  - Learning rate: {training_args.learning_rate}")
print(f"  - Mixed precision training: {training_args.fp16}")

Training configuration set:
  - Epochs: 6
  - Batch size: 8
  - Learning rate: 3e-05
  - Mixed precision training: True

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [17]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],  # <-- Changed from dataset_split
    eval_dataset=dataset_dict["test"],    # <-- Changed from dataset_split
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("Trainer initialized and ready.")
print(f"Will train for {len(dataset_dict['train']) // training_args.per_device_train_batch_size * training_args.num_train_epochs} steps")  # <-- Updated to use dataset_dict

Trainer initialized and ready.
Will train for 9798 steps

In [18]:
# Start training!
# This will take some time depending on your hardware
# With GPU: ~5-10 minutes for 2000 sentences
# With CPU: ~30-60 minutes
import time

print("Starting training... This will take some time.")
print("You'll see progress updates and evaluation results after each epoch.\n")

# Train the model
start_time = time.time()
train_result = trainer.train()
training_time = time.time() - start_time


# Save the final model
trainer.save_model("./final_ner_model")
tokenizer.save_pretrained("./final_ner_model")
print(f"⏱️ Training time: {training_time/60:.1f} minutes")
print("\n✓ Training completed!")
print(f"Training loss: {train_result.training_loss:.4f}")

Starting training... This will take some time.
You'll see progress updates and evaluation results after each epoch.

⏱️ Training time: 18.2 minutes

✓ Training completed!
Training loss: 0.0067

In [20]:
# Evaluate the model on the test set
print("Evaluating model performance...\n")
start_time = time.time()

eval_results = trainer.evaluate()
training_time = time.time() - start_time

# Display overall metrics
print("Overall Performance:")
print(f"  Precision: {eval_results['eval_precision']:.3f}")
print(f"  Recall: {eval_results['eval_recall']:.3f}")
print(f"  F1 Score: {eval_results['eval_f1']:.3f}")
print(f"  Accuracy: {eval_results['eval_accuracy']:.3f}")

# Display per-entity metrics if available
print("\nPer-Entity Performance:")
for entity in BASE_LABELS:
    f1_key = f"eval_{entity}_f1"
    if f1_key in eval_results:
        print(f"  {entity}:")
        print(f"    F1: {eval_results[f1_key]:.3f}")
        print(f"    Precision: {eval_results.get(f'eval_{entity}_precision', 0):.3f}")
        print(f"    Recall: {eval_results.get(f'eval_{entity}_recall', 0):.3f}")

Evaluating model performance...

Overall Performance:
  Precision: 0.892
  Recall: 0.907
  F1 Score: 0.899
  Accuracy: 0.999

Per-Entity Performance:
  CHANGE:
    F1: 0.989
    Precision: 0.981
    Recall: 0.996
  LOC:
    F1: 0.791
    Precision: 0.775
    Recall: 0.807
  LULC:
    F1: 0.988
    Precision: 0.986
    Recall: 0.990
  DATE:
    F1: 0.858
    Precision: 0.840
    Recall: 0.877
  PERCENT:
    F1: 0.864
    Precision: 0.848
    Recall: 0.881
  CARDINAL:
    F1: 0.835
    Precision: 0.805
    Recall: 0.867
  COORDINATES:
    F1: 0.612
    Precision: 0.724
    Recall: 0.531
  SURFACE_UNIT:
    F1: 0.880
    Precision: 0.832
    Recall: 0.934
  PROCESS:
    F1: 0.991
    Precision: 0.982
    Recall: 1.000
  QUANTITY:
    F1: 0.353
    Precision: 0.353
    Recall: 0.353

In [21]:
def predict_entities(text, model, tokenizer):
    """Test the model with new text"""
    # Tokenize
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        return_offsets_mapping=True
    )
    
    # Move to device
    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)
    offset_mapping = inputs["offset_mapping"][0].tolist()
    
    # Predict
    model.eval()
    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        predictions = torch.argmax(outputs.logits, dim=-1)
    
    # Convert predictions to labels
    tokens = tokenizer.convert_ids_to_tokens(input_ids[0])
    predicted_labels = [id2label[pred.item()] for pred in predictions[0]]
    
    # Extract entities
    entities = []
    current_entity = None
    
    for idx, (token, label, (start, end)) in enumerate(zip(tokens, predicted_labels, offset_mapping)):
        if label.startswith("B-"):
            if current_entity:
                entities.append(current_entity)
            current_entity = {
                "text": tokenizer.decode(input_ids[0][idx:idx+1]),
                "label": label[2:],
                "start": start,
                "end": end,
                "tokens": [token]
            }
        elif label.startswith("I-") and current_entity and label[2:] == current_entity["label"]:
            current_entity["tokens"].append(token)
            current_entity["end"] = end
            current_entity["text"] = text[current_entity["start"]:current_entity["end"]]
        else:
            if current_entity:
                entities.append(current_entity)
                current_entity = None
    
    if current_entity:
        entities.append(current_entity)
    
    return entities

# Test with examples
test_sentences = [
    "In the Amazon Basin (~3°S, 60°W), between 2001 and 2020, forest cover decreased by ~9%, representing a loss of over 54.2 million hectares, largely due to deforestation.",
    "Globally, approximately 420 million hectares of forest have been lost since 1990 (~10% of total forest area), mainly to agriculture, though the annual deforestation rate fell from ~16 million ha in the 1990s to ~10 million ha in the late 2010s.",
    "The Sahara Desert (~23°N, 13°E) has expanded by about 10% since 1920, encroaching on an additional ~700,000 km² of land due to climate change and reduced rainfall (accelerating desertification).",
    "In the Gran Chaco (~24°S, 62°W), over 20% of the native forest has been cleared since the 1980s (~142,000 km²) for cattle ranching and soybean farming, making it one of the world's most rapidly deforested regions.",
    "In Indonesia (~1°S, 113°E), rapid deforestation caused forest cover to shrink by ~20% between 1990 and 2010 (a loss of around 24 million hectares), primarily due to the expansion of oil palm plantations.",
    "In China (~35°N, 105°E), urban land area increased by nearly 500% between 1992 and 2015 (from ~12,200 km² to ~72,900 km²) due to rapid urbanization and economic development, often replacing agricultural land.",
    "In China (~35°N, 110°E), forest cover rose from 16.7% to 22.5% of the country's area between 1990 and 2015 – a gain of about 511,800 km² – thanks to large-scale afforestation programs.",
    "In the European Union (~50°N, 15°E), forest area expanded by nearly 10% from 1990 to 2020, growing from ~145 million to 159 million hectares, as farmland abandonment and reforestation projects increased wooded land.",
    "In Russia (~55°N, 40°E), around 50 million hectares of cropland (about 34% of the 1991 farmland area) were abandoned after the Soviet Union's collapse, allowing forests and grasslands to regenerate naturally and sequester ~50 million tons of carbon annually.",
    "In Saudi Arabia (~24°N, 45°E), desert areas were converted to farmland through intensive irrigation; irrigated cropland expanded from under 4,000 km² in 1970 to over 8,000 km² by the early 1990s (>100% increase), although this led to >60% depletion of nonrenewable groundwater over 25 years.",
    "In Central Asia (~45°N, 60°E), the Aral Sea has largely dried up: its surface area shrank by ~85% from 1960 to 2012 (from ~67,500 km² to ~10,000 km²) as Soviet river diversions for irrigation created a new desert on the former lakebed.",
    "In West Africa (~13°N, 14°E), Lake Chad's surface area has plummeted by over 90% since the 1960s (shrinking from ~25,000 km² to <2,000 km² by the early 2000s) due to prolonged drought and water diversion, devastating local agriculture and fisheries.",
    "In Vietnam’s Mekong Delta (~10°N, 106°E), mangrove forests declined by over 50% from the late 1970s to early 1990s, as ~100,000 hectares were cleared for shrimp aquaculture and other development.",
    "In India (~22°N, 79°E), the area of land undergoing degradation increased from ~94.5 million hectares (28.8% of the country) in 2005 to ~96.4 million hectares (29.3%) by 2013, reflecting growing desertification caused by deforestation, overgrazing, and soil erosion.",


]
print("\n🧪 Testing model with example sentences:")
for sentence in test_sentences:
    print(f"\n📝 Input: {sentence}")
    entities = predict_entities(sentence, model, tokenizer)
    print("🏷️ Detected entities:")
    for entity in entities:
        print(f"   - {entity['text']} → {entity['label']}")

🧪 Testing model with example sentences:

📝 Input: In the Amazon Basin (~3°S, 60°W), between 2001 and 2020, forest cover decreased by ~9%, representing a loss of over 54.2 million hectares, largely due to deforestation.
🏷️ Detected entities:
   -  60 → CARDINAL
   - between 2001 and 2020 → DATE
   -  forest → LULC
   -  decreased → CHANGE
   - ~9%, → PERCENT
   -  loss → CHANGE
   - 54.2 million hectares → SURFACE_UNIT
   -  deforestation → PROCESS

📝 Input: Globally, approximately 420 million hectares of forest have been lost since 1990 (~10% of total forest area), mainly to agriculture, though the annual deforestation rate fell from ~16 million ha in the 1990s to ~10 million ha in the late 2010s.
🏷️ Detected entities:
   - 420 million hectares → SURFACE_UNIT
   -  forest → LULC
   -  1990 → DATE
   -  forest → LULC
   -  agriculture → LULC
   -  annual → DATE
   -  deforestation → PROCESS
   -  ha → SURFACE_UNIT
   - the 1990s → DATE
   -  ha → SURFACE_UNIT
   - the late 2010s → DATE

📝 Input: The Sahara Desert (~23°N, 13°E) has expanded by about 10% since 1920, encroaching on an additional ~700,000 km² of land due to climate change and reduced rainfall (accelerating desertification).
🏷️ Detected entities:
   - The Sahara Desert → LOC
   -  13 → CARDINAL
   -  expanded → CHANGE
   - about 10% → PERCENT
   -  1920 → DATE
   - ~700,000 km² → SURFACE_UNIT
   -  change → CHANGE
   - desertification → PROCESS

📝 Input: In the Gran Chaco (~24°S, 62°W), over 20% of the native forest has been cleared since the 1980s (~142,000 km²) for cattle ranching and soybean farming, making it one of the world's most rapidly deforested regions.
🏷️ Detected entities:
   -  62 → CARDINAL
   - over 20% → PERCENT
   -  forest → LULC
   - the 1980s → DATE
   - (~142,000 km² → SURFACE_UNIT

📝 Input: In Indonesia (~1°S, 113°E), rapid deforestation caused forest cover to shrink by ~20% between 1990 and 2010 (a loss of around 24 million hectares), primarily due to the expansion of oil palm plantations.
🏷️ Detected entities:
   -  Indonesia → LOC
   - 1 → CARDINAL
   -  113 → CARDINAL
   -  deforestation → PROCESS
   -  caused → CHANGE
   -  forest → LULC
   - ~20% → PERCENT
   - between 1990 and 2010 → DATE
   -  loss → CHANGE
   - 24 million hectares → SURFACE_UNIT
   -  expansion → CHANGE

📝 Input: In China (~35°N, 105°E), urban land area increased by nearly 500% between 1992 and 2015 (from ~12,200 km² to ~72,900 km²) due to rapid urbanization and economic development, often replacing agricultural land.
🏷️ Detected entities:
   -  China → LOC
   - 35 → CARDINAL
   -  105 → CARDINAL
   -  urban → LULC
   -  increased → CHANGE
   - nearly 500% → PERCENT
   - between 1992 and 2015 → DATE
   - ~12,200 km² to ~72,900 km² → SURFACE_UNIT
   - urbanization → PROCESS

📝 Input: In China (~35°N, 110°E), forest cover rose from 16.7% to 22.5% of the country's area between 1990 and 2015 – a gain of about 511,800 km² – thanks to large-scale afforestation programs.
🏷️ Detected entities:
   -  China → LOC
   -  110 → CARDINAL
   -  forest → LULC
   - 16.7% to 22.5% → PERCENT
   -  area → SURFACE_UNIT
   - between 1990 and 2015 → DATE
   -  gain → CHANGE
   - about 511,800 km² → SURFACE_UNIT
   - afforestation → PROCESS

📝 Input: In the European Union (~50°N, 15°E), forest area expanded by nearly 10% from 1990 to 2020, growing from ~145 million to 159 million hectares, as farmland abandonment and reforestation projects increased wooded land.
🏷️ Detected entities:
   - 50 → CARDINAL
   -  15 → CARDINAL
   -  forest → LULC
   -  expanded → CHANGE
   - nearly 10% → PERCENT
   -  1990 → DATE
   -  2020 → DATE
   -  growing → CHANGE
   - 159 million hectares → SURFACE_UNIT
   - reforestation → PROCESS
   -  increased → CHANGE

📝 Input: In Russia (~55°N, 40°E), around 50 million hectares of cropland (about 34% of the 1991 farmland area) were abandoned after the Soviet Union's collapse, allowing forests and grasslands to regenerate naturally and sequester ~50 million tons of carbon annually.
🏷️ Detected entities:
   -  Russia → LOC
   - 55 → CARDINAL
   -  40 → CARDINAL
   - around 50 million hectares → SURFACE_UNIT
   - cropland → LULC
   - about 34% → PERCENT
   -  1991 → DATE
   -  forests → LULC
   - grasslands → LULC
   -  annually → DATE

📝 Input: In Saudi Arabia (~24°N, 45°E), desert areas were converted to farmland through intensive irrigation; irrigated cropland expanded from under 4,000 km² in 1970 to over 8,000 km² by the early 1990s (>100% increase), although this led to >60% depletion of nonrenewable groundwater over 25 years.
🏷️ Detected entities:
   - Saudi Arabia → LOC
   -  45 → CARDINAL
   -  converted → CHANGE
   - cropland → LULC
   -  expanded → CHANGE
   - 4,000 km² → SURFACE_UNIT
   -  1970 → DATE
   - 8,000 km² → SURFACE_UNIT
   - the early 1990s → DATE
   - 100% → PERCENT
   -  increase → CHANGE
   - 60% → PERCENT
   - 25 years → DATE

📝 Input: In Central Asia (~45°N, 60°E), the Aral Sea has largely dried up: its surface area shrank by ~85% from 1960 to 2012 (from ~67,500 km² to ~10,000 km²) as Soviet river diversions for irrigation created a new desert on the former lakebed.
🏷️ Detected entities:
   - Central Asia → LOC
   -  60 → CARDINAL
   - the Aral Sea → LOC
   - 1960 to → DATE
   -  2012 → DATE
   - ~67,500 km² to ~10,000 km² → SURFACE_UNIT

📝 Input: In West Africa (~13°N, 14°E), Lake Chad's surface area has plummeted by over 90% since the 1960s (shrinking from ~25,000 km² to <2,000 km² by the early 2000s) due to prolonged drought and water diversion, devastating local agriculture and fisheries.
🏷️ Detected entities:
   - West Africa → LOC
   -  14 → CARDINAL
   - Lake Chad → LOC
   - over 90% → PERCENT
   - the 1960s → DATE
   - ~25,000 km² → SURFACE_UNIT
   - 2,000 km² → SURFACE_UNIT
   - the early 2000s → DATE
   -  water → LULC
   -  agriculture → LULC

📝 Input: In Vietnam’s Mekong Delta (~10°N, 106°E), mangrove forests declined by over 50% from the late 1970s to early 1990s, as ~100,000 hectares were cleared for shrimp aquaculture and other development.
🏷️ Detected entities:
   -  Vietnam → LOC
   - Mekong Delta → LOC
   -  106 → CARDINAL
   -  forests → LULC
   -  declined → CHANGE
   - over 50% → PERCENT
   - the late 1970s to early 1990s → DATE
   - ~100,000 hectares → SURFACE_UNIT

📝 Input: In India (~22°N, 79°E), the area of land undergoing degradation increased from ~94.5 million hectares (28.8% of the country) in 2005 to ~96.4 million hectares (29.3%) by 2013, reflecting growing desertification caused by deforestation, overgrazing, and soil erosion.
🏷️ Detected entities:
   -  India → LOC
   -  79 → CARDINAL
   -  increased → CHANGE
   - ~94.5 million hectares → SURFACE_UNIT
   - 28.8% → PERCENT
   -  2005 → DATE
   - ~96.4 million hectares → SURFACE_UNIT
   - 29.3%) → PERCENT
   -  2013 → DATE
   -  growing → CHANGE
   - desertification → PROCESS
   -  caused → CHANGE
   -  deforestation → PROCESS
   -  erosion → PROCESS

In [24]:
def extract_entities(text, model_path="./final_ner_model"):
    """
    Extract entities from new text using the trained model.
    This function shows how to use your model in practice.
    """
    # Load model and tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForTokenClassification.from_pretrained(model_path)
    model.eval()
    
    # Tokenize input
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512,
        return_offsets_mapping=True,
        padding=True
    )
    
    # Get predictions
    with torch.no_grad():
        outputs = model(**{k: v for k, v in inputs.items() if k != 'offset_mapping'})
        predictions = torch.argmax(outputs.logits, dim=-1)
    
    # Convert predictions to labels
    tokens = tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])
    labels = [model.config.id2label[pred.item()] for pred in predictions[0]]
    offset_mapping = inputs['offset_mapping'][0]
    
    # Extract entities
    entities = []
    current_entity = None
    
    for idx, (token, label, offset) in enumerate(zip(tokens, labels, offset_mapping)):
        if token in tokenizer.all_special_tokens:
            continue
            
        if label.startswith('B-'):
            # Start of new entity
            if current_entity:
                entities.append(current_entity)
            current_entity = {
                'text': tokenizer.convert_tokens_to_string([token]),
                'label': label[2:],
                'start': offset[0].item(),
                'end': offset[1].item(),
                'tokens': [token]
            }
        elif label.startswith('I-') and current_entity and label[2:] == current_entity['label']:
            # Continuation of current entity
            current_entity['tokens'].append(token)
            current_entity['end'] = offset[1].item()
            current_entity['text'] = tokenizer.convert_tokens_to_string(current_entity['tokens'])
        else:
            # Not an entity
            if current_entity:
                entities.append(current_entity)
                current_entity = None
    
    if current_entity:
        entities.append(current_entity)
    
    # Clean up entity text
    for entity in entities:
        entity['text'] = entity['text'].strip()
        del entity['tokens']
    
    return entities

# Test the extraction function
test_sentences = [
    "In the Congo Basin (~0°, 20°E), annual deforestation rates increased by ~32% between 2005 and 2020, rising from ~1.36 million ha to ~1.79 million ha per year due to logging, farming, and mining; if this trend continues, over 25% of the remaining rainforest could disappear by 2050.",
    "In the U.S. Great Plains (~36°N, 100°W), severe drought and poor farming practices during the 1930s Dust Bowl stripped topsoil from about 40 million hectares of farmland (around 100 million acres), rendering ~14 million hectares unusable by 1934.",
    "Urban sprawl led to conversion of green spaces into commercial zones.",
    "In the United States (~38°N, 97°W), about 12.5 million hectares of agricultural land (roughly 31 million acres) were irreversibly lost to development between 1992 and 2012 – an area nearly the size of Iowa – as urban sprawl expanded over farmland.",
    "In Costa Rica (~10°N, 84°W), forest cover rebounded from around 21% of the land in the 1980s to over 50% by 2013, regaining roughly 1.5 million hectares of forest thanks to aggressive conservation and reforestation policies that reversed decades of deforestation.",
    "Côte d’Ivoire (~7°N, 5°W) has lost more than 80% of its forest cover since 1960 (dropping from ~12 million to ~2 million hectares remaining), mainly due to cocoa farming, giving it one of the highest deforestation rates in Africa.",
    "In Borneo (~0°, 114°E), tropical forest cover declined by over 30% between the 1970s and mid-2010s – a loss of roughly 16 million hectares – as logging and oil palm plantations replaced vast areas of rainforest.",
    "Worldwide, at least 64% of wetlands have disappeared since 1900, largely due to drainage for agriculture and urban development, with losses exceeding 80% in some regions despite their ecological importance.",


    
    "In the Amazon Basin (~3°S, 60°W), between 2001 and 2020, forest cover decreased by ~9%, representing a loss of over 54.2 million hectares, largely due to deforestation."

]

print("Testing entity extraction on new sentences:\n")
for sentence in test_sentences:
    print(f"Text: {sentence}")
    entities = extract_entities(sentence)
    print("Extracted entities:")
    for ent in entities:
        print(f"  - '{ent['text']}' → {ent['label']}")
    print()

Testing entity extraction on new sentences:

Text: In the Congo Basin (~0°, 20°E), annual deforestation rates increased by ~32% between 2005 and 2020, rising from ~1.36 million ha to ~1.79 million ha per year due to logging, farming, and mining; if this trend continues, over 25% of the remaining rainforest could disappear by 2050.
Extracted entities:
  - 'Congo Basin' → LOC
  - 'annual' → DATE
  - 'deforestation' → PROCESS
  - 'increased' → CHANGE
  - '~32%' → PERCENT
  - 'between 2005 and 2020' → DATE
  - '1.36 million' → COORDINATES
  - 'ha' → SURFACE_UNIT
  - '1.79 million' → COORDINATES
  - 'ha' → SURFACE_UNIT
  - 'over 25%' → PERCENT
  - '2050' → DATE

Text: In the U.S. Great Plains (~36°N, 100°W), severe drought and poor farming practices during the 1930s Dust Bowl stripped topsoil from about 40 million hectares of farmland (around 100 million acres), rendering ~14 million hectares unusable by 1934.
Extracted entities:
  - 'U.S.' → LOC
  - '100' → CARDINAL
  - 'the 1930s' → DATE
  - 'about 40 million hectares' → SURFACE_UNIT
  - '100 million acres' → SURFACE_UNIT
  - 'hectares' → SURFACE_UNIT
  - '1934' → DATE

Text: Urban sprawl led to conversion of green spaces into commercial zones.
Extracted entities:
  - 'Urban' → LULC

Text: In the United States (~38°N, 97°W), about 12.5 million hectares of agricultural land (roughly 31 million acres) were irreversibly lost to development between 1992 and 2012 – an area nearly the size of Iowa – as urban sprawl expanded over farmland.
Extracted entities:
  - 'the United States' → LOC
  - '97' → CARDINAL
  - 'about 12.5 million hectares' → SURFACE_UNIT
  - '31 million acres' → SURFACE_UNIT
  - 'between 1992 and 2012' → DATE
  - 'Iowa' → LOC
  - 'urban' → LULC
  - 'expanded' → CHANGE

Text: In Costa Rica (~10°N, 84°W), forest cover rebounded from around 21% of the land in the 1980s to over 50% by 2013, regaining roughly 1.5 million hectares of forest thanks to aggressive conservation and reforestation policies that reversed decades of deforestation.
Extracted entities:
  - 'Costa Rica' → LOC
  - '84' → CARDINAL
  - 'forest' → LULC
  - 'around 21%' → PERCENT
  - 'the 1980s' → DATE
  - 'over 50%' → PERCENT
  - '2013' → DATE
  - '1.5 million hectares' → SURFACE_UNIT
  - 'forest' → LULC
  - 'reforestation' → PROCESS
  - 'decades' → DATE
  - 'deforestation' → PROCESS

Text: Côte d’Ivoire (~7°N, 5°W) has lost more than 80% of its forest cover since 1960 (dropping from ~12 million to ~2 million hectares remaining), mainly due to cocoa farming, giving it one of the highest deforestation rates in Africa.
Extracted entities:
  - '5' → CARDINAL
  - 'more than 80%' → PERCENT
  - 'forest' → LULC
  - '1960' → DATE
  - 'hectares' → SURFACE_UNIT
  - 'one' → CARDINAL
  - 'deforestation' → PROCESS
  - 'Africa' → LOC

Text: In Borneo (~0°, 114°E), tropical forest cover declined by over 30% between the 1970s and mid-2010s – a loss of roughly 16 million hectares – as logging and oil palm plantations replaced vast areas of rainforest.
Extracted entities:
  - '0' → CARDINAL
  - '114' → DATE
  - 'forest' → LULC
  - 'declined' → CHANGE
  - 'over 30%' → PERCENT
  - 'between the 1970s and mid-2010s' → DATE
  - 'loss' → CHANGE
  - '16 million hectares' → SURFACE_UNIT

Text: Worldwide, at least 64% of wetlands have disappeared since 1900, largely due to drainage for agriculture and urban development, with losses exceeding 80% in some regions despite their ecological importance.
Extracted entities:
  - 'at least 64%' → PERCENT
  - 'wetlands' → LULC
  - '1900' → DATE
  - 'agriculture' → LULC
  - 'urban development' → PROCESS
  - 'losses' → CHANGE
  - '80%' → PERCENT

Text: In the Amazon Basin (~3°S, 60°W), between 2001 and 2020, forest cover decreased by ~9%, representing a loss of over 54.2 million hectares, largely due to deforestation.
Extracted entities:
  - '60' → CARDINAL
  - 'between 2001 and 2020' → DATE
  - 'forest' → LULC
  - 'decreased' → CHANGE
  - '~9%,' → PERCENT
  - 'loss' → CHANGE
  - '54.2 million hectares' → SURFACE_UNIT
  - 'deforestation' → PROCESS

In [3]:
!pip install pdfplumber==0.10.3 pdfminer.six==20231228

Collecting pdfplumber==0.10.3
  Downloading pdfplumber-0.10.3-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 1.8 MB/s eta 0:00:011
Collecting pdfminer.six==20231228
  Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 3.9 MB/s eta 0:00:01
Requirement already satisfied: Pillow>=9.1 in /home/raham/venv/lib/python3.8/site-packages (from pdfplumber==0.10.3) (10.2.0)
Collecting pypdfium2>=4.18.0
  Using cached pypdfium2-4.30.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
Requirement already satisfied: charset-normalizer>=2.0.0 in /home/raham/venv/lib/python3.8/site-packages (from pdfminer.six==20231228) (3.4.2)
Collecting cryptography>=36.0.0
  Downloading cryptography-45.0.5-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 4.1 MB/s eta 0:00:01
Requirement already satisfied: cffi>=1.14; platform_python_implementation != "PyPy" in /home/raham/venv/lib/python3.8/site-packages (from cryptography>=36.0.0->pdfminer.six==20231228) (1.17.1)
Requirement already satisfied: pycparser in /home/raham/venv/lib/python3.8/site-packages (from cffi>=1.14; platform_python_implementation != "PyPy"->cryptography>=36.0.0->pdfminer.six==20231228) (2.22)
ERROR: pdfplumber 0.10.3 has requirement pdfminer.six==20221105, but you'll have pdfminer-six 20231228 which is incompatible.
Installing collected packages: cryptography, pdfminer.six, pypdfium2, pdfplumber
Successfully installed cryptography-45.0.5 pdfminer.six-20231228 pdfplumber-0.10.3 pypdfium2-4.30.0

In [5]:
!pip install PyMuPDF

Requirement already satisfied: PyMuPDF in /home/raham/venv/lib/python3.8/site-packages (1.24.11)

In [30]:
import fitz  # PyMuPDF
import pandas as pd
import torch
import nltk
from transformers import AutoTokenizer, AutoModelForTokenClassification

nltk.download('punkt', quiet=True)

# Set device first
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load model and tokenizer
model_path = "./final_ner_model"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForTokenClassification.from_pretrained(model_path)

# IMPORTANT: Move model to the device
model.to(device)
model.eval()

# Get id2label mapping from model config
id2label = model.config.id2label

# Verify everything is set up correctly
try:
    model
    tokenizer
    device
    id2label
    print("✅ All required variables are available")
    print(f"Model device: {next(model.parameters()).device}")
    print(f"Device variable: {device}")
except NameError as e:
    print(f"❌ Missing variable: {e}")

# Define the PDF file path
pdf_file_path = 'relations_table_20250709_165543 - Sheet5.pdf'  # Update this path

def extract_sentences_from_pdf(file_path):
    """Extract sentences from a PDF file using PyMuPDF."""
    sentences = []
    
    try:
        doc = fitz.open(file_path)
        for page_num in range(len(doc)):
            page = doc.load_page(page_num)
            text = page.get_text()
            
            if text:
                # Split text into sentences
                page_sentences = nltk.sent_tokenize(text)
                sentences.extend([s.strip() for s in page_sentences if s.strip()])
        
        doc.close()
    except Exception as e:
        print(f"Error reading PDF: {e}")
    
    return sentences

def predict_entities(text, model, tokenizer, device, id2label):
    """Test the model with new text"""
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        return_offsets_mapping=True,
        max_length=512
    )
    
    # Move input tensors to the same device as model
    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)
    offset_mapping = inputs["offset_mapping"][0].tolist()
    
    model.eval()
    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        predictions = torch.argmax(outputs.logits, dim=-1)
    
    # Move predictions back to CPU for processing
    predictions = predictions.cpu()
    input_ids_cpu = input_ids.cpu()
    
    tokens = tokenizer.convert_ids_to_tokens(input_ids_cpu[0])
    predicted_labels = [id2label[pred.item()] for pred in predictions[0]]
    
    entities = []
    current_entity = None
    
    for idx, (token, label, (start, end)) in enumerate(zip(tokens, predicted_labels, offset_mapping)):
        # Skip special tokens
        if token in tokenizer.all_special_tokens:
            continue
            
        if label.startswith("B-"):
            if current_entity:
                entities.append(current_entity)
            current_entity = {
                "text": text[start:end],
                "label": label[2:],
                "start": start,
                "end": end
            }
        elif label.startswith("I-") and current_entity and label[2:] == current_entity["label"]:
            current_entity["end"] = end
            current_entity["text"] = text[current_entity["start"]:current_entity["end"]]
        else:
            if current_entity:
                entities.append(current_entity)
                current_entity = None
    
    if current_entity:
        entities.append(current_entity)
    
    return entities

# Extract sentences from PDF
print(f"📄 Reading PDF from: {pdf_file_path}")
sentences = extract_sentences_from_pdf(pdf_file_path)
print(f"📚 Extracted {len(sentences)} sentences from PDF\n")

# Process each sentence and collect results
results = []
all_output_data = []

print("🧪 Processing sentences and extracting entities...\n")
print("="*80)

for idx, sentence in enumerate(sentences):
    if not sentence or sentence.strip() == "":
        continue
    
    # Predict entities - pass all required parameters
    entities = predict_entities(sentence, model, tokenizer, device, id2label)
    
    # Display results for this sentence
    print(f"\n📄 Sentence {idx + 1}:")
    print(f"📝 Text: {sentence}")
    
    if entities:
        print("🏷️  Detected Entities:")
        for entity in entities:
            print(f"    • {entity['text']} → {entity['label']} (positions: {entity['start']}-{entity['end']})")
            
            # Collect data for DataFrame
            all_output_data.append({
                "Sentence_ID": idx + 1,
                "Sentence": sentence,
                "Entity": entity['text'],
                "Entity_Type": entity['label'],
                "Start_Position": entity['start'],
                "End_Position": entity['end']
            })
    else:
        print("    ❌ No entities detected")
        all_output_data.append({
            "Sentence_ID": idx + 1,
            "Sentence": sentence,
            "Entity": None,
            "Entity_Type": None,
            "Start_Position": None,
            "End_Position": None
        })
    
    print("-"*80)
    
    # Store result
    results.append({
        "sentence_id": idx + 1,
        "sentence": sentence,
        "entities": entities
    })

# Create DataFrame with results
df_results = pd.DataFrame(all_output_data)

# Summary statistics
print("\n📈 SUMMARY STATISTICS:")
print(f"Total sentences processed: {len(results)}")
total_entities = sum(len(r['entities']) for r in results)
print(f"Total entities detected: {total_entities}")

# Count entities by type
entity_counts = {}
for result in results:
    for entity in result['entities']:
        entity_type = entity['label']
        entity_counts[entity_type] = entity_counts.get(entity_type, 0) + 1

print("\nEntity counts by type:")
for entity_type, count in sorted(entity_counts.items()):
    print(f"  • {entity_type}: {count}")

# Display DataFrame
print("\n📊 Results DataFrame:")
display(df_results)

# Optional: Save to CSV
df_results.to_csv('entity_extraction_results.csv', index=False)
print("\n💾 Results saved to entity_extraction_results.csv")

Using device: cuda
✅ All required variables are available
Model device: cuda:0
Device variable: cuda
📄 Reading PDF from: relations_table_20250709_165543 - Sheet5.pdf
📚 Extracted 2 sentences from PDF

🧪 Processing sentences and extracting entities...

================================================================================

📄 Sentence 1:
📝 Text: sentenceID
sentence
source
source_type
relationship
target
target_type
confidence
1 After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was often considered as irreversible desertification and large parts of the Sahel were designated as degraded land (e.g
2  The forests of West and Central Africa probably originally covered a combined area of about 3 million km 2
3  Land use change in the study site, p: ref: 2a, 2b, From 1996 to 2017, the area covered by cropped fields, C, has increased from 40% to 51.3% over the study site area, and from 47% to 64% of the arable lands in the study site due to the loss fallows
4 Agriculture in this region has been dominated over the past three decades by cotton production
5 Forest land was decreased nearly by half in 2002 compared to its coverage in 1984, while the size of the gallery forest did not change much
6 About 26 and 31% of the total area of natural vegetation (forest, woodland and tree savanna) will be converted to farmland and degraded savanna by 2050 if we assume the dynamics recorded from 1975 to 1990 and 1990-2010, respectively
7 Assuming the dynamics recorded in the second period , the amounts of land covered by forest, woodland and tree savanna will decrease by 5, 9 and 17% of their cover in 1990, respectively, while the amount of degraded savanna and farmland will increase by 9 and 22% of the total area, respectively
8 Conversely the decrease in the herbaceous standing crop, due to the shortening of the fallow period, the extension of cultivated and cleared fields, the grazing by cattle, and more generally the increment in landscape discontinuities limit the spread of fire and the size of burnt areas
9 describes Rwandan agriculture as caught in a "low investment trap"; less than 10% of cropland is irrigated, while tractors, bank credit and government aid are all scarce
10 Due to the weeding practice, bare soil dominates in cropped fields in the early growing season while herbaceous vegetation continues to grow in fallows and rangelands
11 In 1986, the grazing land had much higher proportion of the total regional area than other land use types while the size of croplands was substantially high after 16 years (Table )
12 In 1990, woodland and tree savanna were still the dominant land cover types
13 In fact, some NTFP-providing trees, such as the baobab (Adansonia digitata) and the shea tree (Vitellaria paradoxa), are protected by farmers during the agricultural cycle of cultivation and fallows and are therefore still well preserved
14 In rangelands, the main cause of woody vegetation decrease is the increasing pressure on wood resources to satisfy the demand for fuel and construction wood, not only from the local rural population, but also from the rapidly growing urban population of Niamey only 80 km away
15 In Saloum Senegal, with the increase of cultivated land and shortening of fallow cycles, soils have become less fertile close to the villages, although fallow land away from the settlement gained in size, mainly due to out-migration
16 Irrigation from rivers is regarded as minor driver of LULCC
17 On the one hand, tree growth and agroforestry on fields have led to an increase of woody cover in proximity to the village
18 Rangelands are grazed year-round under communal access but grazing also extends to fallows, year-round or only in the dry season depending on accessibility, and to cropped fields after the crop harvest
19 Ratios of fallow to cultivated area are 0.8 in Woure, where the bushfallow system is "already defunct," 1.6 in Silgey and Kolbila, where bush-fallow "would lead to a steady decline in fertility," 2 in Koho, where bush-fallow is "marginal," and 5 in Sayero, where available land is still "more than adequate."
🏷️  Detected Entities:
    • the 1970s and 1980s → DATE (positions: 106-125)
    • loss → CHANGE (positions: 140-144)
    • desertification → PROCESS (positions: 208-223)
    • forests → LULC (positions: 298-305)
    • West → LOC (positions: 309-313)
    • Central Africa → LOC (positions: 318-332)
    • area of about 3 million km → SURFACE_UNIT (positions: 372-398)
    • 2
3 → CARDINAL (positions: 399-402)
    • change → CHANGE (positions: 413-419)
    • 2a, 2b → COORDINATES (positions: 447-453)
    • 1996 to 2017 → DATE (positions: 460-472)
    • increased → CHANGE (positions: 517-526)
    • 40% to 51.3% → PERCENT (positions: 532-544)
    • 47% to 64% → PERCENT (positions: 580-590)
    • loss → CHANGE (positions: 640-644)
    • fallows → LULC (positions: 645-652)
    • Agriculture → LULC (positions: 655-666)
    • the past three decades → DATE (positions: 706-728)
    • 5 → CARDINAL (positions: 750-751)
    • Forest → LULC (positions: 752-758)
    • decreased → CHANGE (positions: 768-777)
    • half → CARDINAL (positions: 788-792)
    • 2002 → DATE (positions: 796-800)
    • 1984 → DATE (positions: 829-833)
    • forest → LULC (positions: 865-871)
    • change → CHANGE (positions: 880-886)
    • About 26 → CARDINAL (positions: 894-902)
    • 31% → PERCENT (positions: 907-910)
    • forest → LULC (positions: 952-958)
    • tree → LULC (positions: 973-977)
    • savanna → LULC (positions: 978-985)
    • converted → CHANGE (positions: 995-1004)
    • savanna → LULC (positions: 1030-1037)
    • 2050 → DATE (positions: 1041-1045)
    • 1975 to → DATE (positions: 1086-1093)
    • 1990 → DATE (positions: 1094-1098)
    • 1990-2010 → COORDINATES (positions: 1103-1112)
    • 7 → CARDINAL (positions: 1127-1128)
    • forest → LULC (positions: 1214-1220)
    • tree → LULC (positions: 1235-1239)
    • savanna → LULC (positions: 1240-1247)
    • decrease → CHANGE (positions: 1253-1261)
    • 5, 9 → COORDINATES (positions: 1265-1269)
    • 17% → PERCENT (positions: 1274-1277)
    • 1990 → DATE (positions: 1296-1300)
    • savanna → LULC (positions: 1345-1352)
    • increase → CHANGE (positions: 1371-1379)
    • 9 → CARDINAL (positions: 1383-1384)
    • 22% → PERCENT (positions: 1389-1392)
    • 8 → CARDINAL (positions: 1425-1426)
    • decrease → CHANGE (positions: 1442-1450)
    • crop → LULC (positions: 1478-1482)
    • fallow → LULC (positions: 1513-1519)
    • burnt areas → LULC (positions: 1702-1713)
    • 9 → CARDINAL (positions: 1714-1715)
    • Rwandan → LOC (positions: 1726-1733)
    • agriculture → LULC (positions: 1734-1745)
    • less than 10% → PERCENT (positions: 1784-1797)
    • cropland → LULC (positions: 1801-1809)
    • bare soil → LULC (positions: 1918-1927)
    • cropped → LULC (positions: 1941-1948)
    • the early growing → DATE (positions: 1959-1976)
    • herbaceous vegetation → LULC (positions: 1990-2011)
    • grow → CHANGE (positions: 2025-2029)
    • fallows → LULC (positions: 2033-2040)
    • 1986 → DATE (positions: 2062-2066)
    • croplands → LULC (positions: 2183-2192)
    • 16 years → DATE (positions: 2222-2230)
    • 1990 → DATE (positions: 2246-2250)
    • tree → LULC (positions: 2265-2269)
    • savanna → LULC (positions: 2270-2277)
--------------------------------------------------------------------------------

📄 Sentence 2:
📝 Text: 20 Regular cultivation keeps the soil penetrable and farmers are aware of the benefits of trees in their fields
🏷️  Detected Entities:
    • 20 → CARDINAL (positions: 0-2)
    • cultivation → PROCESS (positions: 11-22)
    • trees → LULC (positions: 90-95)
--------------------------------------------------------------------------------

📈 SUMMARY STATISTICS:
Total sentences processed: 2
Total entities detected: 74

NameError: name 'page_num' is not defined

In [31]:
import pandas as pd
import torch
import nltk
from transformers import AutoTokenizer, AutoModelForTokenClassification

nltk.download('punkt', quiet=True)

# Set device first
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load model and tokenizer
model_path = "./final_ner_model"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForTokenClassification.from_pretrained(model_path)

# IMPORTANT: Move model to the device
model.to(device)
model.eval()

# Get id2label mapping from model config
id2label = model.config.id2label

# Verify everything is set up correctly
print("✅ All required variables are available")
print(f"Model device: {next(model.parameters()).device}")
print(f"Device variable: {device}")

# Define the CSV file path
csv_file_path = 'lulc_relations_EVALUATION_csv  - Roberto .csv'  # Update this path

def load_sentences_from_csv(file_path, sentence_column='sentence'):
    """Load sentences from CSV file."""
    try:
        # Read CSV file
        df = pd.read_csv(file_path)
        print(f"📄 CSV loaded successfully!")
        print(f"📊 Shape: {df.shape}")
        print(f"📋 Columns: {df.columns.tolist()}")
        
        # Check if the sentence column exists
        if sentence_column not in df.columns:
            print(f"❌ Column '{sentence_column}' not found!")
            print(f"Available columns: {df.columns.tolist()}")
            
            # Try to find a likely sentence column
            possible_cols = ['sentence', 'text', 'content', 'description']
            for col in possible_cols:
                if col in df.columns:
                    print(f"🔄 Using column '{col}' instead")
                    sentence_column = col
                    break
            else:
                print("Please specify the correct column name")
                return [], df
        
        # Extract sentences, removing any NaN values
        sentences = df[sentence_column].dropna().astype(str).tolist()
        
        # Filter out very short sentences or obvious non-sentences
        filtered_sentences = []
        for sentence in sentences:
            sentence = sentence.strip()
            if len(sentence) > 10 and not sentence.lower().startswith(('sentenceid', 'sentence')):
                filtered_sentences.append(sentence)
        
        print(f"📚 Extracted {len(filtered_sentences)} valid sentences from CSV\n")
        return filtered_sentences, df
        
    except Exception as e:
        print(f"❌ Error reading CSV: {e}")
        return [], None

def predict_entities(text, model, tokenizer, device, id2label):
    """Test the model with new text"""
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        return_offsets_mapping=True,
        max_length=512
    )
    
    # Move input tensors to the same device as model
    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)
    offset_mapping = inputs["offset_mapping"][0].tolist()
    
    model.eval()
    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        predictions = torch.argmax(outputs.logits, dim=-1)
    
    # Move predictions back to CPU for processing
    predictions = predictions.cpu()
    input_ids_cpu = input_ids.cpu()
    
    tokens = tokenizer.convert_ids_to_tokens(input_ids_cpu[0])
    predicted_labels = [id2label[pred.item()] for pred in predictions[0]]
    
    entities = []
    current_entity = None
    
    for idx, (token, label, (start, end)) in enumerate(zip(tokens, predicted_labels, offset_mapping)):
        # Skip special tokens
        if token in tokenizer.all_special_tokens:
            continue
            
        if label.startswith("B-"):
            if current_entity:
                entities.append(current_entity)
            current_entity = {
                "text": text[start:end],
                "label": label[2:],
                "start": start,
                "end": end
            }
        elif label.startswith("I-") and current_entity and label[2:] == current_entity["label"]:
            current_entity["end"] = end
            current_entity["text"] = text[current_entity["start"]:current_entity["end"]]
        else:
            if current_entity:
                entities.append(current_entity)
                current_entity = None
    
    if current_entity:
        entities.append(current_entity)
    
    return entities

# Load sentences from CSV
print(f"📄 Reading CSV from: {csv_file_path}")
sentences, original_df = load_sentences_from_csv(csv_file_path, sentence_column='sentence')

if not sentences:
    print("❌ No sentences found. Please check your CSV file and column name.")
    exit()

# Process each sentence and collect results
results = []
all_output_data = []

print("🧪 Processing sentences and extracting entities...\n")
print("="*80)

for idx, sentence in enumerate(sentences):
    if not sentence or sentence.strip() == "":
        continue
    
    # Predict entities
    entities = predict_entities(sentence, model, tokenizer, device, id2label)
    
    # Display results for this sentence
    print(f"\n📄 Sentence {idx + 1}:")
    print(f"📝 Text: {sentence}")
    
    if entities:
        print("🏷️  Detected Entities:")
        for entity in entities:
            print(f"    • {entity['text']} → {entity['label']} (positions: {entity['start']}-{entity['end']})")
            
            # Collect data for DataFrame
            all_output_data.append({
                "Sentence_ID": idx + 1,
                "Sentence": sentence,
                "Entity": entity['text'],
                "Entity_Type": entity['label'],
                "Start_Position": entity['start'],
                "End_Position": entity['end']
            })
    else:
        print("    ❌ No entities detected")
        all_output_data.append({
            "Sentence_ID": idx + 1,
            "Sentence": sentence,
            "Entity": None,
            "Entity_Type": None,
            "Start_Position": None,
            "End_Position": None
        })
    
    print("-"*80)
    
    # Store result
    results.append({
        "sentence_id": idx + 1,
        "sentence": sentence,
        "entities": entities
    })

# Create DataFrame with results
df_results = pd.DataFrame(all_output_data)

# Summary statistics
print("\n📈 SUMMARY STATISTICS:")
print(f"Total sentences processed: {len(results)}")
total_entities = sum(len(r['entities']) for r in results)
print(f"Total entities detected: {total_entities}")

# Count entities by type
entity_counts = {}
for result in results:
    for entity in result['entities']:
        entity_type = entity['label']
        entity_counts[entity_type] = entity_counts.get(entity_type, 0) + 1

print("\nEntity counts by type:")
for entity_type, count in sorted(entity_counts.items()):
    print(f"  • {entity_type}: {count}")

# Display DataFrame
print("\n📊 Results DataFrame:")
display(df_results)

# Save results
output_filename = 'entity_extraction_results.csv'
df_results.to_csv(output_filename, index=False)
print(f"\n💾 Results saved to {output_filename}")

# Optional: Also save a summary
summary_df = pd.DataFrame([
    {"Metric": "Total Sentences", "Value": len(results)},
    {"Metric": "Total Entities", "Value": total_entities},
    {"Metric": "Sentences with Entities", "Value": len([r for r in results if r['entities']])},
    {"Metric": "Sentences without Entities", "Value": len([r for r in results if not r['entities']])}
])

for entity_type, count in entity_counts.items():
    summary_df = pd.concat([summary_df, pd.DataFrame([{"Metric": f"Entities: {entity_type}", "Value": count}])], ignore_index=True)

summary_df.to_csv('extraction_summary.csv', index=False)
print(f"📈 Summary saved to extraction_summary.csv")

Using device: cuda
✅ All required variables are available
Model device: cuda:0
Device variable: cuda
📄 Reading CSV from: lulc_relations_EVALUATION_csv  - Roberto .csv
📄 CSV loaded successfully!
📊 Shape: (20, 2)
📋 Columns: ['sentenceID', 'sentence']
📚 Extracted 20 valid sentences from CSV

🧪 Processing sentences and extracting entities...

================================================================================

📄 Sentence 1:
📝 Text: After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was often considered as irreversible desertification and large parts of the Sahel were designated as degraded land (e.g
🏷️  Detected Entities:
    • the 1970s and 1980s → DATE (positions: 22-41)
    • loss → CHANGE (positions: 56-60)
    • desertification → PROCESS (positions: 124-139)
--------------------------------------------------------------------------------

📄 Sentence 2:
📝 Text: The forests of West and Central Africa probably originally covered a combined area of about 3 million km 2
🏷️  Detected Entities:
    • forests → LULC (positions: 4-11)
    • West → LOC (positions: 15-19)
    • Central Africa → LOC (positions: 24-38)
    • area of about 3 million km → SURFACE_UNIT (positions: 78-104)
    • 2 → CARDINAL (positions: 105-106)
--------------------------------------------------------------------------------

📄 Sentence 3:
📝 Text: Land use change in the study site, p: ref: 2a, 2b, From 1996 to 2017, the area covered by cropped fields, C, has increased from 40% to 51.3% over the study site area, and from 47% to 64% of the arable lands in the study site due to the loss fallows
🏷️  Detected Entities:
    • change → CHANGE (positions: 9-15)
    • 2 → CARDINAL (positions: 43-44)
    • 1996 to 2017 → DATE (positions: 56-68)
    • increased → CHANGE (positions: 113-122)
    • 40% to → PERCENT (positions: 128-134)
    • 51.3% → PERCENT (positions: 135-140)
    • 47% to 64% → PERCENT (positions: 176-186)
    • loss → CHANGE (positions: 236-240)
    • fallows → LULC (positions: 241-248)
--------------------------------------------------------------------------------

📄 Sentence 4:
📝 Text: Agriculture in this region has been dominated over the past three decades by cotton production
🏷️  Detected Entities:
    • Agriculture → LULC (positions: 0-11)
    • the past three decades → DATE (positions: 51-73)
--------------------------------------------------------------------------------

📄 Sentence 5:
📝 Text: Forest land was decreased nearly by half in 2002 compared to its coverage in 1984, while the size of the gallery forest did not change much
🏷️  Detected Entities:
    • Forest → LULC (positions: 0-6)
    • decreased → CHANGE (positions: 16-25)
    • half → CARDINAL (positions: 36-40)
    • 2002 → DATE (positions: 44-48)
    • 1984 → DATE (positions: 77-81)
    • forest → LULC (positions: 113-119)
    • change → CHANGE (positions: 128-134)
--------------------------------------------------------------------------------

📄 Sentence 6:
📝 Text: About 26 and 31% of the total area of natural vegetation (forest, woodland and tree savanna) will be converted to farmland and degraded savanna by 2050 if we assume the dynamics recorded from 1975 to 1990 and 1990-2010, respectively
🏷️  Detected Entities:
    • About 26 → CARDINAL (positions: 0-8)
    • 31% → PERCENT (positions: 13-16)
    • forest → LULC (positions: 58-64)
    • tree → LULC (positions: 79-83)
    • savanna → LULC (positions: 84-91)
    • converted → CHANGE (positions: 101-110)
    • savanna → LULC (positions: 136-143)
    • 2050 → DATE (positions: 147-151)
    • 1975 to → DATE (positions: 192-199)
    • 1990 → DATE (positions: 200-204)
    • 1990-2010 → COORDINATES (positions: 209-218)
--------------------------------------------------------------------------------

📄 Sentence 7:
📝 Text: Assuming the dynamics recorded in the second period , the amounts of land covered by forest, woodland and tree savanna will decrease by 5, 9 and 17% of their cover in 1990, respectively, while the amount of degraded savanna and farmland will increase by 9 and 22% of the total area, respectively
🏷️  Detected Entities:
    • forest → LULC (positions: 85-91)
    • tree → LULC (positions: 106-110)
    • savanna → LULC (positions: 111-118)
    • decrease → CHANGE (positions: 124-132)
    • 5, 9 → COORDINATES (positions: 136-140)
    • 17% → PERCENT (positions: 145-148)
    • 1990 → DATE (positions: 167-171)
    • savanna → LULC (positions: 216-223)
    • increase → CHANGE (positions: 242-250)
    • 9 → CARDINAL (positions: 254-255)
    • 22% → PERCENT (positions: 260-263)
--------------------------------------------------------------------------------

📄 Sentence 8:
📝 Text: Conversely the decrease in the herbaceous standing crop, due to the shortening of the fallow period, the extension of cultivated and cleared fields, the grazing by cattle, and more generally the increment in landscape discontinuities limit the spread of fire and the size of burnt areas
🏷️  Detected Entities:
    • decrease → CHANGE (positions: 15-23)
    • crop → LULC (positions: 51-55)
    • fallow → LULC (positions: 86-92)
    • burnt areas → LULC (positions: 275-286)
--------------------------------------------------------------------------------

📄 Sentence 9:
📝 Text: describes Rwandan agriculture as caught in a "low investment trap"; less than 10% of cropland is irrigated, while tractors, bank credit and government aid are all scarce
🏷️  Detected Entities:
    • Rwandan → LOC (positions: 10-17)
    • agriculture → LULC (positions: 18-29)
    • less than 10% → PERCENT (positions: 68-81)
    • cropland → LULC (positions: 85-93)
--------------------------------------------------------------------------------

📄 Sentence 10:
📝 Text: Due to the weeding practice, bare soil dominates in cropped fields in the early growing season while herbaceous vegetation continues to grow in fallows and rangelands
🏷️  Detected Entities:
    • bare soil → LULC (positions: 29-38)
    • cropped → LULC (positions: 52-59)
    • the early → DATE (positions: 70-79)
    • growing → CHANGE (positions: 80-87)
    • herbaceous vegetation → LULC (positions: 101-122)
    • grow → CHANGE (positions: 136-140)
    • fallows → LULC (positions: 144-151)
--------------------------------------------------------------------------------

📄 Sentence 11:
📝 Text: In 1986, the grazing land had much higher proportion of the total regional area than other land use types while the size of croplands was substantially high after 16 years (Table )
🏷️  Detected Entities:
    • 1986 → DATE (positions: 3-7)
    • croplands → LULC (positions: 124-133)
    • 16 years → DATE (positions: 163-171)
--------------------------------------------------------------------------------

📄 Sentence 12:
📝 Text: In 1990, woodland and tree savanna were still the dominant land cover types
🏷️  Detected Entities:
    • 1990 → DATE (positions: 3-7)
    • tree → LULC (positions: 22-26)
    • savanna → LULC (positions: 27-34)
--------------------------------------------------------------------------------

📄 Sentence 13:
📝 Text: In fact, some NTFP-providing trees, such as the baobab (Adansonia digitata) and the shea tree (Vitellaria paradoxa), are protected by farmers during the agricultural cycle of cultivation and fallows and are therefore still well preserved
🏷️  Detected Entities:
    • trees → LULC (positions: 29-34)
    • tree → LULC (positions: 89-93)
    • Vitellaria → LOC (positions: 95-105)
    • cultivation → PROCESS (positions: 175-186)
    • fallows → LULC (positions: 191-198)
--------------------------------------------------------------------------------

📄 Sentence 14:
📝 Text: In rangelands, the main cause of woody vegetation decrease is the increasing pressure on wood resources to satisfy the demand for fuel and construction wood, not only from the local rural population, but also from the rapidly growing urban population of Niamey only 80 km away
🏷️  Detected Entities:
    • cause → CHANGE (positions: 24-29)
    • decrease → CHANGE (positions: 50-58)
    • increasing → CHANGE (positions: 66-76)
    • growing → CHANGE (positions: 226-233)
    • urban → LULC (positions: 234-239)
    • 80 km → SURFACE_UNIT (positions: 266-271)
--------------------------------------------------------------------------------

📄 Sentence 15:
📝 Text: In Saloum Senegal, with the increase of cultivated land and shortening of fallow cycles, soils have become less fertile close to the villages, although fallow land away from the settlement gained in size, mainly due to out-migration
🏷️  Detected Entities:
    • Saloum Senegal → LOC (positions: 3-17)
    • increase → CHANGE (positions: 28-36)
    • fallow → LULC (positions: 74-80)
    • fallow → LULC (positions: 152-158)
    • gained → CHANGE (positions: 189-195)
--------------------------------------------------------------------------------

📄 Sentence 16:
📝 Text: Irrigation from rivers is regarded as minor driver of LULCC
🏷️  Detected Entities:
    • driver → CHANGE (positions: 44-50)
--------------------------------------------------------------------------------

📄 Sentence 17:
📝 Text: On the one hand, tree growth and agroforestry on fields have led to an increase of woody cover in proximity to the village
🏷️  Detected Entities:
    • tree → LULC (positions: 17-21)
    • growth → CHANGE (positions: 22-28)
    • agroforestry → LULC (positions: 33-45)
    • increase → CHANGE (positions: 71-79)
--------------------------------------------------------------------------------

📄 Sentence 18:
📝 Text: Rangelands are grazed year-round under communal access but grazing also extends to fallows, year-round or only in the dry season depending on accessibility, and to cropped fields after the crop harvest
🏷️  Detected Entities:
    • year-round → DATE (positions: 22-32)
    • fallows → LULC (positions: 83-90)
    • year-round → DATE (positions: 92-102)
    • the dry season → DATE (positions: 114-128)
    • crop → LULC (positions: 189-193)
--------------------------------------------------------------------------------

📄 Sentence 19:
📝 Text: Ratios of fallow to cultivated area are 0.8 in Woure, where the bushfallow system is "already defunct," 1.6 in Silgey and Kolbila, where bush-fallow "would lead to a steady decline in fertility," 2 in Koho, where bush-fallow is "marginal," and 5 in Sayero, where available land is still "more than adequate."
🏷️  Detected Entities:
    • fallow → LULC (positions: 10-16)
    • 0.8 → CARDINAL (positions: 40-43)
    • 1.6 → CARDINAL (positions: 104-107)
    • Silgey → LOC (positions: 111-117)
    • Kolbila → LOC (positions: 122-129)
    • fallow → LULC (positions: 142-148)
    • decline → CHANGE (positions: 173-180)
    • 2 → CARDINAL (positions: 196-197)
    • Koho → LOC (positions: 201-205)
    • fallow → LULC (positions: 218-224)
    • 5 → CARDINAL (positions: 244-245)
    • Sayero → LOC (positions: 249-255)
--------------------------------------------------------------------------------

📄 Sentence 20:
📝 Text: Regular cultivation keeps the soil penetrable and farmers are aware of the benefits of trees in their fields
🏷️  Detected Entities:
    • cultivation → PROCESS (positions: 8-19)
    • trees → LULC (positions: 87-92)
--------------------------------------------------------------------------------

📈 SUMMARY STATISTICS:
Total sentences processed: 20
Total entities detected: 109

Entity counts by type:
  • CARDINAL: 9
  • CHANGE: 22
  • COORDINATES: 2
  • DATE: 16
  • LOC: 9
  • LULC: 39
  • PERCENT: 7
  • PROCESS: 3
  • SURFACE_UNIT: 2

📊 Results DataFrame:

,Sentence_ID,Sentence,Entity,Entity_Type,Start_Position,End_Position
0,1,"After the droughts in the 1970s and 1980s, the...",the 1970s and 1980s,DATE,22,41
1,1,"After the droughts in the 1970s and 1980s, the...",loss,CHANGE,56,60
2,1,"After the droughts in the 1970s and 1980s, the...",desertification,PROCESS,124,139
3,2,The forests of West and Central Africa probabl...,forests,LULC,4,11
4,2,The forests of West and Central Africa probabl...,West,LOC,15,19
...,...,...,...,...,...,...
104,19,Ratios of fallow to cultivated area are 0.8 in...,fallow,LULC,218,224
105,19,Ratios of fallow to cultivated area are 0.8 in...,5,CARDINAL,244,245
106,19,Ratios of fallow to cultivated area are 0.8 in...,Sayero,LOC,249,255
107,20,Regular cultivation keeps the soil penetrable ...,cultivation,PROCESS,8,19
108,20,Regular cultivation keeps the soil penetrable ...,trees,LULC,87,92

💾 Results saved to entity_extraction_results.csv
📈 Summary saved to extraction_summary.csv

In [75]:
def analyze_sentence_lengths(data, tokenizer):
    """Check how many sentences exceed the token limit"""
    print("🔍 ANALYZING SENTENCE LENGTHS...")
    
    short_sentences = 0
    medium_sentences = 0
    long_sentences = 0
    very_long_sentences = 0
    
    truncated_entities = 0
    total_entities = 0
    
    for item in data:
        sentence = item['original_sentence']
        entities = item['entities']
        
        # Tokenize to count tokens
        tokens = tokenizer.tokenize(sentence)
        token_count = len(tokens)
        
        total_entities += len(entities)
        
        # Count by length
        if token_count <= 128:
            short_sentences += 1
        elif token_count <= 256:
            medium_sentences += 1
        elif token_count <= 512:
            long_sentences += 1
        else:
            very_long_sentences += 1
            
            # Check for truncated entities
            encoding = tokenizer(sentence, truncation=True, max_length=512, return_offsets_mapping=True)
            last_char = encoding['offset_mapping'][-1][1] if encoding['offset_mapping'] else 0
            
            for entity in entities:
                if entity['start_char'] >= last_char:
                    truncated_entities += 1
    
    total_sentences = len(data)
    
    print(f"\n📊 SENTENCE LENGTH DISTRIBUTION:")
    print(f"  Short (≤128 tokens): {short_sentences} ({short_sentences/total_sentences*100:.1f}%)")
    print(f"  Medium (129-256 tokens): {medium_sentences} ({medium_sentences/total_sentences*100:.1f}%)")
    print(f"  Long (257-512 tokens): {long_sentences} ({long_sentences/total_sentences*100:.1f}%)")
    print(f"  Very Long (>512 tokens): {very_long_sentences} ({very_long_sentences/total_sentences*100:.1f}%)")
    
    print(f"\n⚠️ TRUNCATION IMPACT:")
    print(f"  Sentences that get truncated: {very_long_sentences}")
    print(f"  Entities lost due to truncation: {truncated_entities}")
    print(f"  Entity loss rate: {truncated_entities/total_entities*100:.1f}%")
    
    return {
        'very_long_count': very_long_sentences,
        'truncated_entities': truncated_entities,
        'total_entities': total_entities
    }

# Test your data
length_analysis = analyze_sentence_lengths(fixed_raw_data, tokenizer)

Token indices sequence length is longer than the specified maximum sequence length for this model (710 > 512). Running this sequence through the model will result in indexing errors

🔍 ANALYZING SENTENCE LENGTHS...

📊 SENTENCE LENGTH DISTRIBUTION:
  Short (≤128 tokens): 14229 (98.0%)
  Medium (129-256 tokens): 249 (1.7%)
  Long (257-512 tokens): 35 (0.2%)
  Very Long (>512 tokens): 9 (0.1%)

⚠️ TRUNCATION IMPACT:
  Sentences that get truncated: 9
  Entities lost due to truncation: 554
  Entity loss rate: 1.5%

In [16]:
# First, make sure tqdm is installed
!pip install tqdm -q

from tqdm import tqdm

def extract_all_lulc_terms(texts, model_path="./final_ner_model"):
    """
    Extract all unique LULC terms from a list of texts.
    This gives you the comprehensive list you requested.
    """
    all_lulc_terms = []
    
    # Add progress bar for processing texts
    print("🔄 Extracting entities from texts...")
    for text in tqdm(texts, desc="Processing sentences", unit="sentence"):
        entities = extract_entities(text, model_path)
        lulc_entities = [ent['text'].lower() for ent in entities if ent['label'] == 'LULC']
        all_lulc_terms.extend(lulc_entities)
    
    # Get unique terms
    unique_lulc_terms = sorted(list(set(all_lulc_terms)))
    return unique_lulc_terms

# Extract LULC terms from your original data
all_texts = [item['original_sentence'] for item in fixed_raw_data]
print(f"📊 Total sentences to process: {len(all_texts)}")

unique_lulc_terms = extract_all_lulc_terms(all_texts)

print(f"\n✅ Found {len(unique_lulc_terms)} unique LULC terms in your data:\n")

# Show first 20 terms
print("First 20 LULC terms:")
for i, term in enumerate(unique_lulc_terms[:20], 1):
    print(f"  {i}. {term}")

if len(unique_lulc_terms) > 20:
    print(f"  ... and {len(unique_lulc_terms) - 20} more terms")

# Save to file
with open('unique_lulc_terms.json', 'w') as f:
    json.dump(unique_lulc_terms, f, indent=2)
print(f"\n💾 Saved all {len(unique_lulc_terms)} terms to 'unique_lulc_terms.json'")

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

📊 Total sentences to process: 14522
🔄 Extracting entities from texts...

Processing sentences: 100%|██████████████████████████████████████████████████████████████| 14522/14522 [56:45<00:00,  4.26sentence/s]

✅ Found 111 unique LULC terms in your data:

First 20 LULC terms:
  1. agriculture
  2. agroforestry
  3. annual crops
  4. bare soil
  5. bare soils
  6. barley
  7. beans
  8. build-up area
  9. built up area
  10. built up areas
  11. built-up area
  12. built-up areas
  13. burned area
  14. burnt area
  15. burnt areas
  16. c
  17. cabbage
  18. cashew
  19. cereal
  20. cities
  ... and 91 more terms

💾 Saved all 111 terms to 'unique_lulc_terms.json'

In [ ]:
def extract_entities(text, model_path="./final_ner_model"):
    """
    Extract entities from new text using the trained model.
    This function shows how to use your model in practice.
    """
    # Load model and tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForTokenClassification.from_pretrained(model_path)
    model.eval()
    
    # Tokenize input
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512,
        return_offsets_mapping=True,
        padding=True
    )
    
    # Get predictions
    with torch.no_grad():
        outputs = model(**{k: v for k, v in inputs.items() if k != 'offset_mapping'})
        predictions = torch.argmax(outputs.logits, dim=-1)
    
    # Convert predictions to labels
    tokens = tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])
    labels = [model.config.id2label[pred.item()] for pred in predictions[0]]
    offset_mapping = inputs['offset_mapping'][0]
    
    # Extract entities
    entities = []
    current_entity = None
    
    for idx, (token, label, offset) in enumerate(zip(tokens, labels, offset_mapping)):
        if token in tokenizer.all_special_tokens:
            continue
            
        if label.startswith('B-'):
            # Start of new entity
            if current_entity:
                entities.append(current_entity)
            current_entity = {
                'text': tokenizer.convert_tokens_to_string([token]),
                'label': label[2:],
                'start': offset[0].item(),
                'end': offset[1].item(),
                'tokens': [token]
            }
        elif label.startswith('I-') and current_entity and label[2:] == current_entity['label']:
            # Continuation of current entity
            current_entity['tokens'].append(token)
            current_entity['end'] = offset[1].item()
            current_entity['text'] = tokenizer.convert_tokens_to_string(current_entity['tokens'])
        else:
            # Not an entity
            if current_entity:
                entities.append(current_entity)
                current_entity = None
    
    if current_entity:
        entities.append(current_entity)
    
    # Clean up entity text
    for entity in entities:
        entity['text'] = entity['text'].strip()
        del entity['tokens']
    
    return entities

In [ ]:
# This cell demonstrates why the context-aware model is better

test_text = """
The metropolitan area experienced rapid growth. Build up areas expanded by 40% 
while agricultural zones decreased. The green belt around the city was converted 
to residential use. This urban development affected local ecosystems and build up area.
"""

print("Comparison: Context-Aware Model vs Simple Pattern Matching\n")
print(f"Test text: {test_text}\n")

# Extract with your new model
entities = extract_entities(test_text)

print("Context-Aware Model Results:")
lulc_found = [ent for ent in entities if ent['label'] == 'LULC']
for ent in lulc_found:
    print(f"  ✓ Found LULCPROCESS: '{ent['text']}'")

print(f"\nTotal LULC entities found: {len(lulc_found)}")

# Compare with LULC terms from your training data
print("\n📊 Comparison with training data LULC terms:")

# Get LULC terms that were in your original training data
training_lulc_terms = []
for item in raw_data:
    for entity in item['entities']:
        if entity['label'] == 'LULC':
            training_lulc_terms.append(entity['text'].lower())

training_lulc_set = set(training_lulc_terms)
found_lulc_set = set([ent['text'].lower() for ent in lulc_found])

new_terms = found_lulc_set - training_lulc_set
if new_terms:
    print(f"\n🆕 NEW LULC terms found (not in training data): {list(new_terms)}")
    print("This shows the model can generalize beyond exact training examples!")

In [6]:
import pandas as pd
import json
from transformers import pipeline

# Load your CSV file
print("📂 Loading CSV file...")
csv_file = 'annotated_corpus_for_dataverse.csv'  # Update with your file path
df = pd.read_csv(csv_file)

# Filter for rows where relevance_label is not 'zero'
print("🔍 Filtering data...")
filtered_df = df[df['relevance_label'] != 0].copy()
print(f"✅ Filtered to {len(filtered_df)} rows")

# Load your fixed model for entity extraction
ner_pipeline = pipeline(
    "ner",
    model="./final_ner_model",  # Update with your model path
    tokenizer="./final_ner_model"
)

# Function to clean entity output
def clean_entity_output(text, entities):
    """
    Converts wordpiece-based entities back to original text tokens.
    Removes special characters like 'Ġ' and aligns spans with original text.
    """
    cleaned_entities = []
    
    for entity in entities:
        # Get the actual text span from the original text
        start_char = entity['start']
        end_char = entity['end']
        entity_text = text[start_char:end_char]
        
        # Remove special token markers if present
        clean_text = entity_text.replace('Ġ', ' ').strip()
        
        cleaned_entities.append({
            'text': clean_text,
            'label': entity['entity'],
            'start_char': start_char,
            'end_char': end_char
        })
    
    return cleaned_entities

# Process each text_segment in the filtered DataFrame
results = []

print("\n📊 Processing and extracting entities from filtered sentences...")

for index, row in filtered_df.iterrows():
    article_id = row['id_segment']
    original_sentence = row['text_segment']
    print(f"\nProcessing ID: {article_id}")
    print(f"Text: {original_sentence[:100]}...")  # Show first 100 chars
    
    # Extract entities
    entities = ner_pipeline(original_sentence)
    
    # Clean the entity output
    cleaned_entities = clean_entity_output(original_sentence, entities)
    
    # Prepare the output structure
    output_entry = {
        "article_id": article_id,
        "original_sentence": original_sentence,
        "entities": []  # List to hold cleaned entities
    }
    
    # Add ALL entities to the output (including 'O' labels)
    for ent in cleaned_entities:
        entity_dict = {
            "text": ent['text'],
            "label": ent['label'],
            "start_char": ent['start_char'],
            "end_char": ent['end_char']
        }
        output_entry["entities"].append(entity_dict)
    
    results.append(output_entry)
    
    # Print ALL entities for verification
    print("Extracted entities:")
    for ent in output_entry['entities']:
        print(f"  - text: '{ent['text']}'")
        print(f"    label: {ent['label']}")
        print(f"    start_char: {ent['start_char']}")
        print(f"    end_char: {ent['end_char']}")

# Save results as JSON
output_json_file = 'model_extraction_results.json'
with open(output_json_file, 'w') as f:
    json.dump(results, f, indent=2)

print(f"\n✅ Processing complete. Results saved to '{output_json_file}' as JSON.")

# Optional: Print summary of all unique labels found
all_labels = set()
for result in results:
    for entity in result['entities']:
        all_labels.add(entity['label'])

print(f"\n📊 Summary - Unique labels found: {sorted(all_labels)}")

📂 Loading CSV file...
🔍 Filtering data...
✅ Filtered to 803 rows

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

📊 Processing and extracting entities from filtered sentences...

Processing ID: 1-s2.0-S0301479717300713-main_226b
Text: #text': '(Lambin et al., 2003)'}], '#text': 'With high confidence, rainfall variability is a driving...
Extracted entities:
  - text: '2003'
    label: B-DATE
    start_char: 25
    end_char: 29
  - text: 'driving'
    label: B-CHANGE
    start_char: 93
    end_char: 100

Processing ID: 1-s2.0-S0303243414001718-main_19b
Text: #text': 'After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was ...
Extracted entities:
  - text: 'the'
    label: B-DATE
    start_char: 31
    end_char: 34
  - text: '1970'
    label: I-DATE
    start_char: 35
    end_char: 39
  - text: 's'
    label: I-DATE
    start_char: 39
    end_char: 40
  - text: 'and'
    label: I-DATE
    start_char: 41
    end_char: 44
  - text: '1980'
    label: I-DATE
    start_char: 45
    end_char: 49
  - text: 's'
    label: I-DATE
    start_char: 49
    end_char: 50
  - text: 'loss'
    label: B-CHANGE
    start_char: 65
    end_char: 69

Processing ID: 1-s2.0-S030438781000043X-mainext_313b
Text: #text': 'Few investment opportunities are available to most Rwandan farmers...
Extracted entities:
  - text: 'Rw'
    label: B-LOC
    start_char: 60
    end_char: 62
  - text: 'andan'
    label: I-LOC
    start_char: 62
    end_char: 67

Processing ID: 1-s2.0-S095937809800003X-main_75b
Text: #text': 'Pastoral production has often existed in some sort of symbiotic interaction with the [agric...
Extracted entities:
  - text: 'ag'
    label: B-LULC
    start_char: 95
    end_char: 97
  - text: 'ric'
    label: I-LULC
    start_char: 97
    end_char: 100
  - text: 'ulture'
    label: I-LULC
    start_char: 100
    end_char: 106

Processing ID: 1-s2.0-S0006320709005400-main_16b
Text: #text': 'The forests of West and Central Africa probably originally covered a combined area of about...
Extracted entities:
  - text: 'forests'
    label: B-LULC
    start_char: 13
    end_char: 20
  - text: 'West'
    label: B-LOC
    start_char: 24
    end_char: 28
  - text: 'Central'
    label: B-LOC
    start_char: 33
    end_char: 40
  - text: 'Africa'
    label: I-LOC
    start_char: 41
    end_char: 47
  - text: 'area'
    label: B-SURFACE_UNIT
    start_char: 87
    end_char: 91
  - text: 'of'
    label: I-SURFACE_UNIT
    start_char: 92
    end_char: 94
  - text: 'about'
    label: I-SURFACE_UNIT
    start_char: 95
    end_char: 100
  - text: '3'
    label: I-SURFACE_UNIT
    start_char: 101
    end_char: 102
  - text: 'million'
    label: I-SURFACE_UNIT
    start_char: 103
    end_char: 110
  - text: 'km'
    label: I-SURFACE_UNIT
    start_char: 111
    end_char: 113
  - text: '2'
    label: B-CARDINAL
    start_char: 114
    end_char: 115

Processing ID: 1-s2.0-S095937809800003X-main_8
Text: (1993)'}], '#text': "An increase of land under [cultivation] can be in the form of either (a) cleari...
Extracted entities:
  - text: '1993'
    label: B-DATE
    start_char: 1
    end_char: 5
  - text: 'increase'
    label: B-CHANGE
    start_char: 24
    end_char: 32
  - text: 'cult'
    label: B-PROCESS
    start_char: 48
    end_char: 52
  - text: 'ivation'
    label: I-PROCESS
    start_char: 52
    end_char: 59
  - text: 'cult'
    label: B-PROCESS
    start_char: 200
    end_char: 204
  - text: 'ivation'
    label: I-PROCESS
    start_char: 204
    end_char: 211

Processing ID: 1-s2.0-S0304387816300670-main_75
Text: (2006), who estimate an increase in the national [urban] share of 0.45 percent with a reduction in n...
Extracted entities:
  - text: '2006'
    label: B-DATE
    start_char: 1
    end_char: 5
  - text: 'increase'
    label: B-CHANGE
    start_char: 24
    end_char: 32
  - text: 'urban'
    label: B-LULC
    start_char: 50
    end_char: 55
  - text: '0'
    label: B-PERCENT
    start_char: 66
    end_char: 67
  - text: '.'
    label: I-PERCENT
    start_char: 67
    end_char: 68
  - text: '45'
    label: I-PERCENT
    start_char: 68
    end_char: 70
  - text: 'percent'
    label: I-PERCENT
    start_char: 71
    end_char: 78
  - text: 'reduction'
    label: B-CHANGE
    start_char: 86
    end_char: 95
  - text: '1'
    label: B-PERCENT
    start_char: 120
    end_char: 121
  - text: 'percent'
    label: I-PERCENT
    start_char: 122
    end_char: 129

Processing ID: 1-s2.0-S0140196313000608-main_212
Text: (2011)'}], '#text': 'Perhaps most importantly, the meta-analysis exposes the surprisingly huge gap i...
Extracted entities:
  - text: '2011'
    label: B-DATE
    start_char: 1
    end_char: 5
  - text: 'crop'
    label: B-LULC
    start_char: 169
    end_char: 173
  - text: 'change'
    label: B-CHANGE
    start_char: 180
    end_char: 186
  - text: 'changes'
    label: B-CHANGE
    start_char: 327
    end_char: 334

Processing ID: 1-s2.0-S0140196322000143-main_121
Text: ).'}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': {'@n': '4.2.', '#text': '[Land use ]change...
Extracted entities:
  - text: '4'
    label: B-CARDINAL
    start_char: 66
    end_char: 67
  - text: '.'
    label: I-CARDINAL
    start_char: 67
    end_char: 68
  - text: '2'
    label: I-CARDINAL
    start_char: 68
    end_char: 69
  - text: 'change'
    label: B-CHANGE
    start_char: 94
    end_char: 100
  - text: '1996'
    label: B-DATE
    start_char: 266
    end_char: 270
  - text: 'to'
    label: I-DATE
    start_char: 271
    end_char: 273
  - text: '2017'
    label: I-DATE
    start_char: 274
    end_char: 278
  - text: 'increased'
    label: B-CHANGE
    start_char: 323
    end_char: 332
  - text: '40'
    label: B-PERCENT
    start_char: 338
    end_char: 340
  - text: '%'
    label: I-PERCENT
    start_char: 340
    end_char: 341
  - text: 'to'
    label: I-PERCENT
    start_char: 342
    end_char: 344
  - text: '51'
    label: I-PERCENT
    start_char: 345
    end_char: 347
  - text: '.'
    label: I-PERCENT
    start_char: 347
    end_char: 348
  - text: '3'
    label: I-PERCENT
    start_char: 348
    end_char: 349
  - text: '%'
    label: I-PERCENT
    start_char: 349
    end_char: 350
  - text: '47'
    label: B-PERCENT
    start_char: 386
    end_char: 388
  - text: '%'
    label: I-PERCENT
    start_char: 388
    end_char: 389
  - text: 'to'
    label: I-PERCENT
    start_char: 390
    end_char: 392
  - text: '64'
    label: B-PERCENT
    start_char: 393
    end_char: 395
  - text: '%'
    label: I-PERCENT
    start_char: 395
    end_char: 396
  - text: 'loss'
    label: B-CHANGE
    start_char: 446
    end_char: 450
  - text: 'fall'
    label: B-LULC
    start_char: 451
    end_char: 455
  - text: 'ows'
    label: I-LULC
    start_char: 455
    end_char: 458

Processing ID: 1-s2.0-S0140196322000143-main_146
Text: ).'}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': {'@n': '4.4.', '#text': 'Trends of woody v...
Extracted entities:
  - text: '4'
    label: B-CARDINAL
    start_char: 66
    end_char: 67
  - text: '.'
    label: I-CARDINAL
    start_char: 67
    end_char: 68
  - text: '4'
    label: I-CARDINAL
    start_char: 68
    end_char: 69
  - text: 'two'
    label: B-DATE
    start_char: 115
    end_char: 118
  - text: 'decades'
    label: I-DATE
    start_char: 119
    end_char: 126
  - text: 'decreases'
    label: B-CHANGE
    start_char: 362
    end_char: 371

Processing ID: 1-s2.0-S0264837715302131-main_119
Text: [Agriculture] in this region has been dominated over the past three decades by [cotton] production...
Extracted entities:
  - text: 'Ag'
    label: B-LULC
    start_char: 1
    end_char: 3
  - text: 'ric'
    label: I-LULC
    start_char: 3
    end_char: 6
  - text: 'ulture'
    label: I-LULC
    start_char: 6
    end_char: 12
  - text: 'the'
    label: B-DATE
    start_char: 53
    end_char: 56
  - text: 'past'
    label: I-DATE
    start_char: 57
    end_char: 61
  - text: 'three'
    label: I-DATE
    start_char: 62
    end_char: 67
  - text: 'decades'
    label: I-DATE
    start_char: 68
    end_char: 75
  - text: 'c'
    label: B-LULC
    start_char: 80
    end_char: 81
  - text: 'otton'
    label: I-LULC
    start_char: 81
    end_char: 86

Processing ID: 1-s2.0-S016788090800131X-main_76
Text: [Forest] land was decreased nearly by half in 2002 compared to its coverage in 1984, while the size ...
Extracted entities:
  - text: 'Forest'
    label: B-LULC
    start_char: 1
    end_char: 7
  - text: 'decreased'
    label: B-CHANGE
    start_char: 18
    end_char: 27
  - text: 'half'
    label: I-CARDINAL
    start_char: 38
    end_char: 42
  - text: '2002'
    label: B-DATE
    start_char: 46
    end_char: 50
  - text: '1984'
    label: B-DATE
    start_char: 79
    end_char: 83
  - text: 'forest'
    label: B-LULC
    start_char: 116
    end_char: 122
  - text: 'change'
    label: B-CHANGE
    start_char: 132
    end_char: 138

Processing ID: 1-s2.0-S0304387816300670-main_602
Text: 30 km rain catchment areas around [city]-lights.'}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', '@xml:...
Extracted entities:
  - text: 'km'
    label: I-SURFACE_UNIT
    start_char: 3
    end_char: 5
  - text: 'city'
    label: B-LULC
    start_char: 35
    end_char: 39

Processing ID: 1-s2.0-S0140196313000608-main_106
Text: A detailed screening of the texts allowed us to remove papers that were not associated with [crop] l...
Extracted entities:
  - text: 'crop'
    label: B-LULC
    start_char: 93
    end_char: 97
  - text: 'change'
    label: B-CHANGE
    start_char: 104
    end_char: 110
  - text: 'processes'
    label: B-PROCESS
    start_char: 111
    end_char: 120

Processing ID: 1-s2.0-S030438781000043X-mainext_313a
Text: A new [Land Use ]and Management Law enacted in 2005 moves away from state ownership and seeks to reg...
Extracted entities:
  - text: '2005'
    label: B-DATE
    start_char: 47
    end_char: 51
  - text: 'ag'
    label: B-LULC
    start_char: 195
    end_char: 197
  - text: 'ric'
    label: I-LULC
    start_char: 197
    end_char: 200
  - text: 'ulture'
    label: I-LULC
    start_char: 200
    end_char: 206
  - text: '1998'
    label: B-DATE
    start_char: 288
    end_char: 292
  - text: '1993'
    label: B-DATE
    start_char: 362
    end_char: 366
  - text: '2008'
    label: B-DATE
    start_char: 424
    end_char: 428

Processing ID: 1-s2.0-S0264837715302131-main_147
Text: About 26 and 31% of the total area of natural vegetation ([forest], woodland and tree [savanna]) wil...
Extracted entities:
  - text: '26'
    label: B-CARDINAL
    start_char: 6
    end_char: 8
  - text: '31'
    label: B-PERCENT
    start_char: 13
    end_char: 15
  - text: '%'
    label: I-PERCENT
    start_char: 15
    end_char: 16
  - text: 'forest'
    label: B-LULC
    start_char: 59
    end_char: 65
  - text: 'tree'
    label: B-LULC
    start_char: 81
    end_char: 85
  - text: 'sav'
    label: B-LULC
    start_char: 87
    end_char: 90
  - text: 'anna'
    label: I-LULC
    start_char: 90
    end_char: 94
  - text: 'converted'
    label: B-CHANGE
    start_char: 105
    end_char: 114
  - text: 'sav'
    label: B-LULC
    start_char: 141
    end_char: 144
  - text: 'anna'
    label: I-LULC
    start_char: 144
    end_char: 148
  - text: '2050'
    label: B-DATE
    start_char: 153
    end_char: 157
  - text: '1975'
    label: B-DATE
    start_char: 198
    end_char: 202
  - text: '1990'
    label: B-DATE
    start_char: 206
    end_char: 210
  - text: '1990'
    label: B-COORDINATES
    start_char: 215
    end_char: 219
  - text: '-'
    label: I-COORDINATES
    start_char: 219
    end_char: 220
  - text: '2010'
    label: I-COORDINATES
    start_char: 220
    end_char: 224

Processing ID: 1-s2.0-S0140196314000536-main_381
Text: Active degradation is rarely spotted within 10 years and events such as bush-fires, floods or freque...
Extracted entities:
  - text: '10'
    label: B-DATE
    start_char: 44
    end_char: 46
  - text: 'years'
    label: I-DATE
    start_char: 47
    end_char: 52
  - text: 'crop'
    label: B-LULC
    start_char: 104
    end_char: 108

Processing ID: 1-s2.0-S0006320709005400-main_198
Text: Although such schemes clearly have the potential to benefit biodiversity and the wider environment, ...
Extracted entities:
  - text: '4'
    label: B-CARDINAL
    start_char: 385
    end_char: 386
  - text: '.'
    label: I-CARDINAL
    start_char: 386
    end_char: 387
  - text: '3'
    label: I-CARDINAL
    start_char: 387
    end_char: 388
  - text: '1'
    label: B-CARDINAL
    start_char: 489
    end_char: 490
  - text: '2007'
    label: B-DATE
    start_char: 558
    end_char: 562
  - text: '2006'
    label: B-DATE
    start_char: 613
    end_char: 617
  - text: '2000'
    label: B-DATE
    start_char: 687
    end_char: 691
  - text: 'Z'
    label: B-LOC
    start_char: 743
    end_char: 744
  - text: 'hang'
    label: I-LOC
    start_char: 744
    end_char: 748
  - text: '2006'
    label: B-DATE
    start_char: 757
    end_char: 761
  - text: '2008'
    label: B-DATE
    start_char: 835
    end_char: 839
  - text: 'forest'
    label: B-LULC
    start_char: 869
    end_char: 875
  - text: 'West'
    label: B-LOC
    start_char: 885
    end_char: 889
  - text: 'Africa'
    label: I-LOC
    start_char: 890
    end_char: 896
  - text: 'decline'
    label: B-CHANGE
    start_char: 971
    end_char: 978
  - text: 'forest'
    label: B-LULC
    start_char: 983
    end_char: 989
  - text: 'loss'
    label: B-CHANGE
    start_char: 1001
    end_char: 1005
  - text: 'forest'
    label: B-LULC
    start_char: 1010
    end_char: 1016

Processing ID: 1-s2.0-S0167880913003502-main_147
Text: Another example, using a 7 year wheat-[corn] rotation in China (Table ; , showed that CT had 0.7 Mg ...
Extracted entities:
  - text: '7'
    label: B-DATE
    start_char: 25
    end_char: 26
  - text: 'year'
    label: I-DATE
    start_char: 27
    end_char: 31
  - text: 'corn'
    label: B-LULC
    start_char: 39
    end_char: 43
  - text: 'China'
    label: B-LOC
    start_char: 57
    end_char: 62
  - text: 'CT'
    label: B-LOC
    start_char: 86
    end_char: 88
  - text: '0'
    label: B-CARDINAL
    start_char: 93
    end_char: 94
  - text: '.'
    label: I-CARDINAL
    start_char: 94
    end_char: 95
  - text: '7'
    label: I-CARDINAL
    start_char: 95
    end_char: 96
  - text: 'CT'
    label: B-LOC
    start_char: 151
    end_char: 153
  - text: '0'
    label: B-CARDINAL
    start_char: 158
    end_char: 159
  - text: '.'
    label: I-CARDINAL
    start_char: 159
    end_char: 160
  - text: '6'
    label: I-CARDINAL
    start_char: 160
    end_char: 161
  - text: '1995'
    label: B-DATE
    start_char: 287
    end_char: 291
  - text: '2009'
    label: B-DATE
    start_char: 356
    end_char: 360
  - text: 'G'
    label: B-LOC
    start_char: 413
    end_char: 414
  - text: 'iff'
    label: I-LOC
    start_char: 414
    end_char: 417
  - text: 'ord'
    label: I-LOC
    start_char: 417
    end_char: 420
  - text: '2003'
    label: B-DATE
    start_char: 435
    end_char: 439
  - text: '2010'
    label: B-DATE
    start_char: 516
    end_char: 520
  - text: '2013'
    label: B-DATE
    start_char: 592
    end_char: 596

Processing ID: 1-s2.0-S0140196322000143-main_99
Text: Another variance analysis using GLM was conducted for the variable means of all recorded trees and [...
Extracted entities:
  - text: 'trees'
    label: B-LULC
    start_char: 89
    end_char: 94
  - text: 'shr'
    label: B-LULC
    start_char: 100
    end_char: 103
  - text: 'ubs'
    label: I-LULC
    start_char: 103
    end_char: 106
  - text: 'trees'
    label: B-LULC
    start_char: 181
    end_char: 186
  - text: 'shr'
    label: B-LULC
    start_char: 192
    end_char: 195
  - text: 'ubs'
    label: I-LULC
    start_char: 195
    end_char: 198

Processing ID: 1-s2.0-S003442571730041X-main_24
Text: As current classification schemes of the [land cover] class 'cropland' encompass fallowed fields in ...
Extracted entities:
  - text: 'cro'
    label: B-LULC
    start_char: 61
    end_char: 64
  - text: 'pl'
    label: I-LULC
    start_char: 64
    end_char: 66
  - text: 'and'
    label: I-LULC
    start_char: 66
    end_char: 69
  - text: 'fall'
    label: B-LULC
    start_char: 81
    end_char: 85
  - text: 'owed'
    label: I-LULC
    start_char: 85
    end_char: 89
  - text: 'impact'
    label: B-CHANGE
    start_char: 168
    end_char: 174
  - text: 'fall'
    label: B-LULC
    start_char: 179
    end_char: 183
  - text: 'ow'
    label: I-LULC
    start_char: 183
    end_char: 185
  - text: '2012'
    label: B-DATE
    start_char: 309
    end_char: 313
  - text: '2016'
    label: B-DATE
    start_char: 382
    end_char: 386
  - text: 'Al'
    label: B-LOC
    start_char: 438
    end_char: 440
  - text: 'c'
    label: I-LOC
    start_char: 440
    end_char: 441
  - text: 'ant'
    label: I-LOC
    start_char: 441
    end_char: 444
  - text: 'ara'
    label: I-LOC
    start_char: 444
    end_char: 447
  - text: '2012'
    label: B-DATE
    start_char: 456
    end_char: 460
  - text: '2016'
    label: B-DATE
    start_char: 509
    end_char: 513
  - text: '2015'
    label: B-DATE
    start_char: 580
    end_char: 584
  - text: 'Earth'
    label: B-LOC
    start_char: 609
    end_char: 614
  - text: 'fall'
    label: B-LULC
    start_char: 694
    end_char: 698
  - text: 'owed'
    label: I-LULC
    start_char: 698
    end_char: 702
  - text: 'fields'
    label: I-LULC
    start_char: 703
    end_char: 709
  - text: 'improve'
    label: B-CHANGE
    start_char: 725
    end_char: 732
  - text: 'drivers'
    label: B-CHANGE
    start_char: 773
    end_char: 780
  - text: 'changes'
    label: B-CHANGE
    start_char: 820
    end_char: 827
  - text: 'fall'
    label: B-LULC
    start_char: 871
    end_char: 875
  - text: 'ow'
    label: I-LULC
    start_char: 875
    end_char: 877
  - text: 'expansion'
    label: B-CHANGE
    start_char: 904
    end_char: 913

Processing ID: 1-s2.0-S0264837715302131-main_103
Text: Assuming the dynamics recorded in the second period , the amounts of land covered by [forest], woodl...
Extracted entities:
  - text: 'forest'
    label: B-LULC
    start_char: 86
    end_char: 92
  - text: 'tree'
    label: B-LULC
    start_char: 108
    end_char: 112
  - text: 'sav'
    label: B-LULC
    start_char: 114
    end_char: 117
  - text: 'anna'
    label: I-LULC
    start_char: 117
    end_char: 121
  - text: 'decrease'
    label: B-CHANGE
    start_char: 128
    end_char: 136
  - text: '5'
    label: B-COORDINATES
    start_char: 140
    end_char: 141
  - text: ','
    label: I-COORDINATES
    start_char: 141
    end_char: 142
  - text: '9'
    label: I-COORDINATES
    start_char: 143
    end_char: 144
  - text: '17'
    label: B-PERCENT
    start_char: 149
    end_char: 151
  - text: '%'
    label: I-PERCENT
    start_char: 151
    end_char: 152
  - text: '1990'
    label: B-DATE
    start_char: 171
    end_char: 175
  - text: 'sav'
    label: B-LULC
    start_char: 221
    end_char: 224
  - text: 'anna'
    label: I-LULC
    start_char: 224
    end_char: 228
  - text: 'increase'
    label: B-CHANGE
    start_char: 248
    end_char: 256
  - text: '9'
    label: B-CARDINAL
    start_char: 260
    end_char: 261
  - text: '22'
    label: B-PERCENT
    start_char: 266
    end_char: 268
  - text: '%'
    label: I-PERCENT
    start_char: 268
    end_char: 269

Processing ID: 1-s2.0-S003442571730041X-main_4
Text: At present, no studies have considered the importance of the different [seasonal] NDVI signals of cr...
Extracted entities:
  - text: 'fall'
    label: B-LULC
    start_char: 110
    end_char: 114
  - text: 'owed'
    label: I-LULC
    start_char: 114
    end_char: 118
  - text: 'cro'
    label: B-LULC
    start_char: 212
    end_char: 215
  - text: 'pl'
    label: I-LULC
    start_char: 215
    end_char: 217
  - text: 'and'
    label: I-LULC
    start_char: 217
    end_char: 220

Processing ID: 1-s2.0-S0169204617300270-main_139

In [ ]:
import pandas as pd
import json
from transformers import pipeline
import os
import xml.sax.saxutils

# Load your CSV file
print("📂 Loading CSV file...")
csv_file = 'annotated_corpus_for_dataverse.csv'  # Update with your file path
df = pd.read_csv(csv_file)

# Filter for rows where relevance_label is not 'zero' (optional)
print("🔍 Filtering data...")
filtered_df = df[df['relevance_label'] != 0].copy()
print(f"✅ Filtered to {len(filtered_df)} rows")

# Load your NER model
ner_pipeline = pipeline(
    "ner",
    model="./final_ner_model",  # Update with your model path
    tokenizer="./final_ner_model",
    aggregation_strategy="simple"  # Groups sub-word tokens
)

def create_label_studio_config(all_labels, output_dir):
    """Create Label Studio config XML file"""
    
    colors = [
        "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FECA57", 
        "#FF9FF3", "#A55EEA", "#54A0FF", "#5F27CD", "#00D2D3",
        "#FF9F43", "#10AC84", "#EE5A24", "#0098C7", "#8395A7"
    ]
    
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    config_path = os.path.join(output_dir, "ner_label_studio_config.xml")
    
    # Build entity labels
    entity_labels = ""
    for i, label in enumerate(sorted(all_labels)):
        color = colors[i % len(colors)]
        # Escape XML special characters
        safe_label = xml.sax.saxutils.escape(label)
        entity_labels += f'    <Label value="{safe_label}" background="{color}"/>\n'
    
    # Build complete XML config
    label_studio_config = f"""<View>
  <Text name="text" value="$text"/>
  <Labels name="label" toName="text">
{entity_labels}  </Labels>
</View>"""
    
    # Write the file
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(label_studio_config)
    
    print(f"✅ Label Studio config saved to: {config_path}")
    return config_path

# Process each text_segment
label_studio_data = []
all_unique_labels = set()
annotation_id_counter = 1

print("\n📊 Processing texts and extracting entities...")

for index, row in filtered_df.iterrows():
    text = row['text_segment']
    article_id = row['id_segment']
    
    print(f"\nProcessing ID: {article_id}")
    print(f"Text preview: {text[:100]}...")
    
    # Extract entities using your model
    entities = ner_pipeline(text)
    
    # Build result array for this text
    results = []
    entity_counter = 0
    
    for entity in entities:
        # Skip 'O' labels
        if entity.get('entity_group', entity.get('entity', '')).endswith('-O'):
            continue
        
        # Extract clean label (remove B-, I- prefixes)
        label = entity.get('entity_group', entity.get('entity', '')).replace('B-', '').replace('I-', '')
        
        # Add to unique labels set
        all_unique_labels.add(label)
        
        # Create entity result
        result = {
            "id": f"entity_{entity_counter}",
            "type": "labels",
            "value": {
                "start": entity['start'],
                "end": entity['end'],
                "text": text[entity['start']:entity['end']],
                "labels": [label]
            },
            "from_name": "label",
            "to_name": "text"
        }
        results.append(result)
        entity_counter += 1
    
    # Create the task in Label Studio format
    task = {
        "data": {
            "text": text,
            "article_id": article_id  # Keep original ID for reference
        }
    }
    
    # Add annotations only if entities were found
    if results:
        task["annotations"] = [{
            "id": annotation_id_counter,
            "result": results
        }]
        annotation_id_counter += 1
    
    label_studio_data.append(task)
    
    # Print extracted entities for verification
    if results:
        print(f"Found {len(results)} entities:")
        for result in results[:5]:  # Show first 5
            print(f"  - '{result['value']['text']}' → {result['value']['labels'][0]}")
        if len(results) > 5:
            print(f"  ... and {len(results) - 5} more")
    else:
        print("No entities found")

# Create output directory
output_dir = "label_studio_output"
os.makedirs(output_dir, exist_ok=True)

# Save as Label Studio JSON format
output_file = os.path.join(output_dir, 'label_studio_ner_tasks.json')
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(label_studio_data, f, indent=2, ensure_ascii=False)

# Generate Label Studio config file
if all_unique_labels:
    config_file = create_label_studio_config(all_unique_labels, output_dir)
else:
    print("⚠️ No labels found to generate config")

print(f"\n✅ Processing complete!")
print(f"📄 Results saved to: {output_file}")
print(f"📊 Total tasks: {len(label_studio_data)}")

# Print summary statistics
total_entities = sum(len(task.get('annotations', [{}])[0].get('result', [])) 
                    for task in label_studio_data if 'annotations' in task)
print(f"🏷️ Total entities extracted: {total_entities}")
print(f"🏷️ Unique labels found: {sorted(all_unique_labels)}")

print("\n📝 To import in Label Studio:")
print("1. Create a new project in Label Studio")
print(f"2. Go to Settings > Labeling Interface > Code")
print(f"3. Paste the content from: {output_dir}/ner_label_studio_config.xml")
print(f"4. Go to Import and upload: {output_file}")

# Show sample of output format
print("\n📋 Sample output format:")
if label_studio_data:
    print(json.dumps(label_studio_data[0], indent=2)[:500] + "...")

📂 Loading CSV file...
🔍 Filtering data...
✅ Filtered to 803 rows

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

📊 Processing texts and extracting entities...

Processing ID: 1-s2.0-S0301479717300713-main_226b
Text preview: #text': '(Lambin et al., 2003)'}], '#text': 'With high confidence, rainfall variability is a driving...
Found 2 entities:
  - '2003' → DATE
  - 'driving' → CHANGE

Processing ID: 1-s2.0-S0303243414001718-main_19b
Text preview: #text': 'After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was ...
Found 2 entities:
  - 'the 1970s and 1980s' → DATE
  - 'loss' → CHANGE

Processing ID: 1-s2.0-S030438781000043X-mainext_313b
Text preview: #text': 'Few investment opportunities are available to most Rwandan farmers...
Found 1 entities:
  - 'Rwandan' → LOC

Processing ID: 1-s2.0-S095937809800003X-main_75b
Text preview: #text': 'Pastoral production has often existed in some sort of symbiotic interaction with the [agric...
Found 1 entities:
  - 'agriculture' → LULC

Processing ID: 1-s2.0-S0006320709005400-main_16b
Text preview: #text': 'The forests of West and Central Africa probably originally covered a combined area of about...
Found 5 entities:
  - 'forests' → LULC
  - 'West' → LOC
  - 'Central Africa' → LOC
  - 'area of about 3 million km' → SURFACE_UNIT
  - '2' → CARDINAL

Processing ID: 1-s2.0-S095937809800003X-main_8
Text preview: (1993)'}], '#text': "An increase of land under [cultivation] can be in the form of either (a) cleari...
Found 4 entities:
  - '1993' → DATE
  - 'increase' → CHANGE
  - 'cultivation' → PROCESS
  - 'cultivation' → PROCESS

Processing ID: 1-s2.0-S0304387816300670-main_75
Text preview: (2006), who estimate an increase in the national [urban] share of 0.45 percent with a reduction in n...
Found 6 entities:
  - '2006' → DATE
  - 'increase' → CHANGE
  - 'urban' → LULC
  - '0.45 percent' → PERCENT
  - 'reduction' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S0140196313000608-main_212
Text preview: (2011)'}], '#text': 'Perhaps most importantly, the meta-analysis exposes the surprisingly huge gap i...
Found 4 entities:
  - '2011' → DATE
  - 'crop' → LULC
  - 'change' → CHANGE
  - 'changes' → CHANGE

Processing ID: 1-s2.0-S0140196322000143-main_121
Text preview: ).'}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': {'@n': '4.2.', '#text': '[Land use ]change...
Found 9 entities:
  - '4.2' → CARDINAL
  - 'change' → CHANGE
  - '1996 to 2017' → DATE
  - 'increased' → CHANGE
  - '40% to 51.3%' → PERCENT
  ... and 4 more

Processing ID: 1-s2.0-S0140196322000143-main_146
Text preview: ).'}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': {'@n': '4.4.', '#text': 'Trends of woody v...
Found 3 entities:
  - '4.4' → CARDINAL
  - 'two decades' → DATE
  - 'decreases' → CHANGE

Processing ID: 1-s2.0-S0264837715302131-main_119
Text preview: [Agriculture] in this region has been dominated over the past three decades by [cotton] production...
Found 3 entities:
  - 'Agriculture' → LULC
  - 'the past three decades' → DATE
  - 'cotton' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_76
Text preview: [Forest] land was decreased nearly by half in 2002 compared to its coverage in 1984, while the size ...
Found 7 entities:
  - 'Forest' → LULC
  - 'decreased' → CHANGE
  - 'half' → CARDINAL
  - '2002' → DATE
  - '1984' → DATE
  ... and 2 more

Processing ID: 1-s2.0-S0304387816300670-main_602
Text preview: 30 km rain catchment areas around [city]-lights.'}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', '@xml:...
Found 2 entities:
  - 'km' → SURFACE_UNIT
  - 'city' → LULC

Processing ID: 1-s2.0-S0140196313000608-main_106
Text preview: A detailed screening of the texts allowed us to remove papers that were not associated with [crop] l...
Found 3 entities:
  - 'crop' → LULC
  - 'change' → CHANGE
  - 'processes' → PROCESS

Processing ID: 1-s2.0-S030438781000043X-mainext_313a
Text preview: A new [Land Use ]and Management Law enacted in 2005 moves away from state ownership and seeks to reg...
Found 5 entities:
  - '2005' → DATE
  - 'agriculture' → LULC
  - '1998' → DATE
  - '1993' → DATE
  - '2008' → DATE

Processing ID: 1-s2.0-S0264837715302131-main_147
Text preview: About 26 and 31% of the total area of natural vegetation ([forest], woodland and tree [savanna]) wil...
Found 11 entities:
  - '26' → CARDINAL
  - '31%' → PERCENT
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  ... and 6 more

Processing ID: 1-s2.0-S0140196314000536-main_381
Text preview: Active degradation is rarely spotted within 10 years and events such as bush-fires, floods or freque...
Found 2 entities:
  - '10 years' → DATE
  - 'crop' → LULC

Processing ID: 1-s2.0-S0006320709005400-main_198
Text preview: Although such schemes clearly have the potential to benefit biodiversity and the wider environment, ...
Found 14 entities:
  - '4.3' → CARDINAL
  - '1' → CARDINAL
  - '2007' → DATE
  - '2006' → DATE
  - '2000' → DATE
  ... and 9 more

Processing ID: 1-s2.0-S0167880913003502-main_147
Text preview: Another example, using a 7 year wheat-[corn] rotation in China (Table ; , showed that CT had 0.7 Mg ...
Found 13 entities:
  - '7 year' → DATE
  - 'corn' → LULC
  - 'China' → LOC
  - 'CT' → LOC
  - '0.7' → CARDINAL
  ... and 8 more

Processing ID: 1-s2.0-S0140196322000143-main_99
Text preview: Another variance analysis using GLM was conducted for the variable means of all recorded trees and [...
Found 4 entities:
  - 'trees' → LULC
  - 'shrubs' → LULC
  - 'trees' → LULC
  - 'shrubs' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_24
Text preview: As current classification schemes of the [land cover] class 'cropland' encompass fallowed fields in ...
Found 17 entities:
  - 'cropland' → LULC
  - 'fallowed' → LULC
  - 'impact' → CHANGE
  - 'fallow' → LULC
  - '2012' → DATE
  ... and 12 more

Processing ID: 1-s2.0-S0264837715302131-main_103
Text preview: Assuming the dynamics recorded in the second period , the amounts of land covered by [forest], woodl...
Found 11 entities:
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  - 'decrease' → CHANGE
  - '5, 9' → COORDINATES
  ... and 6 more

Processing ID: 1-s2.0-S003442571730041X-main_4
Text preview: At present, no studies have considered the importance of the different [seasonal] NDVI signals of cr...
Found 2 entities:
  - 'fallowed' → LULC
  - 'cropland' → LULC

Processing ID: 1-s2.0-S0169204617300270-main_139
Text preview: Based on the consistency of the results of the three methods, we assigned confidence levels (Table a...
Found 4 entities:
  - 'three' → CARDINAL
  - '2002' → DATE
  - 'Urban' → LULC
  - 'urban' → LULC

Processing ID: 1-s2.0-S0168192311001122-main_97
Text preview: Based on this assumption, each of the 64 sub-basins was classified according to its average [fallow]...
Found 4 entities:
  - '64' → CARDINAL
  - 'fallow' → LULC
  - 'cropland' → LULC
  - 'three' → CARDINAL

Processing ID: 1-s2.0-S0140196310000893-main_63
Text preview: Between brackets: absolute contribution of fire type to respectively the first and second axis: [lan...
Found 1 entities:
  - '1' → CARDINAL

Processing ID: 1-s2.0-S0308521X12000157-main_281b
Text preview: Can institutional contexts be changed? Neither the outcomes nor the processes of change are predeter...
Found 3 entities:
  - 'changed' → CHANGE
  - 'processes' → PROCESS
  - 'of change' → CHANGE

Processing ID: 1-s2.0-S095937809800003X-main_52
Text preview: Climatic variations influence farmers' immediate as well as long-term choice of [cultivation] patter...
Found 1 entities:
  - 'cultivation' → PROCESS

Processing ID: 1-s2.0-S0140196310000893-main_115
Text preview: Conversely the decrease in the herbaceous standing [crop], due to the shortening of the [fallow] per...
Found 3 entities:
  - 'decrease' → CHANGE
  - 'crop' → LULC
  - 'fallow' → LULC

Processing ID: 1-s2.0-S0169204617300270-main_221
Text preview: Coping capacities were therefore assumed to be lower for the Bolgatanga area, which could lead to lo...
Found 11 entities:
  - 'Bolgatanga' → LOC
  - 'urban' → LULC
  - 'agriculture' → LULC
  - '3.2' → CARDINAL
  - 'Dri' → CHANGE
  ... and 6 more

Processing ID: 1-s2.0-S0264837715302131-main_61
Text preview: Cover loss refers to [land cover] that was subjected to a change with a concomitant loss in a regres...
Found 5 entities:
  - 'loss' → CHANGE
  - 'change' → CHANGE
  - 'loss' → CHANGE
  - 'forest' → LULC
  - 'savanna' → LULC

Processing ID: 1-s2.0-S0304387816300670-main_363
Text preview: Decreased moisture is then likely to decrease local [city] income...
Found 3 entities:
  - 'ased' → CHANGE
  - 'decrease' → CHANGE
  - 'city' → LULC

Processing ID: 1-s2.0-S0168192311001122-main_99
Text preview: Depending on the average [fallow]-cropland ratio, a sub-basin is classified into one of the seven cl...
Found 18 entities:
  - 'fallow' → LULC
  - 'cropland' → LULC
  - 'one' → CARDINAL
  - 'seven' → CARDINAL
  - 'fallow' → LULC
  ... and 13 more

Processing ID: 1-s2.0-S0168192311001122-main_64
Text preview: described three [land use] scenarios assuming increasing population density, but different reduction...
Found 4 entities:
  - 'three' → CARDINAL
  - 'increasing' → CHANGE
  - 'reduction' → CHANGE
  - 'growth' → CHANGE

Processing ID: 1-s2.0-S030438781000043X-mainext_317
Text preview: describes Rwandan [agriculture] as caught in a "low investment trap"; less than 10% of cropland is i...
Found 4 entities:
  - 'Rwandan' → LOC
  - 'agriculture' → LULC
  - 'less than 10%' → PERCENT
  - 'cropland' → LULC

Processing ID: 1-s2.0-S0140196313000608-main_62
Text preview: Despite the often mentioned "cash [crop] revolution", the so-called "Peanut Basin" of Senegal and th...
Found 4 entities:
  - 'crop' → LULC
  - 'Senegal' → LOC
  - 'cotton' → LULC
  - 'Mali' → LOC

Processing ID: 1-s2.0-S0140196313000608-main_121
Text preview: Drivers of change in [crop] land included demographic, economic, agro-technical, institutional, and ...
Found 6 entities:
  - 'vers' → CHANGE
  - 'of change' → CHANGE
  - 'crop' → LULC
  - 'drivers' → CHANGE
  - '2' → CARDINAL
  ... and 1 more

Processing ID: 1-s2.0-S0140196313000608-main_121
Text preview: Drivers of change in [crop] land.', 'graphic': {'@coords': '8,108.00,66.73,369.83,358.41', '@type': ...
Found 4 entities:
  - 'vers' → CHANGE
  - 'of change' → CHANGE
  - 'crop' → LULC
  - '8,108.00,66.73,369.83,358.41' → COORDINATES

Processing ID: 1-s2.0-S0301479717300713-main_45
Text preview: Due to the low capacities for food provision, especially in the dry season, up to 100,000 people (in...
Found 9 entities:
  - 'the dry season' → DATE
  - 'up to 100,000' → CARDINAL
  - '2000' → DATE
  - 'Ghana' → LOC
  - 'the dry season' → DATE
  ... and 4 more

Processing ID: 1-s2.0-S003442571730041X-main_41
Text preview: Due to the weeding practice, [bare soil] dominates in cropped fields in the early growing season whi...
Found 4 entities:
  - 'bare soil' → LULC
  - 'early growing season' → DATE
  - 'grow' → CHANGE
  - 'fallows' → LULC

Processing ID: 1-s2.0-S0301479717300713-main_978
Text preview: Error 0.3217 À0.000001553 1.97 À0.4507 1Q Estimate 6.76E-01 À1.18E-05'}]}, {'cell': ['À0.4079', 'À0....
Found 22 entities:
  - '0.3217' → CARDINAL
  - '1.97' → CARDINAL
  - '76' → CARDINAL
  - '3' → CARDINAL
  - '0.0706' → CARDINAL
  ... and 17 more

Processing ID: 1-s2.0-S0301479717300713-main_23
Text preview: Examples for the eminent relevance of such climatic parameters for [LULCC] in marginalised rural reg...
Found 7 entities:
  - 'the Global South' → LOC
  - 'Ghana' → LOC
  - 'West Africa' → LOC
  - '2016' → DATE
  - '2010' → DATE
  ... and 2 more

Processing ID: 1-s2.0-S030438781000043X-mainext_780
Text preview: Fenske / Journal of Development Economics 95 (2011) 137-156'}, {'@xmlns': 'http://www.tei-c.org/ns/1...
Found 5 entities:
  - '2011)' → COORDINATES
  - '137-156' → COORDINATES
  - '3' → CARDINAL
  - 'cultivation' → PROCESS
  - 'crop' → LULC

Processing ID: 1-s2.0-S0167880913003502-main_111
Text preview: For example, materials with high C:N, characteristic of cereal [crop] residues, reduce the available...
Found 14 entities:
  - 'cereal' → LULC
  - 'crop' → LULC
  - 'crop' → LULC
  - 'crops' → LULC
  - 'increase' → CHANGE
  ... and 9 more

Processing ID: 1-s2.0-S0169204617300270-main_92
Text preview: For example, Poku-Boansi & Amoako (2015) compared spatial inequalities of cities within Ghana, inclu...
Found 26 entities:
  - '2015' → DATE
  - 'cities' → LULC
  - 'Ghana' → LOC
  - 'Takoradi' → LOC
  - 'Bolgatanga' → LOC
  ... and 21 more

Processing ID: 1-s2.0-S0169204617300270-main_281
Text preview: For the Bolgatanga area, PPPs were not mentioned by the experts and were proposed by literature only...
Found 3 entities:
  - 'Bol' → LOC
  - 'anga' → LOC
  - 'city' → LULC

Processing ID: 1-s2.0-S0301479717300713-main_223
Text preview: From the expert interviews, we learned that migration is a driver and a consequence of [LULCC] and p...
Found 2 entities:
  - 'driver' → CHANGE
  - 'driver' → CHANGE

Processing ID: 1-s2.0-S0169204617300270-main_321
Text preview: Furthermore, by developing datasets with the requisite data structures, we could use additional land...
Found 5 entities:
  - 'urban' → LULC
  - '2015' → DATE
  - 'Edenhofe' → LOC
  - '2011' → DATE
  - '2015' → DATE

Processing ID: 1-s2.0-S0301479717300713-main_912
Text preview: He has no power, beyond his salary -that\'s it … P5 (no driver): If government earmark this land as ...
Found 2 entities:
  - 'driver' → CHANGE
  - 'forest' → LULC

Processing ID: 1-s2.0-S0140196310000893-main_39
Text preview: However agricultural fires should be distinguished from the other fires that are wildland fires and ...
Found 2 entities:
  - 'grass' → LULC
  - 'savanna' → LULC

Processing ID: 1-s2.0-S0304387816300670-main_219
Text preview: However these factors ( ) X ij could also affect the impact of climate changes on [urban] share grow...
Found 4 entities:
  - 'impact' → CHANGE
  - 'changes' → CHANGE
  - 'urban' → LULC
  - 'growth' → CHANGE

Processing ID: 1-s2.0-S0301479717300713-main_236
Text preview: However, it also becomes evident that the majority of parameters with low or very low confidence pot...
Found 2 entities:
  - 'improved' → CHANGE
  - 'crop' → LULC

Processing ID: 1-s2.0-S0301479717300713-main_226a
Text preview: However, some authors from the literature review showed a diverging picture of poverty as a driver o...
Found 5 entities:
  - 'driver' → CHANGE
  - '2016' → DATE
  - '2010' → DATE
  - '2010' → DATE
  - '2015' → DATE

Processing ID: 1-s2.0-S0140196313000608-main_137
Text preview: However, the same approach may apply to understand the different combinations of outcomes that are g...
Found 3 entities:
  - 'crop' → LULC
  - 'increase' → CHANGE
  - 'decrease' → CHANGE

Processing ID: 1-s2.0-S0301479717300713-main_881
Text preview: I doubt that this is for [agricultural land]...
No entities found

Processing ID: 1-s2.0-S030438781000043X-mainext_43
Text preview: I find that land tenure affects incentives to leave land [fallow] and to plant trees, but has a weak...
Found 3 entities:
  - 'fallow' → LULC
  - 'trees' → LULC
  - 'impact' → CHANGE

Processing ID: 1-s2.0-S0304387816300670-main_138
Text preview: If the [city] has a tiny or non-existent traded manufacturing sector so that +'}, {'@xmlns': 'http:/...
Found 2 entities:
  - 'city' → LULC
  - '30' → CARDINAL

Processing ID: 1-s2.0-S0304387816300670-main_558
Text preview: If the [city] has a tradable manufacturing sector that is not too small relative to its local servic...
Found 5 entities:
  - 'city' → LULC
  - 'decline' → CHANGE
  - 'increase' → CHANGE
  - 'urban' → LULC
  - 'city' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_82
Text preview: In 1986, the grazing land had much higher proportion of the total regional area than other [land use...
Found 3 entities:
  - '1986' → DATE
  - 'croplands' → LULC
  - '16 years' → DATE

Processing ID: 1-s2.0-S0264837715302131-main_74
Text preview: In 1990, woodland and tree [savanna] were still the dominant [land cover] types...
Found 3 entities:
  - '1990' → DATE
  - 'tree' → LULC
  - 'savanna' → LULC

Processing ID: 1-s2.0-S0168192311001122-main_159
Text preview: In addition to the decrease in [maize] yield the interannual variability is increasing in the yield ...
Found 2 entities:
  - 'decrease' → CHANGE
  - 'increasing' → CHANGE

Processing ID: 1-s2.0-S0308521X12000157-main_281a
Text preview: In Benin, the choice of [cotton] farmers to switch to subsidized food crops a few years ago motivate...
Found 5 entities:
  - 'Benin' → LOC
  - 'cotton' → LULC
  - 'crops' → LULC
  - 'a few years ago' → DATE
  - 'cotton' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_4
Text preview: In fact, some NTFP-providing trees, such as the baobab (Adansonia digitata) and the shea tree (Vitel...
Found 4 entities:
  - 'trees' → LULC
  - 'tree' → LULC
  - 'cultivation' → PROCESS
  - 'fallows' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_563a
Text preview: In his study of the ICRISAT villages, he argues that, except in Sayero, all "have passed or are appr...
Found 1 entities:
  - 'fallow' → LULC

Processing ID: 1-s2.0-S0140196313000608-main_75
Text preview: In northern Burkina Faso, temporary migration is also one of the diversification strategies observed...
Found 15 entities:
  - 'Burkina Faso' → LOC
  - '2.5' → CARDINAL
  - '1994' → DATE
  - '2009' → DATE
  - '1988' → DATE
  ... and 10 more

Processing ID: 1-s2.0-S0140196322000143-main_273
Text preview: In rangelands, the main cause of woody vegetation decrease is the increasing pressure on wood resour...
Found 7 entities:
  - 'cause' → CHANGE
  - 'decrease' → CHANGE
  - 'increasing' → CHANGE
  - 'growing' → CHANGE
  - 'urban' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S0140196313000608-main_184
Text preview: In Saloum Senegal, with the increase of cultivated land and shortening of [fallow] cycles, soils hav...
Found 6 entities:
  - 'Saloum' → LOC
  - 'Senegal' → LOC
  - 'increase' → CHANGE
  - 'fallow' → LULC
  - 'fallow' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0169204617300270-main_293
Text preview: In the case of Ghana, that statement might be true for Kumasi as expanding [city] in the hinterlands...
Found 4 entities:
  - 'Ghana' → LOC
  - 'expanding' → CHANGE
  - 'city' → LULC
  - 'Bolgatanga' → LOC

Processing ID: 1-s2.0-S0140196313000608-main_9
Text preview: In the course of the last three to four decades a range of environmental policies has been concerned...
Found 1 entities:
  - 'the last three to four decades' → DATE

Processing ID: 1-s2.0-S0301479717300713-main_147
Text preview: In the past, missing or low fertilizer input was compensated by the [crop]-[fallow] practice, but la...
Found 5 entities:
  - 'crop' → LULC
  - 'fallow' → LULC
  - 'growth' → CHANGE
  - 'cultivation' → PROCESS
  - 'crops' → LULC

Processing ID: 1-s2.0-S0168192311001122-main_130
Text preview: In the scenario run, an EPIC input database file for each of the 1462 LUSAC units was prepared, cont...
Found 4 entities:
  - '1462' → CARDINAL
  - 'crop' → LULC
  - 'fallow' → LULC
  - 'crop' → LULC

Processing ID: 1-s2.0-S0301479717300713-main_99
Text preview: In total, 12 documents were identified as relevant in the context of [LULCC] in the UER (Table )...
Found 1 entities:
  - '12' → CARDINAL

Processing ID: 1-s2.0-S016788090800131X-main_77
Text preview: In Yale ´, the size of [crop] and grazing lands increased by 9 and 18% in 2002 compared to the sizes...
Found 10 entities:
  - 'crop' → LULC
  - 'increased' → CHANGE
  - '9' → CARDINAL
  - '18%' → PERCENT
  - '2002' → DATE
  ... and 5 more

Processing ID: 1-s2.0-S0169204617300270-main_289
Text preview: Ineffective [land use] planning can contribute to an increase in land fragmentation resulting in los...
Found 2 entities:
  - 'increase' → CHANGE
  - 'loss' → CHANGE

Processing ID: 1-s2.0-S235198941500102X-main_200
Text preview: Insights into some of these causes were highlighted in this study.'}]}, {'@xmlns': 'http://www.tei-c...
Found 3 entities:
  - 'causes' → CHANGE
  - 'causes' → CHANGE
  - 'deforestation' → PROCESS


In [4]:
import pandas as pd
import json
from transformers import pipeline, AutoTokenizer

# Load your CSV file
print("📂 Loading CSV file...")
csv_file = 'annotated_corpus_for_dataverse.csv'  # Update with your file path
df = pd.read_csv(csv_file)

# Filter for rows where relevance_label is not 'zero'
print("🔍 Filtering data...")
filtered_df = df[df['relevance_label'] != 'zero'].copy()
print(f"✅ Filtered to {len(filtered_df)} rows")

# Load your fixed model for entity extraction
ner_pipeline = pipeline(
    "ner",
    model="./final_ner_model",  # Update with your model path
    tokenizer="./final_ner_model",
    aggregation_strategy="none"  # This ensures we get token-level predictions
)

# Also load the tokenizer separately to get all tokens
tokenizer = AutoTokenizer.from_pretrained("./final_ner_model")

# Process each text_segment in the filtered DataFrame
results = []

print("\n📊 Processing and extracting entities from filtered sentences...")

for index, row in filtered_df.iterrows():
    article_id = row['id_segment']
    original_sentence = row['text_segment']
    print(f"\nProcessing ID: {article_id}")
    print(f"Text: {original_sentence[:100]}...")  # Show first 100 chars
    
    # Get NER predictions
    ner_results = ner_pipeline(original_sentence)
    
    # Tokenize the text to get all tokens
    tokens = tokenizer(original_sentence, return_offsets_mapping=True)
    
    # Create a list to hold all tokens with their labels
    all_tokens_with_labels = []
    
    # First, mark all tokens as 'O' by default
    for i, (start, end) in enumerate(tokens['offset_mapping']):
        if start == end:  # Skip special tokens
            continue
        token_text = original_sentence[start:end]
        all_tokens_with_labels.append({
            'text': token_text,
            'label': 'O',
            'start_char': start,
            'end_char': end
        })
    
    # Then update with actual entity labels
    for entity in ner_results:
        # Find which token this entity corresponds to
        for token_info in all_tokens_with_labels:
            if (token_info['start_char'] == entity['start'] and 
                token_info['end_char'] == entity['end']):
                token_info['label'] = entity['entity']
                break
    
    # Prepare the output structure
    output_entry = {
        "article_id": article_id,
        "original_sentence": original_sentence,
        "entities": all_tokens_with_labels
    }
    
    results.append(output_entry)
    
    # Print ALL tokens with their labels
    print("All tokens with labels:")
    for token in all_tokens_with_labels:
        print(f"  - text: '{token['text']}'")
        print(f"    label: {token['label']}")
        print(f"    start_char: {token['start_char']}")
        print(f"    end_char: {token['end_char']}")

# Save results as JSON
output_json_file = 'model_extraction_results_with_all_tokens.json'
with open(output_json_file, 'w') as f:
    json.dump(results, f, indent=2)

print(f"\n✅ Processing complete. Results saved to '{output_json_file}' as JSON.")

# Print summary of all unique labels found
all_labels = set()
for result in results:
    for entity in result['entities']:
        all_labels.add(entity['label'])

print(f"\n📊 Summary - Unique labels found: {sorted(all_labels)}")

📂 Loading CSV file...
🔍 Filtering data...
✅ Filtered to 803 rows

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

📊 Processing and extracting entities from filtered sentences...

Processing ID: 1-s2.0-S0301479717300713-main_226b
Text: #text': '(Lambin et al., 2003)'}], '#text': 'With high confidence, rainfall variability is a driving...
All tokens with labels:
  - text: '#'
    label: O
    start_char: 0
    end_char: 1
  - text: 'text'
    label: O
    start_char: 1
    end_char: 5
  - text: '':'
    label: O
    start_char: 5
    end_char: 7
  - text: ''('
    label: O
    start_char: 8
    end_char: 10
  - text: 'L'
    label: O
    start_char: 10
    end_char: 11
  - text: 'amb'
    label: O
    start_char: 11
    end_char: 14
  - text: 'in'
    label: O
    start_char: 14
    end_char: 16
  - text: 'et'
    label: O
    start_char: 17
    end_char: 19
  - text: 'al'
    label: O
    start_char: 20
    end_char: 22
  - text: '.,'
    label: O
    start_char: 22
    end_char: 24
  - text: '2003'
    label: B-DATE
    start_char: 25
    end_char: 29
  - text: ')''
    label: O
    start_char: 29
    end_char: 31
  - text: '}'
    label: O
    start_char: 31
    end_char: 32
  - text: '],'
    label: O
    start_char: 32
    end_char: 34
  - text: '''
    label: O
    start_char: 35
    end_char: 36
  - text: '#'
    label: O
    start_char: 36
    end_char: 37
  - text: 'text'
    label: O
    start_char: 37
    end_char: 41
  - text: '':'
    label: O
    start_char: 41
    end_char: 43
  - text: '''
    label: O
    start_char: 44
    end_char: 45
  - text: 'With'
    label: O
    start_char: 45
    end_char: 49
  - text: 'high'
    label: O
    start_char: 50
    end_char: 54
  - text: 'confidence'
    label: O
    start_char: 55
    end_char: 65
  - text: ','
    label: O
    start_char: 65
    end_char: 66
  - text: 'rainfall'
    label: O
    start_char: 67
    end_char: 75
  - text: 'variability'
    label: O
    start_char: 76
    end_char: 87
  - text: 'is'
    label: O
    start_char: 88
    end_char: 90
  - text: 'a'
    label: O
    start_char: 91
    end_char: 92
  - text: 'driving'
    label: B-CHANGE
    start_char: 93
    end_char: 100
  - text: 'force'
    label: O
    start_char: 101
    end_char: 106
  - text: 'of'
    label: O
    start_char: 107
    end_char: 109
  - text: '['
    label: O
    start_char: 110
    end_char: 111
  - text: 'L'
    label: O
    start_char: 111
    end_char: 112
  - text: 'UL'
    label: O
    start_char: 112
    end_char: 114
  - text: 'CC'
    label: O
    start_char: 114
    end_char: 116
  - text: ']'
    label: O
    start_char: 116
    end_char: 117

Processing ID: 1-s2.0-S0303243414001718-main_19b
Text: #text': 'After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was ...
All tokens with labels:
  - text: '#'
    label: O
    start_char: 0
    end_char: 1
  - text: 'text'
    label: O
    start_char: 1
    end_char: 5
  - text: '':'
    label: O
    start_char: 5
    end_char: 7
  - text: '''
    label: O
    start_char: 8
    end_char: 9
  - text: 'After'
    label: O
    start_char: 9
    end_char: 14
  - text: 'the'
    label: O
    start_char: 15
    end_char: 18
  - text: 'd'
    label: O
    start_char: 19
    end_char: 20
  - text: 'rough'
    label: O
    start_char: 20
    end_char: 25
  - text: 'ts'
    label: O
    start_char: 25
    end_char: 27
  - text: 'in'
    label: O
    start_char: 28
    end_char: 30
  - text: 'the'
    label: B-DATE
    start_char: 31
    end_char: 34
  - text: '1970'
    label: I-DATE
    start_char: 35
    end_char: 39
  - text: 's'
    label: I-DATE
    start_char: 39
    end_char: 40
  - text: 'and'
    label: I-DATE
    start_char: 41
    end_char: 44
  - text: '1980'
    label: I-DATE
    start_char: 45
    end_char: 49
  - text: 's'
    label: I-DATE
    start_char: 49
    end_char: 50
  - text: ','
    label: O
    start_char: 50
    end_char: 51
  - text: 'the'
    label: O
    start_char: 52
    end_char: 55
  - text: 'observed'
    label: O
    start_char: 56
    end_char: 64
  - text: 'loss'
    label: B-CHANGE
    start_char: 65
    end_char: 69
  - text: 'of'
    label: O
    start_char: 70
    end_char: 72
  - text: 'wood'
    label: O
    start_char: 73
    end_char: 77
  - text: 'y'
    label: O
    start_char: 77
    end_char: 78
  - text: 'vegetation'
    label: O
    start_char: 79
    end_char: 89
  - text: 'cover'
    label: O
    start_char: 90
    end_char: 95
  - text: 'was'
    label: O
    start_char: 96
    end_char: 99
  - text: 'often'
    label: O
    start_char: 100
    end_char: 105
  - text: 'considered'
    label: O
    start_char: 106
    end_char: 116
  - text: 'as'
    label: O
    start_char: 117
    end_char: 119
  - text: 'irreversible'
    label: O
    start_char: 120
    end_char: 132
  - text: '['
    label: O
    start_char: 133
    end_char: 134
  - text: 'des'
    label: O
    start_char: 134
    end_char: 137
  - text: 'ert'
    label: O
    start_char: 137
    end_char: 140
  - text: 'ification'
    label: O
    start_char: 140
    end_char: 149
  - text: ']'
    label: O
    start_char: 149
    end_char: 150
  - text: 'and'
    label: O
    start_char: 151
    end_char: 154
  - text: 'large'
    label: O
    start_char: 155
    end_char: 160
  - text: 'parts'
    label: O
    start_char: 161
    end_char: 166
  - text: 'of'
    label: O
    start_char: 167
    end_char: 169
  - text: 'the'
    label: O
    start_char: 170
    end_char: 173
  - text: 'Sa'
    label: O
    start_char: 174
    end_char: 176
  - text: 'hel'
    label: O
    start_char: 176
    end_char: 179
  - text: 'were'
    label: O
    start_char: 180
    end_char: 184
  - text: 'designated'
    label: O
    start_char: 185
    end_char: 195
  - text: 'as'
    label: O
    start_char: 196
    end_char: 198
  - text: 'degraded'
    label: O
    start_char: 199
    end_char: 207
  - text: 'land'
    label: O
    start_char: 208
    end_char: 212
  - text: '('
    label: O
    start_char: 213
    end_char: 214
  - text: 'e'
    label: O
    start_char: 214
    end_char: 215
  - text: '.'
    label: O
    start_char: 215
    end_char: 216
  - text: 'g'
    label: O
    start_char: 216
    end_char: 217

Processing ID: 1-s2.0-S030438781000043X-mainext_313b
Text: #text': 'Few investment opportunities are available to most Rwandan farmers...
All tokens with labels:
  - text: '#'
    label: O
    start_char: 0
    end_char: 1
  - text: 'text'
    label: O
    start_char: 1
    end_char: 5
  - text: '':'
    label: O
    start_char: 5
    end_char: 7
  - text: '''
    label: O
    start_char: 8
    end_char: 9
  - text: 'Few'
    label: O
    start_char: 9
    end_char: 12
  - text: 'investment'
    label: O
    start_char: 13
    end_char: 23
  - text: 'opportunities'
    label: O
    start_char: 24
    end_char: 37
  - text: 'are'
    label: O
    start_char: 38
    end_char: 41
  - text: 'available'
    label: O
    start_char: 42
    end_char: 51
  - text: 'to'
    label: O
    start_char: 52
    end_char: 54
  - text: 'most'
    label: O
    start_char: 55
    end_char: 59
  - text: 'Rw'
    label: B-LOC
    start_char: 60
    end_char: 62
  - text: 'andan'
    label: I-LOC
    start_char: 62
    end_char: 67
  - text: 'farmers'
    label: O
    start_char: 68
    end_char: 75

Processing ID: 1-s2.0-S095937809800003X-main_75b
Text: #text': 'Pastoral production has often existed in some sort of symbiotic interaction with the [agric...
All tokens with labels:
  - text: '#'
    label: O
    start_char: 0
    end_char: 1
  - text: 'text'
    label: O
    start_char: 1
    end_char: 5
  - text: '':'
    label: O
    start_char: 5
    end_char: 7
  - text: '''
    label: O
    start_char: 8
    end_char: 9
  - text: 'Past'
    label: O
    start_char: 9
    end_char: 13
  - text: 'oral'
    label: O
    start_char: 13
    end_char: 17
  - text: 'production'
    label: O
    start_char: 18
    end_char: 28
  - text: 'has'
    label: O
    start_char: 29
    end_char: 32
  - text: 'often'
    label: O
    start_char: 33
    end_char: 38
  - text: 'existed'
    label: O
    start_char: 39
    end_char: 46
  - text: 'in'
    label: O
    start_char: 47
    end_char: 49
  - text: 'some'
    label: O
    start_char: 50
    end_char: 54
  - text: 'sort'
    label: O
    start_char: 55
    end_char: 59
  - text: 'of'
    label: O
    start_char: 60
    end_char: 62
  - text: 'symb'
    label: O
    start_char: 63
    end_char: 67
  - text: 'iotic'
    label: O
    start_char: 67
    end_char: 72
  - text: 'interaction'
    label: O
    start_char: 73
    end_char: 84
  - text: 'with'
    label: O
    start_char: 85
    end_char: 89
  - text: 'the'
    label: O
    start_char: 90
    end_char: 93
  - text: '['
    label: O
    start_char: 94
    end_char: 95
  - text: 'ag'
    label: B-LULC
    start_char: 95
    end_char: 97
  - text: 'ric'
    label: I-LULC
    start_char: 97
    end_char: 100
  - text: 'ulture'
    label: I-LULC
    start_char: 100
    end_char: 106
  - text: ']'
    label: O
    start_char: 106
    end_char: 107

Processing ID: 1-s2.0-S0006320709005400-main_16b
Text: #text': 'The forests of West and Central Africa probably originally covered a combined area of about...
All tokens with labels:
  - text: '#'
    label: O
    start_char: 0
    end_char: 1
  - text: 'text'
    label: O
    start_char: 1
    end_char: 5
  - text: '':'
    label: O
    start_char: 5
    end_char: 7
  - text: '''
    label: O
    start_char: 8
    end_char: 9
  - text: 'The'
    label: O
    start_char: 9
    end_char: 12
  - text: 'forests'
    label: B-LULC
    start_char: 13
    end_char: 20
  - text: 'of'
    label: O
    start_char: 21
    end_char: 23
  - text: 'West'
    label: B-LOC
    start_char: 24
    end_char: 28
  - text: 'and'
    label: O
    start_char: 29
    end_char: 32
  - text: 'Central'
    label: B-LOC
    start_char: 33
    end_char: 40
  - text: 'Africa'
    label: I-LOC
    start_char: 41
    end_char: 47
  - text: 'probably'
    label: O
    start_char: 48
    end_char: 56
  - text: 'originally'
    label: O
    start_char: 57
    end_char: 67
  - text: 'covered'
    label: O
    start_char: 68
    end_char: 75
  - text: 'a'
    label: O
    start_char: 76
    end_char: 77
  - text: 'combined'
    label: O
    start_char: 78
    end_char: 86
  - text: 'area'
    label: B-SURFACE_UNIT
    start_char: 87
    end_char: 91
  - text: 'of'
    label: I-SURFACE_UNIT
    start_char: 92
    end_char: 94
  - text: 'about'
    label: I-SURFACE_UNIT
    start_char: 95
    end_char: 100
  - text: '3'
    label: I-SURFACE_UNIT
    start_char: 101
    end_char: 102
  - text: 'million'
    label: I-SURFACE_UNIT
    start_char: 103
    end_char: 110
  - text: 'km'
    label: I-SURFACE_UNIT
    start_char: 111
    end_char: 113
  - text: '2'
    label: B-CARDINAL
    start_char: 114
    end_char: 115

Processing ID: 1-s2.0-S095937809800003X-main_8
Text: (1993)'}], '#text': "An increase of land under [cultivation] can be in the form of either (a) cleari...
All tokens with labels:
  - text: '('
    label: O
    start_char: 0
    end_char: 1
  - text: '1993'
    label: B-DATE
    start_char: 1
    end_char: 5
  - text: ')''
    label: O
    start_char: 5
    end_char: 7
  - text: '}'
    label: O
    start_char: 7
    end_char: 8
  - text: '],'
    label: O
    start_char: 8
    end_char: 10
  - text: '''
    label: O
    start_char: 11
    end_char: 12
  - text: '#'
    label: O
    start_char: 12
    end_char: 13
  - text: 'text'
    label: O
    start_char: 13
    end_char: 17
  - text: '':'
    label: O
    start_char: 17
    end_char: 19
  - text: '"'
    label: O
    start_char: 20
    end_char: 21
  - text: 'An'
    label: O
    start_char: 21
    end_char: 23
  - text: 'increase'
    label: B-CHANGE
    start_char: 24
    end_char: 32
  - text: 'of'
    label: O
    start_char: 33
    end_char: 35
  - text: 'land'
    label: O
    start_char: 36
    end_char: 40
  - text: 'under'
    label: O
    start_char: 41
    end_char: 46
  - text: '['
    label: O
    start_char: 47
    end_char: 48
  - text: 'cult'
    label: B-PROCESS
    start_char: 48
    end_char: 52
  - text: 'ivation'
    label: I-PROCESS
    start_char: 52
    end_char: 59
  - text: ']'
    label: O
    start_char: 59
    end_char: 60
  - text: 'can'
    label: O
    start_char: 61
    end_char: 64
  - text: 'be'
    label: O
    start_char: 65
    end_char: 67
  - text: 'in'
    label: O
    start_char: 68
    end_char: 70
  - text: 'the'
    label: O
    start_char: 71
    end_char: 74
  - text: 'form'
    label: O
    start_char: 75
    end_char: 79
  - text: 'of'
    label: O
    start_char: 80
    end_char: 82
  - text: 'either'
    label: O
    start_char: 83
    end_char: 89
  - text: '('
    label: O
    start_char: 90
    end_char: 91
  - text: 'a'
    label: O
    start_char: 91
    end_char: 92
  - text: ')'
    label: O
    start_char: 92
    end_char: 93
  - text: 'clearing'
    label: O
    start_char: 94
    end_char: 102
  - text: 'more'
    label: O
    start_char: 103
    end_char: 107
  - text: 'land'
    label: O
    start_char: 108
    end_char: 112
  - text: 'within'
    label: O
    start_char: 113
    end_char: 119
  - text: 'the'
    label: O
    start_char: 120
    end_char: 123
  - text: 'present'
    label: O
    start_char: 124
    end_char: 131
  - text: 'territory'
    label: O
    start_char: 132
    end_char: 141
  - text: ','
    label: O
    start_char: 141
    end_char: 142
  - text: 'or'
    label: O
    start_char: 143
    end_char: 145
  - text: '('
    label: O
    start_char: 146
    end_char: 147
  - text: 'b'
    label: O
    start_char: 147
    end_char: 148
  - text: ')'
    label: O
    start_char: 148
    end_char: 149
  - text: 'migrating'
    label: O
    start_char: 150
    end_char: 159
  - text: 'to'
    label: O
    start_char: 160
    end_char: 162
  - text: 'other'
    label: O
    start_char: 163
    end_char: 168
  - text: 'areas'
    label: O
    start_char: 169
    end_char: 174
  - text: 'to'
    label: O
    start_char: 175
    end_char: 177
  - text: 'develop'
    label: O
    start_char: 178
    end_char: 185
  - text: 'new'
    label: O
    start_char: 186
    end_char: 189
  - text: 'land'
    label: O
    start_char: 190
    end_char: 194
  - text: 'for'
    label: O
    start_char: 195
    end_char: 198
  - text: '['
    label: O
    start_char: 199
    end_char: 200
  - text: 'cult'
    label: B-PROCESS
    start_char: 200
    end_char: 204
  - text: 'ivation'
    label: I-PROCESS
    start_char: 204
    end_char: 211
  - text: ']'
    label: O
    start_char: 211
    end_char: 212

Processing ID: 1-s2.0-S0304387816300670-main_75
Text: (2006), who estimate an increase in the national [urban] share of 0.45 percent with a reduction in n...
All tokens with labels:
  - text: '('
    label: O
    start_char: 0
    end_char: 1
  - text: '2006'
    label: B-DATE
    start_char: 1
    end_char: 5
  - text: '),'
    label: O
    start_char: 5
    end_char: 7
  - text: 'who'
    label: O
    start_char: 8
    end_char: 11
  - text: 'estimate'
    label: O
    start_char: 12
    end_char: 20
  - text: 'an'
    label: O
    start_char: 21
    end_char: 23
  - text: 'increase'
    label: B-CHANGE
    start_char: 24
    end_char: 32
  - text: 'in'
    label: O
    start_char: 33
    end_char: 35
  - text: 'the'
    label: O
    start_char: 36
    end_char: 39
  - text: 'national'
    label: O
    start_char: 40
    end_char: 48
  - text: '['
    label: O
    start_char: 49
    end_char: 50
  - text: 'urban'
    label: B-LULC
    start_char: 50
    end_char: 55
  - text: ']'
    label: O
    start_char: 55
    end_char: 56
  - text: 'share'
    label: O
    start_char: 57
    end_char: 62
  - text: 'of'
    label: O
    start_char: 63
    end_char: 65
  - text: '0'
    label: B-PERCENT
    start_char: 66
    end_char: 67
  - text: '.'
    label: I-PERCENT
    start_char: 67
    end_char: 68
  - text: '45'
    label: I-PERCENT
    start_char: 68
    end_char: 70
  - text: 'percent'
    label: I-PERCENT
    start_char: 71
    end_char: 78
  - text: 'with'
    label: O
    start_char: 79
    end_char: 83
  - text: 'a'
    label: O
    start_char: 84
    end_char: 85
  - text: 'reduction'
    label: B-CHANGE
    start_char: 86
    end_char: 95
  - text: 'in'
    label: O
    start_char: 96
    end_char: 98
  - text: 'national'
    label: O
    start_char: 99
    end_char: 107
  - text: 'rainfall'
    label: O
    start_char: 108
    end_char: 116
  - text: 'of'
    label: O
    start_char: 117
    end_char: 119
  - text: '1'
    label: B-PERCENT
    start_char: 120
    end_char: 121
  - text: 'percent'
    label: I-PERCENT
    start_char: 122
    end_char: 129

Processing ID: 1-s2.0-S0140196313000608-main_212
Text: (2011)'}], '#text': 'Perhaps most importantly, the meta-analysis exposes the surprisingly huge gap i...
All tokens with labels:
  - text: '('
    label: O
    start_char: 0
    end_char: 1
  - text: '2011'
    label: B-DATE
    start_char: 1
    end_char: 5
  - text: ')''
    label: O
    start_char: 5
    end_char: 7
  - text: '}'
    label: O
    start_char: 7
    end_char: 8
  - text: '],'
    label: O
    start_char: 8
    end_char: 10
  - text: '''
    label: O
    start_char: 11
    end_char: 12
  - text: '#'
    label: O
    start_char: 12
    end_char: 13
  - text: 'text'
    label: O
    start_char: 13
    end_char: 17
  - text: '':'
    label: O
    start_char: 17
    end_char: 19
  - text: '''
    label: O
    start_char: 20
    end_char: 21
  - text: 'Perhaps'
    label: O
    start_char: 21
    end_char: 28
  - text: 'most'
    label: O
    start_char: 29
    end_char: 33
  - text: 'importantly'
    label: O
    start_char: 34
    end_char: 45
  - text: ','
    label: O
    start_char: 45
    end_char: 46
  - text: 'the'
    label: O
    start_char: 47
    end_char: 50
  - text: 'meta'
    label: O
    start_char: 51
    end_char: 55
  - text: '-'
    label: O
    start_char: 55
    end_char: 56
  - text: 'analysis'
    label: O
    start_char: 56
    end_char: 64
  - text: 'exposes'
    label: O
    start_char: 65
    end_char: 72
  - text: 'the'
    label: O
    start_char: 73
    end_char: 76
  - text: 'surprisingly'
    label: O
    start_char: 77
    end_char: 89
  - text: 'huge'
    label: O
    start_char: 90
    end_char: 94
  - text: 'gap'
    label: O
    start_char: 95
    end_char: 98
  - text: 'in'
    label: O
    start_char: 99
    end_char: 101
  - text: 'the'
    label: O
    start_char: 102
    end_char: 105
  - text: 'scientific'
    label: O
    start_char: 106
    end_char: 116
  - text: 'literature'
    label: O
    start_char: 117
    end_char: 127
  - text: 'when'
    label: O
    start_char: 128
    end_char: 132
  - text: 'it'
    label: O
    start_char: 133
    end_char: 135
  - text: 'comes'
    label: O
    start_char: 136
    end_char: 141
  - text: 'to'
    label: O
    start_char: 142
    end_char: 144
  - text: 'actual'
    label: O
    start_char: 145
    end_char: 151
  - text: 'measurements'
    label: O
    start_char: 152
    end_char: 164
  - text: 'of'
    label: O
    start_char: 165
    end_char: 167
  - text: '['
    label: O
    start_char: 168
    end_char: 169
  - text: 'crop'
    label: B-LULC
    start_char: 169
    end_char: 173
  - text: ']'
    label: O
    start_char: 173
    end_char: 174
  - text: 'land'
    label: O
    start_char: 175
    end_char: 179
  - text: 'change'
    label: B-CHANGE
    start_char: 180
    end_char: 186
  - text: 'in'
    label: O
    start_char: 187
    end_char: 189
  - text: 'the'
    label: O
    start_char: 190
    end_char: 193
  - text: 'Sa'
    label: O
    start_char: 194
    end_char: 196
  - text: 'hel'
    label: O
    start_char: 196
    end_char: 199
  - text: ','
    label: O
    start_char: 199
    end_char: 200
  - text: 'which'
    label: O
    start_char: 201
    end_char: 206
  - text: 'are'
    label: O
    start_char: 207
    end_char: 210

Token indices sequence length is longer than the specified maximum sequence length for this model (712 > 512). Running this sequence through the model will result in indexing errors

All tokens with labels:
  - text: 'For'
    label: O
    start_char: 0
    end_char: 3
  - text: 'example'
    label: O
    start_char: 4
    end_char: 11
  - text: ','
    label: O
    start_char: 11
    end_char: 12
  - text: 'Pok'
    label: O
    start_char: 13
    end_char: 16
  - text: 'u'
    label: O
    start_char: 16
    end_char: 17
  - text: '-'
    label: O
    start_char: 17
    end_char: 18
  - text: 'Bo'
    label: O
    start_char: 18
    end_char: 20
  - text: 'ans'
    label: O
    start_char: 20
    end_char: 23
  - text: 'i'
    label: O
    start_char: 23
    end_char: 24
  - text: '&'
    label: O
    start_char: 25
    end_char: 26
  - text: 'Am'
    label: O
    start_char: 27
    end_char: 29
  - text: 'oak'
    label: O
    start_char: 29
    end_char: 32
  - text: 'o'
    label: O
    start_char: 32
    end_char: 33
  - text: '('
    label: O
    start_char: 34
    end_char: 35
  - text: '2015'
    label: B-DATE
    start_char: 35
    end_char: 39
  - text: ')'
    label: O
    start_char: 39
    end_char: 40
  - text: 'compared'
    label: O
    start_char: 41
    end_char: 49
  - text: 'spatial'
    label: O
    start_char: 50
    end_char: 57
  - text: 'inequalities'
    label: O
    start_char: 58
    end_char: 70
  - text: 'of'
    label: O
    start_char: 71
    end_char: 73
  - text: 'cities'
    label: B-LULC
    start_char: 74
    end_char: 80
  - text: 'within'
    label: O
    start_char: 81
    end_char: 87
  - text: 'Ghana'
    label: B-LOC
    start_char: 88
    end_char: 93
  - text: ','
    label: O
    start_char: 93
    end_char: 94
  - text: 'including'
    label: O
    start_char: 95
    end_char: 104
  - text: 'Tak'
    label: B-LOC
    start_char: 105
    end_char: 108
  - text: 'or'
    label: I-LOC
    start_char: 108
    end_char: 110
  - text: 'adi'
    label: I-LOC
    start_char: 110
    end_char: 113
  - text: 'and'
    label: O
    start_char: 114
    end_char: 117
  - text: 'Bol'
    label: B-LOC
    start_char: 118
    end_char: 121
  - text: 'gat'
    label: I-LOC
    start_char: 121
    end_char: 124
  - text: 'anga'
    label: I-LOC
    start_char: 124
    end_char: 128
  - text: ','
    label: O
    start_char: 128
    end_char: 129
  - text: 'using'
    label: O
    start_char: 130
    end_char: 135
  - text: 'statistics'
    label: O
    start_char: 136
    end_char: 146
  - text: '('
    label: O
    start_char: 147
    end_char: 148
  - text: 'secondary'
    label: O
    start_char: 148
    end_char: 157
  - text: 'data'
    label: O
    start_char: 158
    end_char: 162
  - text: ')'
    label: O
    start_char: 162
    end_char: 163
  - text: 'without'
    label: O
    start_char: 164
    end_char: 171
  - text: 'consulting'
    label: O
    start_char: 172
    end_char: 182
  - text: 'experts'
    label: O
    start_char: 183
    end_char: 190
  - text: 'or'
    label: O
    start_char: 191
    end_char: 193
  - text: 'comparing'
    label: O
    start_char: 194
    end_char: 203
  - text: '[['
    label: O
    start_char: 204
    end_char: 206
  - text: 'urban'
    label: B-LULC
    start_char: 206
    end_char: 211
  - text: ']'
    label: O
    start_char: 211
    end_char: 212
  - text: 'development'
    label: O
    start_char: 213
    end_char: 224
  - text: ']'
    label: O
    start_char: 224
    end_char: 225
  - text: 'with'
    label: O
    start_char: 226
    end_char: 230
  - text: 'the'
    label: O
    start_char: 231
    end_char: 234
  - text: 'aid'
    label: O
    start_char: 235
    end_char: 238
  - text: 'of'
    label: O
    start_char: 239
    end_char: 241
  - text: 'remote'
    label: O
    start_char: 242
    end_char: 248
  - text: 'sensing'
    label: O
    start_char: 249
    end_char: 256
  - text: 'data'
    label: O
    start_char: 257
    end_char: 261
  - text: '.''
    label: O
    start_char: 261
    end_char: 263
  - text: '},'
    label: O
    start_char: 263
    end_char: 265
  - text: '''
    label: O
    start_char: 266
    end_char: 267
  - text: 'The'
    label: O
    start_char: 267
    end_char: 270
  - text: 'specific'
    label: O
    start_char: 271
    end_char: 279
  - text: 'research'
    label: O
    start_char: 280
    end_char: 288
  - text: 'questions'
    label: O
    start_char: 289
    end_char: 298
  - text: 'are'
    label: O
    start_char: 299
    end_char: 302
  - text: ':'
    label: O
    start_char: 302
    end_char: 303
  - text: '','
    label: O
    start_char: 303
    end_char: 305
  - text: '''
    label: O
    start_char: 306
    end_char: 307
  - text: '•'
    label: O
    start_char: 307
    end_char: 308
  - text: 'What'
    label: O
    start_char: 309
    end_char: 313
  - text: 'are'
    label: O
    start_char: 314
    end_char: 317
  - text: 'the'
    label: O
    start_char: 318
    end_char: 321
  - text: 'patterns'
    label: O
    start_char: 322
    end_char: 330
  - text: 'of'
    label: O
    start_char: 331
    end_char: 333
  - text: 'per'
    label: O
    start_char: 334
    end_char: 337
  - text: 'i'
    label: O
    start_char: 337
    end_char: 338
  - text: '-'
    label: O
    start_char: 338
    end_char: 339
  - text: '[['
    label: O
    start_char: 339
    end_char: 341
  - text: 'urban'
    label: B-LULC
    start_char: 341
    end_char: 346
  - text: ']'
    label: O
    start_char: 346
    end_char: 347
  - text: 'development'
    label: O
    start_char: 348
    end_char: 359
  - text: ']'
    label: O
    start_char: 359
    end_char: 360
  - text: 'and'
    label: O
    start_char: 361
    end_char: 364
  - text: 'differences'
    label: O
    start_char: 365
    end_char: 376
  - text: 'between'
    label: O
    start_char: 377
    end_char: 384
  - text: 'northern'
    label: O
    start_char: 385
    end_char: 393
  - text: 'and'
    label: O
    start_char: 394
    end_char: 397
  - text: 'southern'
    label: O
    start_char: 398
    end_char: 406
  - text: 'Ghana'
    label: B-LOC
    start_char: 407
    end_char: 412
  - text: ','
    label: O
    start_char: 412
    end_char: 413
  - text: 'using'
    label: O
    start_char: 414
    end_char: 419
  - text: 'Bol'
    label: B-LOC
    start_char: 420
    end_char: 423
  - text: 'gat'
    label: I-LOC
    start_char: 423
    end_char: 426
  - text: 'anga'
    label: I-LOC
    start_char: 426
    end_char: 430
  - text: 'as'
    label: O
    start_char: 431
    end_char: 433
  - text: 'an'
    label: O
    start_char: 434
    end_char: 436
  - text: 'example'
    label: O
    start_char: 437
    end_char: 444
  - text: 'for'
    label: O
    start_char: 445
    end_char: 448
  - text: 'the'
    label: O
    start_char: 449
    end_char: 452
  - text: 'north'
    label: O
    start_char: 453
    end_char: 458
  - text: 'and'
    label: O
    start_char: 459
    end_char: 462
  - text: 'Tak'
    label: B-LOC
    start_char: 463
    end_char: 466
  - text: 'or'
    label: I-LOC
    start_char: 466
    end_char: 468
  - text: 'adi'
    label: I-LOC
    start_char: 468
    end_char: 471
  - text: 'as'
    label: O
    start_char: 472
    end_char: 474
  - text: 'an'
    label: O
    start_char: 475
    end_char: 477
  - text: 'example'
    label: O
    start_char: 478
    end_char: 485
  - text: 'for'
    label: O
    start_char: 486
    end_char: 489
  - text: 'the'
    label: O
    start_char: 490
    end_char: 493
  - text: 'south'
    label: O
    start_char: 494
    end_char: 499
  - text: '?'
    label: O
    start_char: 499
    end_char: 500
  - text: '•'
    label: O
    start_char: 501
    end_char: 502
  - text: 'What'
    label: O
    start_char: 503
    end_char: 507
  - text: 'are'
    label: O
    start_char: 508
    end_char: 511
  - text: 'the'
    label: O
    start_char: 512
    end_char: 515
  - text: 'determin'
    label: O
    start_char: 516
    end_char: 524
  - text: 'ants'
    label: O
    start_char: 524
    end_char: 528
  - text: 'of'
    label: O
    start_char: 529
    end_char: 531
  - text: '[['
    label: O
    start_char: 532
    end_char: 534
  - text: 'urban'
    label: B-LULC
    start_char: 534
    end_char: 539
  - text: ']'
    label: O
    start_char: 539
    end_char: 540
  - text: 'development'
    label: O
    start_char: 541
    end_char: 552
  - text: ']'
    label: O
    start_char: 552
    end_char: 553
  - text: 'for'
    label: O
    start_char: 554
    end_char: 557
  - text: 'both'
    label: O
    start_char: 558
    end_char: 562
  - text: 'study'
    label: O
    start_char: 563
    end_char: 568
  - text: 'areas'
    label: O
    start_char: 569
    end_char: 574
  - text: '?'
    label: O
    start_char: 574
    end_char: 575
  - text: '•'
    label: O
    start_char: 576
    end_char: 577
  - text: 'Which'
    label: O
    start_char: 578
    end_char: 583
  - text: 'conclusions'
    label: O
    start_char: 584
    end_char: 595
  - text: 'can'
    label: O
    start_char: 596
    end_char: 599
  - text: 'be'
    label: O
    start_char: 600
    end_char: 602
  - text: 'drawn'
    label: O
    start_char: 603
    end_char: 608
  - text: 'for'
    label: O
    start_char: 609
    end_char: 612
  - text: '['
    label: O
    start_char: 613
    end_char: 614
  - text: 'land'
    label: O
    start_char: 614
    end_char: 618
  - text: 'use'
    label: O
    start_char: 619
    end_char: 622
  - text: ']'
    label: O
    start_char: 622
    end_char: 623
  - text: 'planning'
    label: O
    start_char: 624
    end_char: 632
  - text: '?'
    label: O
    start_char: 632
    end_char: 633
  - text: 'What'
    label: O
    start_char: 634
    end_char: 638
  - text: 'are'
    label: O
    start_char: 639
    end_char: 642
  - text: 'the'
    label: O
    start_char: 643
    end_char: 646
  - text: 'current'
    label: O
    start_char: 647
    end_char: 654
  - text: 'opportunities'
    label: O
    start_char: 655
    end_char: 668
  - text: 'and'
    label: O
    start_char: 669
    end_char: 672
  - text: 'challenges'
    label: O
    start_char: 673
    end_char: 683
  - text: 'of'
    label: O
    start_char: 684
    end_char: 686
  - text: '['
    label: O
    start_char: 687
    end_char: 688
  - text: 'land'
    label: O
    start_char: 688
    end_char: 692
  - text: 'use'
    label: O
    start_char: 693
    end_char: 696
  - text: ']'
    label: O
    start_char: 696
    end_char: 697
  - text: 'planning'
    label: O
    start_char: 698
    end_char: 706
  - text: 'and'
    label: O
    start_char: 707
    end_char: 710
  - text: 'how'
    label: O
    start_char: 711
    end_char: 714
  - text: 'can'
    label: O
    start_char: 715
    end_char: 718
  - text: 'they'
    label: O
    start_char: 719
    end_char: 723
  - text: 'be'
    label: O
    start_char: 724
    end_char: 726
  - text: 'linked'
    label: O
    start_char: 727
    end_char: 733
  - text: 'to'
    label: O
    start_char: 734
    end_char: 736
  - text: '['
    label: O
    start_char: 737
    end_char: 738
  - text: 'urban'
    label: B-LULC
    start_char: 738
    end_char: 743
  - text: ']'
    label: O
    start_char: 743
    end_char: 744
  - text: 'sp'
    label: O
    start_char: 745
    end_char: 747
  - text: 'rawl'
    label: O
    start_char: 747
    end_char: 751
  - text: '?'
    label: O
    start_char: 751
    end_char: 752
  - text: '•'
    label: O
    start_char: 753
    end_char: 754
  - text: 'What'
    label: O
    start_char: 755
    end_char: 759
  - text: 'are'
    label: O
    start_char: 760
    end_char: 763
  - text: 'the'
    label: O
    start_char: 764
    end_char: 767
  - text: '('
    label: O
    start_char: 768
    end_char: 769
  - text: 'dis'
    label: O
    start_char: 769
    end_char: 772
  - text: '-)'
    label: O
    start_char: 772
    end_char: 774
  - text: 'advant'
    label: O
    start_char: 774
    end_char: 780
  - text: 'ages'
    label: O
    start_char: 780
    end_char: 784
  - text: 'of'
    label: O
    start_char: 785
    end_char: 787
  - text: 'a'
    label: O
    start_char: 788
    end_char: 789
  - text: 'mixed'
    label: O
    start_char: 790
    end_char: 795
  - text: 'method'
    label: O
    start_char: 796
    end_char: 802
  - text: 'approach'
    label: O
    start_char: 803
    end_char: 811
  - text: 'to'
    label: O
    start_char: 812
    end_char: 814
  - text: 'analyse'
    label: O
    start_char: 815
    end_char: 822
  - text: 'per'
    label: O
    start_char: 823
    end_char: 826
  - text: 'i'
    label: O
    start_char: 826
    end_char: 827
  - text: '-['
    label: O
    start_char: 827
    end_char: 829
  - text: 'urban'
    label: B-LULC
    start_char: 829
    end_char: 834
  - text: ']'
    label: O
    start_char: 834
    end_char: 835
  - text: '['
    label: O
    start_char: 836
    end_char: 837
  - text: 'land'
    label: O
    start_char: 837
    end_char: 841
  - text: 'use'
    label: O
    start_char: 842
    end_char: 845
  - text: ']'
    label: O
    start_char: 845
    end_char: 846
  - text: 'patterns'
    label: O
    start_char: 847
    end_char: 855
  - text: '?'
    label: O
    start_char: 855
    end_char: 856
  - text: '','
    label: O
    start_char: 856
    end_char: 858
  - text: '{'
    label: O
    start_char: 859
    end_char: 860
  - text: '''
    label: O
    start_char: 860
    end_char: 861
  - text: 'ref'
    label: O
    start_char: 861
    end_char: 864
  - text: '':'
    label: O
    start_char: 864
    end_char: 866
  - text: '['
    label: O
    start_char: 867
    end_char: 868
  - text: '{'
    label: O
    start_char: 868
    end_char: 869
  - text: '''
    label: O
    start_char: 869
    end_char: 870
  - text: '@'
    label: O
    start_char: 870
    end_char: 871
  - text: 'type'
    label: O
    start_char: 871
    end_char: 875
  - text: '':'
    label: O
    start_char: 875
    end_char: 877
  - text: '''
    label: O
    start_char: 878
    end_char: 879
  - text: 'b'
    label: O
    start_char: 879
    end_char: 880
  - text: 'ibr'
    label: O
    start_char: 880
    end_char: 883
  - text: '','
    label: O
    start_char: 883
    end_char: 885
  - text: '''
    label: O
    start_char: 886
    end_char: 887
  - text: '@'
    label: O
    start_char: 887
    end_char: 888
  - text: 'target'
    label: O
    start_char: 888
    end_char: 894
  - text: '':'
    label: O
    start_char: 894
    end_char: 896
  - text: '''
    label: O
    start_char: 897
    end_char: 898
  - text: '#'
    label: O
    start_char: 898
    end_char: 899
  - text: 'b'
    label: O
    start_char: 899
    end_char: 900
  - text: '11'
    label: O
    start_char: 900
    end_char: 902
  - text: '','
    label: O
    start_char: 902
    end_char: 904
  - text: '''
    label: O
    start_char: 905
    end_char: 906
  - text: '#'
    label: O
    start_char: 906
    end_char: 907
  - text: 'text'
    label: O
    start_char: 907
    end_char: 911
  - text: '':'
    label: O
    start_char: 911
    end_char: 913
  - text: '''
    label: O
    start_char: 914
    end_char: 915
  - text: 'Be'
    label: O
    start_char: 915
    end_char: 917
  - text: 'au'
    label: O
    start_char: 917
    end_char: 919
  - text: 'che'
    label: O
    start_char: 919
    end_char: 922
  - text: 'min'
    label: O
    start_char: 922
    end_char: 925
  - text: '&'
    label: O
    start_char: 926
    end_char: 927
  - text: 'B'
    label: O
    start_char: 928
    end_char: 929
  - text: 'oc'
    label: O
    start_char: 929
    end_char: 931
  - text: 'qu'
    label: O
    start_char: 931
    end_char: 933
  - text: 'ier'
    label: O
    start_char: 933
    end_char: 936
  - text: ','
    label: O
    start_char: 936
    end_char: 937
  - text: '2004'
    label: B-DATE
    start_char: 938
    end_char: 942
  - text: ';'
    label: O
    start_char: 942
    end_char: 943
  - text: '''
    label: O
    start_char: 943
    end_char: 944
  - text: '},'
    label: O
    start_char: 944
    end_char: 946
  - text: '{'
    label: O
    start_char: 947
    end_char: 948
  - text: '''
    label: O
    start_char: 948
    end_char: 949
  - text: '@'
    label: O
    start_char: 949
    end_char: 950
  - text: 'type'
    label: O
    start_char: 950
    end_char: 954
  - text: '':'
    label: O
    start_char: 954
    end_char: 956
  - text: '''
    label: O
    start_char: 957
    end_char: 958
  - text: 'b'
    label: O
    start_char: 958
    end_char: 959
  - text: 'ibr'
    label: O
    start_char: 959
    end_char: 962
  - text: '','
    label: O
    start_char: 962
    end_char: 964
  - text: '''
    label: O
    start_char: 965
    end_char: 966
  - text: '@'
    label: O
    start_char: 966
    end_char: 967
  - text: 'target'
    label: O
    start_char: 967
    end_char: 973
  - text: '':'
    label: O
    start_char: 973
    end_char: 975
  - text: '''
    label: O
    start_char: 976
    end_char: 977
  - text: '#'
    label: O
    start_char: 977
    end_char: 978
  - text: 'b'
    label: O
    start_char: 978
    end_char: 979
  - text: '40'
    label: O
    start_char: 979
    end_char: 981
  - text: '','
    label: O
    start_char: 981
    end_char: 983
  - text: '''
    label: O
    start_char: 984
    end_char: 985
  - text: '#'
    label: O
    start_char: 985
    end_char: 986
  - text: 'text'
    label: O
    start_char: 986
    end_char: 990
  - text: '':'
    label: O
    start_char: 990
    end_char: 992
  - text: '''
    label: O
    start_char: 993
    end_char: 994
  - text: 'G'
    label: B-LOC
    start_char: 994
    end_char: 995
  - text: 'ough'
    label: I-LOC
    start_char: 995
    end_char: 999
  - text: '&'
    label: O
    start_char: 1000
    end_char: 1001
  - text: 'Y'
    label: O
    start_char: 1002
    end_char: 1003
  - text: 'anks'
    label: O
    start_char: 1003
    end_char: 1007
  - text: 'on'
    label: O
    start_char: 1007
    end_char: 1009
  - text: ','
    label: O
    start_char: 1009
    end_char: 1010
  - text: '2000'
    label: B-DATE
    start_char: 1011
    end_char: 1015
  - text: ';'
    label: O
    start_char: 1015
    end_char: 1016
  - text: '''
    label: O
    start_char: 1016
    end_char: 1017
  - text: '},'
    label: O
    start_char: 1017
    end_char: 1019
  - text: '{'
    label: O
    start_char: 1020
    end_char: 1021
  - text: '''
    label: O
    start_char: 1021
    end_char: 1022
  - text: '@'
    label: O
    start_char: 1022
    end_char: 1023
  - text: 'type'
    label: O
    start_char: 1023
    end_char: 1027
  - text: '':'
    label: O
    start_char: 1027
    end_char: 1029
  - text: '''
    label: O
    start_char: 1030
    end_char: 1031
  - text: 'b'
    label: O
    start_char: 1031
    end_char: 1032
  - text: 'ibr'
    label: O
    start_char: 1032
    end_char: 1035
  - text: '','
    label: O
    start_char: 1035
    end_char: 1037
  - text: '''
    label: O
    start_char: 1038
    end_char: 1039
  - text: '@'
    label: O
    start_char: 1039
    end_char: 1040
  - text: 'target'
    label: O
    start_char: 1040
    end_char: 1046
  - text: '':'
    label: O
    start_char: 1046
    end_char: 1048
  - text: '''
    label: O
    start_char: 1049
    end_char: 1050
  - text: '#'
    label: O
    start_char: 1050
    end_char: 1051
  - text: 'b'
    label: O
    start_char: 1051
    end_char: 1052
  - text: '69'
    label: O
    start_char: 1052
    end_char: 1054
  - text: '','
    label: O
    start_char: 1054
    end_char: 1056
  - text: '''
    label: O
    start_char: 1057
    end_char: 1058
  - text: '#'
    label: O
    start_char: 1058
    end_char: 1059
  - text: 'text'
    label: O
    start_char: 1059
    end_char: 1063
  - text: '':'
    label: O
    start_char: 1063
    end_char: 1065
  - text: '''
    label: O
    start_char: 1066
    end_char: 1067
  - text: 'O'
    label: O
    start_char: 1067
    end_char: 1068
  - text: 'ten'
    label: O
    start_char: 1068
    end_char: 1071
  - text: 'g'
    label: O
    start_char: 1071

In [14]:
# Save all important outputs

import os
os.makedirs("ner_output", exist_ok=True)

# 1. Model performance metrics
with open('ner_output/model_metrics.json', 'w') as f:
    json.dump(eval_results, f, indent=2)

# 2. Unique LULC terms
with open('ner_output/unique_LULC_terms.txt', 'w') as f:
    for term in unique_lulc_terms:
        f.write(f"{term}\n")

# 3. Model configuration
model_info = {
    "base_model": "roberta-base",
    "num_labels": len(label2id),
    "labels": list(label2id.keys()),
    "training_sentences": len(dataset_split['train']),
    "validation_sentences": len(dataset_split['test']),
    "performance": {
        "f1_score": eval_results['eval_f1'],
        "precision": eval_results['eval_precision'],
        "recall": eval_results['eval_recall']
    }
}

with open('ner_output/model_info.json', 'w') as f:
    json.dump(model_info, f, indent=2)

print("✓ All outputs saved to 'ner_output/' directory:")
print("  - model_metrics.json: Detailed performance metrics")
print("  - unique_lulc_terms.txt: List of all unique LULC terms found")
print("  - model_info.json: Model configuration and summary")
print(f"\n✓ Trained model saved to './final_ner_model/'")
print("\nYou can now use extract_entities() function to process any new text!")

NameError: name 'eval_results' is not defined

In [ ]:
# Read the .txt file (assuming one term per line)
with open('ner_output/unique_PROCESS_terms.txt', 'r') as f:
    file1 = set(line.strip() for line in f)  # Correctly read and strip lines from .txt

# Read the .csv file
file2 = pd.read_csv('LCprocess.csv', header=None, names=['term'])
set2 = set(file2['term'])  # Convert DataFrame column to a set

# Find unique terms in file1 (txt) not in file2 (csv)
unique_to_file1 = file1 - set2

# Find unique terms in file2 (csv) not in file1 (txt)
unique_to_file2 = set2 - file1

# Print the results
print("Unique terms in file1.txt not in file2.csv:")
print(unique_to_file1)

print("\nUnique terms in file2.csv not in file1.txt:")
print(unique_to_file2)

In [ ]:
# Read the .txt file (assuming one term per line)
with open('ner_output/unique_lulc_terms.txt', 'r') as f:
    file1 = set(line.strip() for line in f)  # Correctly read and strip lines from .txt

# Read the .csv file
file2 = pd.read_csv('LULC.csv', header=None, names=['term'])
set2 = set(file2['term'])  # Convert DataFrame column to a set

# Find unique terms in file1 (txt) not in file2 (csv)
unique_to_file1 = file1 - set2

# Find unique terms in file2 (csv) not in file1 (txt)
unique_to_file2 = set2 - file1

# Print the results
print("Unique terms in file1.txt not in file2.csv:")
print(unique_to_file1)

print("\nUnique terms in file2.csv not in file1.txt:")
print(unique_to_file2)

In [11]:
import pandas as pd

# Load CSV file
df = pd.read_csv('extracted_lulc_sentences_from_articles.csv')

# Display structure
print(f"CSV has {len(df)} rows")
print(f"Columns: {df.columns.tolist()}")
print("\nFirst few rows:")
print(df.head())

# Get first 10 sentences
first_10_sentences = df['lulc_sentence'].head(10).tolist()

# Test each sentence
print("\n🔍 Testing model on first 10 sentences:\n")
for i, sentence in enumerate(first_10_sentences, 1):
    article_id = df.iloc[i-1]['article_id']
    
    print(f"{i}. Article ID: {article_id}")
    print(f"   Sentence: {sentence}")
    
    # Extract entities
    entities = extract_entities(sentence, "./final_ner_model")
    
    if entities:
        print("   Found entities:")
        for ent in entities:
            print(f"   - '{ent['text']}' → {ent['label']}")
    else:
        print("   No entities found")
    print()

CSV has 2003 rows
Columns: ['article_id', 'lulc_sentence']

First few rows:
  article_id                                      lulc_sentence
0  Article_1  Simulation results reveal that the landscape o...
1  Article_1  The study observed a significant increase (12....
2  Article_1  On the contrary, forest cover declined drastic...
3  Article_1  Rapid population growth triggered by rural urb...
4  Article_1  Under the business as usual scenario, predicti...

🔍 Testing model on first 10 sentences:

1. Article ID: Article_1
   Sentence: Simulation results reveal that the landscape of Thimphu city has changed considerably during the study period and the change trend is predicted to continue into 2050.
   Found entities:
   - 'Thimphu' → LOC
   - 'city' → LULC
   - 'changed' → CHANGE
   - 'change' → CHANGE
   - '2050' → DATE

2. Article ID: Article_1
   Sentence: The study observed a significant increase (12.77%) in built-up area from 2002 (52.88%) to 2018 (65.5%), followed by a slight increase in the cover of bare ground.
   Found entities:
   - 'increase' → CHANGE
   - '12.77%)' → PERCENT
   - '2002' → DATE
   - '52.88%)' → PERCENT
   - '2018' → DATE
   - '65.5%),' → PERCENT
   - 'increase' → CHANGE

3. Article ID: Article_1
   Sentence: On the contrary, forest cover declined drastically (15.25%) followed by agriculture (1.01%).
   Found entities:
   - 'forest' → LULC
   - 'declined' → CHANGE
   - '15.25%)' → PERCENT
   - 'agriculture' → LULC
   - '1.01%).' → PERCENT

4. Article ID: Article_1
   Sentence: Rapid population growth triggered by rural urban migration coupled with hasty socio-economic development post democracy are the main drivers of these changes.
   Found entities:
   - 'growth' → CHANGE
   - 'urban' → LULC
   - 'drivers' → CHANGE
   - 'changes' → CHANGE

5. Article ID: Article_1
   Sentence: Under the business as usual scenario, prediction analysis for the year 2050 show that built up area will consume almost all of the city area (73.21%) with forest significantly reduced to patches making up only about 16% of the city.
   Found entities:
   - 'the year' → DATE
   - 'city' → LULC
   - '73.21%)' → PERCENT
   - 'forest' → LULC
   - 'only about 16%' → PERCENT
   - 'city' → LULC

6. Article ID: Article_1
   Sentence: Prior to this, the area was occupied by terraced agricultural fields and some 13 villages.
   Found entities:
   - 'some 13' → CARDINAL

7. Article ID: Article_1
   Sentence: Planned development for Thimphu started in 1985 with the establishment of National Urban Development Commission.
   Found entities:
   - '1985' → DATE
   - 'Urban Development' → PROCESS

8. Article ID: Article_1
   Sentence: Expansion of Thimphu city in 2002 added local areas of Lanjophaka, Heo-Samteling, Jungshi-Pamtsho, Taba and Dechencholing in the north and Changjiji, Lungtenphu, Simtokha, and Babesa in the south ( Fig.
   Found entities:
   - 'Expansion' → CHANGE
   - 'city' → LULC
   - '2002' → DATE
   - 'Lanjophaka' → LOC
   - 'Taba' → LOC
   - 'Dechencholing' → LOC
   - 'Changjiji' → LOC
   - 'Lungtenphu' → LOC

9. Article ID: Article_1
   Sentence: The period, 2002-2018 represents a rapid expansion of the city accompanied by expediated socio-economic development that led to significant changes in the city's landscape.
   Found entities:
   - '2002-2018' → COORDINATES
   - 'expansion' → CHANGE
   - 'city' → LULC
   - 'changes' → CHANGE
   - 'city' → LULC

10. Article ID: Article_1
   Sentence: The resultant improvement in basic facilities combined with creation of additional jobs further attracted more immigration from rural areas and lesser developed cities, causing a boom in real estate and informal settlements and triggering significant changes in land uses.
   Found entities:
   - 'cities' → LULC
   - 'causing' → CHANGE
   - 'changes' → CHANGE

In [33]:
# Quick diagnostic: Check if you're using the right model
def diagnose_model_issue(model_path="./final_ner_model"):
    from transformers import AutoConfig, AutoTokenizer, AutoModelForTokenClassification
    import torch
    
    # 1. Check model configuration
    config = AutoConfig.from_pretrained(model_path)
    print("🔍 MODEL DIAGNOSTIC:")
    print(f"Number of labels: {config.num_labels}")
    print(f"Label list: {config.id2label}")
    
    # Check if CARDINAL is in labels
    if 'CARDINAL' in config.id2label.values():
        print("\n❌ PROBLEM: 'CARDINAL' found in labels!")
        print("This is NOT your custom NER model - you're loading the wrong model!")
        return False
    
    # 2. Test specific tokens
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForTokenClassification.from_pretrained(model_path)
    
    # Test just "villages"
    test_text = "villages"
    inputs = tokenizer(test_text, return_tensors="pt")
    with torch.no_grad():
        outputs = model(**inputs)
        predictions = torch.argmax(outputs.logits, dim=-1)[0]
    
    label = config.id2label[predictions[1].item()]  # Token 1 should be "villages"
    print(f"\nTest prediction for 'villages': {label}")
    
    if label != "B-LULC":
        print("❌ Model doesn't recognize 'villages' as LULC!")
        print("This confirms training data has missing labels.")
    
    return True

# Run diagnostic
is_correct_model = diagnose_model_issue()

🔍 MODEL DIAGNOSTIC:
Number of labels: 21
Label list: {0: 'O', 1: 'B-CHANGE', 2: 'I-CHANGE', 3: 'B-LOC', 4: 'I-LOC', 5: 'B-LULC', 6: 'I-LULC', 7: 'B-DATE', 8: 'I-DATE', 9: 'B-PERCENT', 10: 'I-PERCENT', 11: 'B-CARDINAL', 12: 'I-CARDINAL', 13: 'B-COORDINATES', 14: 'I-COORDINATES', 15: 'B-SURFACE_UNIT', 16: 'I-SURFACE_UNIT', 17: 'B-PROCESS', 18: 'I-PROCESS', 19: 'B-QUANTITY', 20: 'I-QUANTITY'}

Test prediction for 'villages': O
❌ Model doesn't recognize 'villages' as LULC!
This confirms training data has missing labels.

In [20]:
import json
import re
from collections import Counter

# Load your training data
with open('extracted_ALL_entities_structured.json', 'r') as f:
    training_data = json.load(f)

print(f"Loaded {len(training_data)} training sentences")

# Define LULC patterns that MUST be labeled
MUST_BE_LULC = [
    # Basic land types
    r'\b(agricultural|arable)\s+(fields?|lands?|areas?|zones?)\b',
    r'\b(urban|rural|suburban|industrial)\s+(areas?|zones?|lands?|districts?)\b',
    r'\b(built-up|built up|build up)\s+(areas?|lands?|zones?)\b',
    
    
    # Specific terms
    r'\bvillages?\b',
    r'\bsettlements?\b',
    r'\btowns?\b',
    r'\bcities\b',
    r'\bfarmlands?\b',
    r'\bcroplands?\b',
    r'\bforests?\b',
    r'\bwoodlands?\b',
    r'\bgrasslands?\b',
    r'\bwetlands?\b',
    r'\bmarshlands?\b',
    r'\bswamps?\b',
    r'\bpastures?\b',
    r'\borchards?\b',
    r'\bplantations?\b',
    r'\b(paddy|rice)\s+fields?\b',
    r'\b(green|open)\s+(spaces?|areas?)\b',
    r'\bparks?\b',
    r'\bgardens?\b',
    r'\bhabitats?\b'
     r'\burned area
acacias
bare rock
shrub form
shrublands
evergreen trees
]

# Find and fix missing LULC labels
fixed_count = 0
missing_examples = []

for item in training_data:
    sentence = item['original_sentence']
    
    # Get existing LULC entities
    existing_lulc = {(e['start_char'], e['end_char']): e['text'] 
                     for e in item['entities'] if e['label'] == 'LULC'}
    
    # Check each pattern
    for pattern in MUST_BE_LULC:
        for match in re.finditer(pattern, sentence, re.IGNORECASE):
            start, end = match.span()
            matched_text = match.group()
            
            # Check if this span is already labeled
            is_labeled = any(s <= start and end <= e for s, e in existing_lulc.keys())
            
            if not is_labeled:
                # Add missing LULC entity
                item['entities'].append({
                    'text': matched_text,
                    'label': 'LULC',
                    'start_char': start,
                    'end_char': end
                })
                fixed_count += 1
                
                if len(missing_examples) < 10:
                    missing_examples.append(f"'{matched_text}' in: {sentence[:80]}...")
    
    # Sort entities by position
    item['entities'] = sorted(item['entities'], key=lambda x: x['start_char'])

print(f"\n✅ Fixed {fixed_count} missing LULC labels!")
print("\nExamples of fixed labels:")
for ex in missing_examples:
    print(f"  - {ex}")

Loaded 13660 training sentences

✅ Fixed 1596 missing LULC labels!

Examples of fixed labels:
  - 'built-up area' in: The study observed a significant increase (12.77%) in built-up area from 2002 (5...
  - 'built up area' in: Under the business as usual scenario, prediction analysis for the year 2050 show...
  - 'agricultural fields' in: Prior to this, the area was occupied by terraced agricultural fields and some 13...
  - 'villages' in: Prior to this, the area was occupied by terraced agricultural fields and some 13...
  - 'plantation' in: In addition, records of major incidents such as disasters (fire, floods), planta...
  - 'agricultural lands' in: Assuming that these probabilities | Results and discussion: | Classification acc...
  - 'built-up area' in: Using the outputs from remote sensing imagery, field surveys, and topped expert ...
  - 'rural areas' in: The resultant improvement in basic facilities combined with creation of addition...
  - 'settlements' in: The resultant improvement in basic facilities combined with creation of addition...
  - 'built-up area' in: Studies by | LULC transition between years: To deepen our understanding of the e...

In [21]:
# Check if our problematic sentence is now fixed
test_sentence = "Prior to this, the area was occupied by terraced agricultural fields and some 13 villages."

# Find this sentence in training data
found = False
for item in training_data:
    if test_sentence in item['original_sentence']:
        print(f"\nFound sentence in training data:")
        print(f"Sentence: {item['original_sentence']}")
        print(f"LULC entities:")
        for e in item['entities']:
            if e['label'] == 'LULC':
                print(f"  - '{e['text']}'")
        found = True
        break

if not found:
    print("\n⚠️ This exact sentence not in training data, but similar patterns are now fixed")

# Save corrected training data
with open('training_data_corrected.json', 'w') as f:
    json.dump(training_data, f, indent=2)
print("\n💾 Saved corrected training data to 'training_data_corrected.json'")

Found sentence in training data:
Sentence: Prior to this, the area was occupied by terraced agricultural fields and some 13 villages.
LULC entities:
  - 'agricultural fields'
  - 'villages'

💾 Saved corrected training data to 'training_data_corrected.json'

In [22]:
from transformers import AutoTokenizer, AutoModelForTokenClassification, TrainingArguments, Trainer
from datasets import Dataset
import numpy as np

# Load tokenizer and initialize new model
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

# Your label mappings (make sure these match!)
label_list = ['O', 'B-CHANGE', 'I-CHANGE', 'B-LOC', 'I-LOC', 'B-LULC', 'I-LULC', 
              'B-DATE', 'I-DATE', 'B-PERCENT', 'I-PERCENT', 'B-CARDINAL', 'I-CARDINAL',
              'B-COORDINATES', 'I-COORDINATES', 'B-SURFACE_UNIT', 'I-SURFACE_UNIT',
              'B-PROCESS', 'I-PROCESS', 'B-QUANTITY', 'I-QUANTITY']

label2id = {label: i for i, label in enumerate(label_list)}
id2label = {i: label for i, label in enumerate(label_list)}

# Initialize model
model = AutoModelForTokenClassification.from_pretrained(
    "roberta-base",
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

# Prepare dataset with corrected data
def prepare_dataset(data, tokenizer, label2id):
    def tokenize_and_align_labels(examples):
        tokenized_inputs = tokenizer(
            examples["tokens"],
            truncation=True,
            is_split_into_words=True,
            max_length=512,
            padding=True
        )
        
        labels = []
        for i, label in enumerate(examples["labels"]):
            word_ids = tokenized_inputs.word_ids(batch_index=i)
            label_ids = []
            previous_word_idx = None
            
            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)
                elif word_idx != previous_word_idx:
                    label_ids.append(label2id[label[word_idx]])
                else:
                    # For subword tokens, use the same label or -100
                    label_ids.append(label2id[label[word_idx]])
                previous_word_idx = word_idx
            
            labels.append(label_ids)
        
        tokenized_inputs["labels"] = labels
        return tokenized_inputs
    
    # Convert your data format
    processed_examples = []
    for item in data:
        # Simple tokenization for alignment
        tokens = item['original_sentence'].split()
        labels = ['O'] * len(tokens)
        
        # Apply entity labels
        for entity in item['entities']:
            # Find which tokens this entity spans
            # (This is simplified - you may need more sophisticated alignment)
            entity_text = entity['text']
            entity_label = entity['label']
            
            # Add proper B- and I- prefixes
            # ... (implement proper token-label alignment)
        
        processed_examples.append({
            'tokens': tokens,
            'labels': labels
        })
    
    # Create dataset
    dataset = Dataset.from_list(processed_examples)
    tokenized_dataset = dataset.map(
        lambda x: tokenize_and_align_labels(x),
        batched=True
    )
    
    return tokenized_dataset

# Prepare corrected dataset
print("Preparing dataset with corrected labels...")
dataset = prepare_dataset_enhanced(raw_data, tokenizer, label2id)
train_test = dataset.train_test_split(test_size=0.1)

# Training arguments
training_args = TrainingArguments(
    output_dir="./roberta-ner-corrected",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=5,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    push_to_hub=False,
    report_to="none",
)

# Create trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_test["train"],
    eval_dataset=train_test["test"],
    tokenizer=tokenizer,
    data_collator=DataCollatorForTokenClassification(tokenizer),
)

# Train!
print("\n🚀 Starting training with corrected labels...")
trainer.train()

# Save the fixed model
trainer.save_model("./final_ner_model_corrected")
print("\n✅ Model retrained and saved to './final_ner_model_corrected'")

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Preparing dataset with corrected labels...

Map:   0%|          | 0/13660 [00:00<?, ? examples/s]

AssertionError: You need to instantiate RobertaTokenizerFast with add_prefix_space=True to use it with pretokenized inputs.

In [11]:
import pandas as pd
import json
from transformers import pipeline
import os
import xml.sax.saxutils

# Load your CSV file
print("📂 Loading CSV file...")
csv_file = 'annotated_corpus_for_dataverse.csv'  # Update with your file path
df = pd.read_csv(csv_file)

# Filter for rows where relevance_label is not 'zero' (optional)
print("🔍 Filtering data...")
filtered_df = df[df['relevance_label'] != 0].copy()
print(f"✅ Filtered to {len(filtered_df)} rows")

# Load your NER model
ner_pipeline = pipeline(
    "ner",
    model="./final_ner_model",  # Update with your model path
    tokenizer="./final_ner_model",
    aggregation_strategy="simple"  # Groups sub-word tokens
)

def create_label_studio_config(all_labels, output_dir):
    """Create Label Studio config XML file"""
    
    colors = [
        "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FECA57", 
        "#FF9FF3", "#A55EEA", "#54A0FF", "#5F27CD", "#00D2D3",
        "#FF9F43", "#10AC84", "#EE5A24", "#0098C7", "#8395A7"
    ]
    
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    config_path = os.path.join(output_dir, "ner_label_studio_config.xml")
    
    # Build entity labels
    entity_labels = ""
    for i, label in enumerate(sorted(all_labels)):
        color = colors[i % len(colors)]
        # Escape XML special characters
        safe_label = xml.sax.saxutils.escape(label)
        entity_labels += f'    <Label value="{safe_label}" background="{color}"/>\n'
    
    # Build complete XML config
    label_studio_config = f"""<View>
  <Text name="text" value="$text"/>
  <Labels name="label" toName="text">
{entity_labels}  </Labels>
</View>"""
    
    # Write the file
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(label_studio_config)
    
    print(f"✅ Label Studio config saved to: {config_path}")
    return config_path

# Process each text_segment
label_studio_data = []
all_unique_labels = set()
annotation_id_counter = 1

print("\n📊 Processing texts and extracting entities...")

for index, row in filtered_df.iterrows():
    text = row['text_segment']
    article_id = row['id_segment']
    
    print(f"\nProcessing ID: {article_id}")
    print(f"Text preview: {text[:100]}...")
    
    # Extract entities using your model
    entities = ner_pipeline(text)
    
    # Build result array for this text
    results = []
    entity_counter = 0
    
    for entity in entities:
        # Skip 'O' labels
        if entity.get('entity_group', entity.get('entity', '')).endswith('-O'):
            continue
        
        # Extract clean label (remove B-, I- prefixes)
        label = entity.get('entity_group', entity.get('entity', '')).replace('B-', '').replace('I-', '')
        
        # Add to unique labels set
        all_unique_labels.add(label)
        
        # Create entity result
        result = {
            "id": f"entity_{entity_counter}",
            "type": "labels",
            "value": {
                "start": entity['start'],
                "end": entity['end'],
                "text": text[entity['start']:entity['end']],
                "labels": [label]
            },
            "from_name": "label",
            "to_name": "text"
        }
        results.append(result)
        entity_counter += 1
    
    # Create the task in Label Studio format
    task = {
        "data": {
            "text": text,
            "article_id": article_id  # Keep original ID for reference
        }
    }
    
    # Add annotations only if entities were found
    if results:
        task["annotations"] = [{
            "id": annotation_id_counter,
            "result": results
        }]
        annotation_id_counter += 1
    
    label_studio_data.append(task)
    
    # Print extracted entities for verification
    if results:
        print(f"Found {len(results)} entities:")
        for result in results[:5]:  # Show first 5
            print(f"  - '{result['value']['text']}' → {result['value']['labels'][0]}")
        if len(results) > 5:
            print(f"  ... and {len(results) - 5} more")
    else:
        print("No entities found")

# Create output directory
output_dir = "label_studio_output"
os.makedirs(output_dir, exist_ok=True)

# Save as Label Studio JSON format
output_file = os.path.join(output_dir, 'label_studio_ner_tasks.json')
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(label_studio_data, f, indent=2, ensure_ascii=False)

# Generate Label Studio config file
if all_unique_labels:
    config_file = create_label_studio_config(all_unique_labels, output_dir)
else:
    print("⚠️ No labels found to generate config")

print(f"\n✅ Processing complete!")
print(f"📄 Results saved to: {output_file}")
print(f"📊 Total tasks: {len(label_studio_data)}")

# Print summary statistics
total_entities = sum(len(task.get('annotations', [{}])[0].get('result', [])) 
                    for task in label_studio_data if 'annotations' in task)
print(f"🏷️ Total entities extracted: {total_entities}")
print(f"🏷️ Unique labels found: {sorted(all_unique_labels)}")

print("\n📝 To import in Label Studio:")
print("1. Create a new project in Label Studio")
print(f"2. Go to Settings > Labeling Interface > Code")
print(f"3. Paste the content from: {output_dir}/ner_label_studio_config.xml")
print(f"4. Go to Import and upload: {output_file}")

# Show sample of output format
print("\n📋 Sample output format:")
if label_studio_data:
    print(json.dumps(label_studio_data[0], indent=2)[:500] + "...")

📂 Loading CSV file...
🔍 Filtering data...
✅ Filtered to 233 rows

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

📊 Processing texts and extracting entities...

Processing ID: 1-s2.0-S0303243414001718-main_19b
Text preview: #text': 'After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was ...
Found 2 entities:
  - 'the 1970s and 1980s' → DATE
  - 'loss' → CHANGE

Processing ID: 1-s2.0-S095937809800003X-main_75b
Text preview: #text': 'Pastoral production has often existed in some sort of symbiotic interaction with the [agric...
Found 1 entities:
  - 'agriculture' → LULC

Processing ID: 1-s2.0-S0006320709005400-main_16b
Text preview: #text': 'The forests of West and Central Africa probably originally covered a combined area of about...
Found 5 entities:
  - 'forests' → LULC
  - 'West' → LOC
  - 'Central Africa' → LOC
  - 'area of about 3 million km' → SURFACE_UNIT
  - '2' → CARDINAL

Processing ID: 1-s2.0-S095937809800003X-main_8
Text preview: (1993)'}], '#text': "An increase of land under [cultivation] can be in the form of either (a) cleari...
Found 4 entities:
  - '1993' → DATE
  - 'increase' → CHANGE
  - 'cultivation' → PROCESS
  - 'cultivation' → PROCESS

Processing ID: 1-s2.0-S0304387816300670-main_75
Text preview: (2006), who estimate an increase in the national [urban] share of 0.45 percent with a reduction in n...
Found 6 entities:
  - '2006' → DATE
  - 'increase' → CHANGE
  - 'urban' → LULC
  - '0.45 percent' → PERCENT
  - 'reduction' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S0140196322000143-main_121
Text preview: ).'}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': {'@n': '4.2.', '#text': '[Land use ]change...
Found 9 entities:
  - '4.2' → CARDINAL
  - 'change' → CHANGE
  - '1996 to 2017' → DATE
  - 'increased' → CHANGE
  - '40% to 51.3%' → PERCENT
  ... and 4 more

Processing ID: 1-s2.0-S0264837715302131-main_119
Text preview: [Agriculture] in this region has been dominated over the past three decades by [cotton] production...
Found 3 entities:
  - 'Agriculture' → LULC
  - 'the past three decades' → DATE
  - 'cotton' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_76
Text preview: [Forest] land was decreased nearly by half in 2002 compared to its coverage in 1984, while the size ...
Found 7 entities:
  - 'Forest' → LULC
  - 'decreased' → CHANGE
  - 'half' → CARDINAL
  - '2002' → DATE
  - '1984' → DATE
  ... and 2 more

Processing ID: 1-s2.0-S0264837715302131-main_147
Text preview: About 26 and 31% of the total area of natural vegetation ([forest], woodland and tree [savanna]) wil...
Found 11 entities:
  - '26' → CARDINAL
  - '31%' → PERCENT
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  ... and 6 more

Processing ID: 1-s2.0-S0006320709005400-main_198
Text preview: Although such schemes clearly have the potential to benefit biodiversity and the wider environment, ...
Found 14 entities:
  - '4.3' → CARDINAL
  - '1' → CARDINAL
  - '2007' → DATE
  - '2006' → DATE
  - '2000' → DATE
  ... and 9 more

Processing ID: 1-s2.0-S0140196322000143-main_99
Text preview: Another variance analysis using GLM was conducted for the variable means of all recorded trees and [...
Found 4 entities:
  - 'trees' → LULC
  - 'shrubs' → LULC
  - 'trees' → LULC
  - 'shrubs' → LULC

Processing ID: 1-s2.0-S0264837715302131-main_103
Text preview: Assuming the dynamics recorded in the second period , the amounts of land covered by [forest], woodl...
Found 11 entities:
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  - 'decrease' → CHANGE
  - '5, 9' → COORDINATES
  ... and 6 more

Processing ID: 1-s2.0-S0140196310000893-main_115
Text preview: Conversely the decrease in the herbaceous standing [crop], due to the shortening of the [fallow] per...
Found 3 entities:
  - 'decrease' → CHANGE
  - 'crop' → LULC
  - 'fallow' → LULC

Processing ID: 1-s2.0-S0169204617300270-main_221
Text preview: Coping capacities were therefore assumed to be lower for the Bolgatanga area, which could lead to lo...
Found 11 entities:
  - 'Bolgatanga' → LOC
  - 'urban' → LULC
  - 'agriculture' → LULC
  - '3.2' → CARDINAL
  - 'Dri' → CHANGE
  ... and 6 more

Processing ID: 1-s2.0-S030438781000043X-mainext_317
Text preview: describes Rwandan [agriculture] as caught in a "low investment trap"; less than 10% of cropland is i...
Found 4 entities:
  - 'Rwandan' → LOC
  - 'agriculture' → LULC
  - 'less than 10%' → PERCENT
  - 'cropland' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_41
Text preview: Due to the weeding practice, [bare soil] dominates in cropped fields in the early growing season whi...
Found 4 entities:
  - 'bare soil' → LULC
  - 'early growing season' → DATE
  - 'grow' → CHANGE
  - 'fallows' → LULC

Processing ID: 1-s2.0-S0301479717300713-main_223
Text preview: From the expert interviews, we learned that migration is a driver and a consequence of [LULCC] and p...
Found 2 entities:
  - 'driver' → CHANGE
  - 'driver' → CHANGE

Processing ID: 1-s2.0-S016788090800131X-main_82
Text preview: In 1986, the grazing land had much higher proportion of the total regional area than other [land use...
Found 3 entities:
  - '1986' → DATE
  - 'croplands' → LULC
  - '16 years' → DATE

Processing ID: 1-s2.0-S0264837715302131-main_74
Text preview: In 1990, woodland and tree [savanna] were still the dominant [land cover] types...
Found 3 entities:
  - '1990' → DATE
  - 'tree' → LULC
  - 'savanna' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_4
Text preview: In fact, some NTFP-providing trees, such as the baobab (Adansonia digitata) and the shea tree (Vitel...
Found 4 entities:
  - 'trees' → LULC
  - 'tree' → LULC
  - 'cultivation' → PROCESS
  - 'fallows' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_563a
Text preview: In his study of the ICRISAT villages, he argues that, except in Sayero, all "have passed or are appr...
Found 1 entities:
  - 'fallow' → LULC

Processing ID: 1-s2.0-S0140196313000608-main_75
Text preview: In northern Burkina Faso, temporary migration is also one of the diversification strategies observed...
Found 15 entities:
  - 'Burkina Faso' → LOC
  - '2.5' → CARDINAL
  - '1994' → DATE
  - '2009' → DATE
  - '1988' → DATE
  ... and 10 more

Processing ID: 1-s2.0-S0140196322000143-main_273
Text preview: In rangelands, the main cause of woody vegetation decrease is the increasing pressure on wood resour...
Found 7 entities:
  - 'cause' → CHANGE
  - 'decrease' → CHANGE
  - 'increasing' → CHANGE
  - 'growing' → CHANGE
  - 'urban' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S0140196313000608-main_184
Text preview: In Saloum Senegal, with the increase of cultivated land and shortening of [fallow] cycles, soils hav...
Found 6 entities:
  - 'Saloum' → LOC
  - 'Senegal' → LOC
  - 'increase' → CHANGE
  - 'fallow' → LULC
  - 'fallow' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0169204617300270-main_293
Text preview: In the case of Ghana, that statement might be true for Kumasi as expanding [city] in the hinterlands...
Found 4 entities:
  - 'Ghana' → LOC
  - 'expanding' → CHANGE
  - 'city' → LULC
  - 'Bolgatanga' → LOC

Processing ID: 1-s2.0-S0301479717300713-main_147
Text preview: In the past, missing or low fertilizer input was compensated by the [crop]-[fallow] practice, but la...
Found 5 entities:
  - 'crop' → LULC
  - 'fallow' → LULC
  - 'growth' → CHANGE
  - 'cultivation' → PROCESS
  - 'crops' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_77
Text preview: In Yale ´, the size of [crop] and grazing lands increased by 9 and 18% in 2002 compared to the sizes...
Found 10 entities:
  - 'crop' → LULC
  - 'increased' → CHANGE
  - '9' → CARDINAL
  - '18%' → PERCENT
  - '2002' → DATE
  ... and 5 more

Processing ID: 1-s2.0-S0169204617300270-main_289
Text preview: Ineffective [land use] planning can contribute to an increase in land fragmentation resulting in los...
Found 2 entities:
  - 'increase' → CHANGE
  - 'loss' → CHANGE

Processing ID: 1-s2.0-S0301479717300713-main_227
Text preview: Interviews and literature review showed that biophysical factors as drivers of [LULCC] were frequent...
Found 2 entities:
  - 'drivers' → CHANGE
  - 'drivers' → CHANGE

Processing ID: 1-s2.0-S0301479717300713-main_134
Text preview: Irrigation from rivers is regarded as minor driver of [LULCC]...
Found 1 entities:
  - 'driver' → CHANGE

Processing ID: 1-s2.0-S0168192311001122-main_23
Text preview: It is well known that the availability of [fallow] land and hence the duration of [fallow] periods d...
Found 4 entities:
  - 'fallow' → LULC
  - 'fallow' → LULC
  - 'decrease' → CHANGE
  - 'increasing' → CHANGE

Processing ID: 1-s2.0-S0303243414001718-main_190
Text preview: On the one hand, the shallow soils were not able to temper droughts, leading to a massive dying of t...
Found 2 entities:
  - 'trees' → LULC
  - 'shrubs' → LULC

Processing ID: 1-s2.0-S0303243414001718-main_164
Text preview: On the one hand, tree growth and [agroforestry] on fields have led to an increase of woody cover in ...
Found 4 entities:
  - 'tree' → LULC
  - 'growth' → CHANGE
  - 'agroforestry' → LULC
  - 'increase' → CHANGE

Processing ID: 1-s2.0-S0301479717300713-main_235
Text preview: One explanation could be the indistinct influence of indirect drivers on [LULCC], for example, chang...
Found 2 entities:
  - 'drivers' → CHANGE
  - 'changes' → CHANGE

Processing ID: 1-s2.0-S0006320709005400-main_54
Text preview: One of the fundamental factors has been demographic growth and the growth in [urban] food demands...
Found 3 entities:
  - 'growth' → CHANGE
  - 'growth' → CHANGE
  - 'urban' → LULC

Processing ID: 1-s2.0-S0140196313000608-main_210
Text preview: Other areas have experienced a decrease in [crop] land despite a population increase...
Found 3 entities:
  - 'decrease' → CHANGE
  - 'crop' → LULC
  - 'increase' → CHANGE

Processing ID: 1-s2.0-S0301479717300713-main_321
Text preview: P9: We know that [urbanisation] is coming, it\'s growing...
Found 2 entities:
  - 'urbanisation' → PROCESS
  - 'growing' → CHANGE

Processing ID: 1-s2.0-S0140196322000143-main_50
Text preview: Rangelands are grazed year-round under communal access but grazing also extends to fallows, year-rou...
Found 5 entities:
  - 'year-round' → DATE
  - 'fallows' → LULC
  - 'year-round' → DATE
  - 'the dry season' → DATE
  - 'crop' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_563b
Text preview: Ratios of [fallow] to cultivated area are 0.8 in Woure, where the bushfallow system is "already defu...
Found 12 entities:
  - 'fallow' → LULC
  - '0.8' → CARDINAL
  - 'Woure' → LOC
  - 'ow' → LULC
  - '1.6' → CARDINAL
  ... and 7 more

Processing ID: 1-s2.0-S0140196314000536-main_305
Text preview: Regular [cultivation] keeps the soil penetrable and farmers are aware of the benefits of trees in th...
Found 2 entities:
  - 'cultivation' → PROCESS
  - 'trees' → LULC

Processing ID: 1-s2.0-S095937809800003X-main_159
Text preview: Secondary crops are cowpeas, [groundnuts], sorrel, and okra...
Found 3 entities:
  - 'crops' → LULC
  - 'groundnuts' → LULC
  - 'okra' → LOC

Processing ID: 1-s2.0-S0140196314000536-main_330
Text preview: Since the 1960s, the natural vegetation has been completely transformed and today many trees and [sh...
Found 5 entities:
  - 'the 1960s' → DATE
  - 'transformed' → CHANGE
  - 'today' → DATE
  - 'trees' → LULC
  - 'shrubs' → LULC

Processing ID: 1-s2.0-S0303243414001718-main_117
Text preview: Site visits provided information on [land cover] and land use, woody species composition, tree heigh...
Found 2 entities:
  - 'tree' → LULC
  - 'processes' → PROCESS

Processing ID: 1-s2.0-S0140196313000608-main_242
Text preview: Some publications describe several case studies when [crop] land trends are described in different g...
Found 29 entities:
  - 'crop' → LULC
  - '2' → CARDINAL
  - 'Crop' → LULC
  - 'change' → CHANGE
  - 'Drivers' → CHANGE
  ... and 24 more

Processing ID: 1-s2.0-S003442571730041X-main_19
Text preview: Still at present, little scientific empirical evidence for the link between NDVI trends and cropland...
Found 16 entities:
  - 'cropland' → LULC
  - 'changes' → CHANGE
  - '2013' → DATE
  - 'Bégué' → LOC
  - '2011' → DATE
  ... and 11 more

Processing ID: 1-s2.0-S0301479717300713-main_504
Text preview: Temperature variability P3: So it has the potential to lead to [desertification] because the tempera...
No entities found

Processing ID: 1-s2.0-S016788090800131X-main_81
Text preview: The actual size and proportion of the different [land use] types changed during the study period...
Found 1 entities:
  - 'changed' → CHANGE

Processing ID: 1-s2.0-S0006320709005400-main_5
Text preview: The available evidence suggests that [forest] loss and degradation has been caused primarily by agri...
Found 4 entities:
  - 'forest' → LULC
  - 'loss' → CHANGE
  - 'caused' → CHANGE
  - 'expansion' → CHANGE

Processing ID: 1-s2.0-S0304387816300670-main_610
Text preview: The dependent variable is growth in the [urbanization] rate...
Found 2 entities:
  - 'growth' → CHANGE
  - 'urbanization' → PROCESS

Processing ID: 1-s2.0-S095937809800003X-main_120
Text preview: The majority (94%) of the households keep livestock which plays an important role as a saving and se...
Found 3 entities:
  - '94' → PERCENT
  - 'years' → DATE
  - 'crop' → LULC

Processing ID: 1-s2.0-S0140196322000143-main_262
Text preview: The plots were only cropped one year and with little success, after which irreversible soil [erosion...
Found 1 entities:
  - 'one year' → DATE

Processing ID: 1-s2.0-S0140196313000608-main_166
Text preview: The reasons for the decline described by the authors are droughts and declining rainfall in the past...
Found 5 entities:
  - 'decline' → CHANGE
  - 'declining' → CHANGE
  - 'the past 30 years' → DATE
  - 'cultivation' → PROCESS
  - 'crops' → LULC

Processing ID: 1-s2.0-S000632071100245X-main_231
Text preview: The shortening of [fallow] periods may hamper a successful establishment of A...
Found 1 entities:
  - 'fallow' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_430
Text preview: The vulnerability of [fallow] investment to insecurity makes the link particularly strong here...
Found 1 entities:
  - 'fallow' → LULC

Processing ID: 1-s2.0-S0169204617300270-main_253
Text preview: Therefore, infrastructural development (excluding [roads]) has a very low confidence level as a driv...
Found 6 entities:
  - 'driver' → CHANGE
  - 'urban' → LULC
  - '2010' → DATE
  - '2009' → DATE
  - '2012' → DATE
  ... and 1 more

Processing ID: 1-s2.0-S0169204617300270-main_205
Text preview: These change rates together with the decreasing average SU size (Table ) indicate that [urban] expan...
Found 7 entities:
  - 'change' → CHANGE
  - 'decreasing' → CHANGE
  - 'urban' → LULC
  - 'expansion' → CHANGE
  - 'urban' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S095937809800003X-main_240
Text preview: Thus, changes in [land use] strategies result not only in a simple expansion of fields to new and le...
Found 2 entities:
  - 'changes' → CHANGE
  - 'expansion' → CHANGE

Processing ID: 1-s2.0-S030438781000043X-mainext_563c
Text preview: Thus, he argues that secure rights: have value in those villages other than Sayero where shifting [c...
Found 4 entities:
  - 'shifting' → CHANGE
  - 'cultivation' → PROCESS
  - 'grass' → LULC
  - 'fallow' → LULC

Processing ID: 1-s2.0-S095937809800003X-main_151
Text preview: Thus, the coherence between spatially related socio-economic characteristics of the households, agri...
Found 3 entities:
  - 'Yomboli' → LOC
  - 'four' → CARDINAL
  - 'mare' → LULC

Processing ID: 1-s2.0-S0303243414001718-main_43
Text preview: To investigate and quantify [land cover] changes over 44 years including aspects of degradation and ...
Found 3 entities:
  - 'changes' → CHANGE
  - '44 years' → DATE
  - 'expansion' → CHANGE

Processing ID: 1-s2.0-S0301479717300713-main_155
Text preview: Today, these areas are free from diseases and are, therefore, threatened by [agriculture]...
Found 1 entities:
  - 'agriculture' → LULC

Processing ID: 1-s2.0-S0006320709005400-main_158
Text preview: Tree cover, in both dense [forest] and the agricultural mosaics, is lost as a result...
Found 1 entities:
  - 'forest' → LULC

Processing ID: 1-s2.0-S0301479717300713-main_558
Text preview: Usually, it's the people who are in the [urban] areas who do this vegetable production...
Found 2 entities:
  - 'urban' → LULC
  - 'vegetable' → LULC

Processing ID: 1-s2.0-S0304387816300670-main_452
Text preview: We then turn to evidence on the migration channel itself.'}}, {'@xmlns': 'http://www.tei-c.org/ns/1....
Found 4 entities:
  - '7.1' → CARDINAL
  - '26' → CARDINAL
  - '1' → CARDINAL
  - 'urbanization' → PROCESS

Processing ID: 1-s2.0-S003442571730041X-main_192
Text preview: Whereas most [shrubs] are annually coppiced in fields prior to [cultivation], they are left to grow ...
Found 6 entities:
  - 'shrubs' → LULC
  - 'annually' → DATE
  - 'cultivation' → PROCESS
  - 'grow' → CHANGE
  - 'fallowed fields' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0304387816300670-main_112
Text preview: (2004)'}], '#text': 'With regard to population growth, the literature analysis revealed that only ru...
Found 7 entities:
  - '2004' → DATE
  - 'growth' → CHANGE
  - 'growth' → CHANGE
  - 'driver' → CHANGE
  - 'urban' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S0264837715302131-main_8
Text preview: Falling precipitation and rising temperatures would likely worsen agricultural growing conditions in...
Found 5 entities:
  - 'growing' → CHANGE
  - 'Africa' → LOC
  - 'West Africa' → LOC
  - 'Southern Africa' → LOC
  - '7' → CARDINAL

Processing ID: 1-s2.0-S016788090800131X-main_101
Text preview: The population density has increased during the past decades, which has had a significant impact on ...
Found 3 entities:
  - 'increased' → CHANGE
  - 'the past decades' → DATE
  - 'impact' → CHANGE

Processing ID: 1-s2.0-S0308521X12000157-main_49
Text preview: #text': '[Land use] and [land cover] in West African savannas are mainly driven by population pressu...
Found 5 entities:
  - 'West African' → LOC
  - 'savannas' → LULC
  - 'driven' → CHANGE
  - 'drivers' → CHANGE
  - 'road' → LULC

Processing ID: 1-s2.0-S0301479717300713-main_182
Text preview: Furthermore, the general infrastructural develop-ment of electricity and hospitals, for example, as ...
Found 2 entities:
  - 'drivers' → CHANGE
  - 'urban' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_692
Text preview: Conversely, climate change as one of the emerging drivers of [LULCC] is difficult to detect and quan...
Found 3 entities:
  - 'change' → CHANGE
  - 'one' → CARDINAL
  - 'drivers' → CHANGE

Processing ID: 1-s2.0-S0140196310000893-main_18a
Text preview: Furthermore, issues such as state politics, market incentives, climate variations, and access to lan...
Found 9 entities:
  - 'water' → LULC
  - 'change' → CHANGE
  - 'er' → LOC
  - '1993' → DATE
  - '1998' → DATE
  ... and 4 more

Processing ID: 1-s2.0-S235198941500102X-main_247
Text preview: P6: From my perspective, the [[land use]] aspect that is degrading the land is including the fire … ...
Found 1 entities:
  - 'tree' → LULC

Processing ID: 1-s2.0-S0140196322000143-main_275
Text preview: As quoted by the higher the [[land use]] intensity, the lower the fire frequency: indeed our results...
Found 1 entities:
  - 'agriculture' → LULC

Processing ID: 1-s2.0-S0304387816300670-main_107a
Text preview: However, diverging expert statements were made on bush fires as driver of [LULCC] (mentioned by 62%)...
Found 2 entities:
  - 'driver' → CHANGE
  - '62' → PERCENT

Processing ID: 1-s2.0-S0006320709005400-main_61
Text preview: As expected, plant species statistically linked with frequent fire landscape units are typical of su...
Found 2 entities:
  - 'savanna' → LULC
  - 'savannas' → LULC

Processing ID: 1-s2.0-S0303243414001718-main_54
Text preview: The interrelations between [savanna] fire regimes and vegetation dynamics are indeed complex; they a...
Found 9 entities:
  - 'savanna' → LULC
  - '2008' → DATE
  - '2006' → DATE
  - '2003' → DATE
  - '2007' → DATE

In [12]:
import pandas as pd
import json
from transformers import pipeline
import os
import xml.sax.saxutils

# Load your CSV file
print("📂 Loading CSV file...")
csv_file = 'annotated_corpus_for_dataverse.csv'  # Update with your file path
df = pd.read_csv(csv_file)

# Filter for rows where relevance_label is not 'zero' (optional)
print("🔍 Filtering data...")
filtered_df = df[df['relevance_label'] == 2].copy()
print(f"✅ Filtered to {len(filtered_df)} rows")

# Load your NER model
ner_pipeline = pipeline(
    "ner",
    model="./final_ner_model",  # Update with your model path
    tokenizer="./final_ner_model",
    aggregation_strategy="simple"  # Groups sub-word tokens
)

def create_label_studio_config(all_labels, output_dir):
    """Create Label Studio config XML file"""
    
    colors = [
        "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FECA57", 
        "#FF9FF3", "#A55EEA", "#54A0FF", "#5F27CD", "#00D2D3",
        "#FF9F43", "#10AC84", "#EE5A24", "#0098C7", "#8395A7"
    ]
    
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    config_path = os.path.join(output_dir, "ner_label_studio_config.xml")
    
    # Build entity labels
    entity_labels = ""
    for i, label in enumerate(sorted(all_labels)):
        color = colors[i % len(colors)]
        # Escape XML special characters
        safe_label = xml.sax.saxutils.escape(label)
        entity_labels += f'    <Label value="{safe_label}" background="{color}"/>\n'
    
    # Build complete XML config
    label_studio_config = f"""<View>
  <Text name="text" value="$text"/>
  <Labels name="label" toName="text">
{entity_labels}  </Labels>
</View>"""
    
    # Write the file
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(label_studio_config)
    
    print(f"✅ Label Studio config saved to: {config_path}")
    return config_path

# Process each text_segment
label_studio_data = []
all_unique_labels = set()
annotation_id_counter = 1

print("\n📊 Processing texts and extracting entities...")

for index, row in filtered_df.iterrows():
    text = row['text_segment']
    article_id = row['id_segment']
    
    print(f"\nProcessing ID: {article_id}")
    print(f"Text preview: {text[:100]}...")
    
    # Extract entities using your model
    entities = ner_pipeline(text)
    
    # Build result array for this text
    results = []
    entity_counter = 0
    
    for entity in entities:
        # Skip 'O' labels
        if entity.get('entity_group', entity.get('entity', '')).endswith('-O'):
            continue
        
        # Extract clean label (remove B-, I- prefixes)
        label = entity.get('entity_group', entity.get('entity', '')).replace('B-', '').replace('I-', '')
        
        # Add to unique labels set
        all_unique_labels.add(label)
        
        # Create entity result (simplified without from_name and to_name)
        result = {
            "id": f"entity_{entity_counter}",
            "type": "labels",
            "value": {
                "start": entity['start'],
                "end": entity['end'],
                "text": text[entity['start']:entity['end']],
                "labels": [label]
            }
        }
        results.append(result)
        entity_counter += 1
    
    # Create the task in Label Studio format
    task = {
        "data": {
            "text": text,
            "article_id": article_id  # Keep original ID for reference
        }
    }
    
    # Add annotations only if entities were found
    if results:
        task["annotations"] = [{
            "id": annotation_id_counter,
            "result": results
        }]
        annotation_id_counter += 1
    
    label_studio_data.append(task)
    
    # Print extracted entities for verification
    if results:
        print(f"Found {len(results)} entities:")
        for result in results[:5]:  # Show first 5
            print(f"  - '{result['value']['text']}' → {result['value']['labels'][0]}")
        if len(results) > 5:
            print(f"  ... and {len(results) - 5} more")
    else:
        print("No entities found")

# Create output directory
output_dir = "label_studio_output"
os.makedirs(output_dir, exist_ok=True)

# Save as Label Studio JSON format
output_file = os.path.join(output_dir, 'label_studio_ner_tasks.json')
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(label_studio_data, f, indent=2, ensure_ascii=False)

# Generate Label Studio config file
if all_unique_labels:
    config_file = create_label_studio_config(all_unique_labels, output_dir)
else:
    print("⚠️ No labels found to generate config")

print(f"\n✅ Processing complete!")
print(f"📄 Results saved to: {output_file}")
print(f"📊 Total tasks: {len(label_studio_data)}")

# Print summary statistics
total_entities = sum(len(task.get('annotations', [{}])[0].get('result', [])) 
                    for task in label_studio_data if 'annotations' in task)
print(f"🏷️ Total entities extracted: {total_entities}")
print(f"🏷️ Unique labels found: {sorted(all_unique_labels)}")

print("\n📝 To import in Label Studio:")
print("1. Create a new project in Label Studio")
print(f"2. Go to Settings > Labeling Interface > Code")
print(f"3. Paste the content from: {output_dir}/ner_label_studio_config.xml")
print(f"4. Go to Import and upload: {output_file}")

# Show sample of output format
print("\n📋 Sample output format:")
if label_studio_data:
    print(json.dumps(label_studio_data[0], indent=2)[:500] + "...")

📂 Loading CSV file...
🔍 Filtering data...
✅ Filtered to 67 rows

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

📊 Processing texts and extracting entities...

Processing ID: 1-s2.0-S0303243414001718-main_19b
Text preview: #text': 'After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was ...
Found 2 entities:
  - 'the 1970s and 1980s' → DATE
  - 'loss' → CHANGE

Processing ID: 1-s2.0-S0006320709005400-main_16b
Text preview: #text': 'The forests of West and Central Africa probably originally covered a combined area of about...
Found 5 entities:
  - 'forests' → LULC
  - 'West' → LOC
  - 'Central Africa' → LOC
  - 'area of about 3 million km' → SURFACE_UNIT
  - '2' → CARDINAL

Processing ID: 1-s2.0-S0140196322000143-main_121
Text preview: ).'}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': {'@n': '4.2.', '#text': '[Land use ]change...
Found 9 entities:
  - '4.2' → CARDINAL
  - 'change' → CHANGE
  - '1996 to 2017' → DATE
  - 'increased' → CHANGE
  - '40% to 51.3%' → PERCENT
  ... and 4 more

Processing ID: 1-s2.0-S0264837715302131-main_119
Text preview: [Agriculture] in this region has been dominated over the past three decades by [cotton] production...
Found 3 entities:
  - 'Agriculture' → LULC
  - 'the past three decades' → DATE
  - 'cotton' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_76
Text preview: [Forest] land was decreased nearly by half in 2002 compared to its coverage in 1984, while the size ...
Found 7 entities:
  - 'Forest' → LULC
  - 'decreased' → CHANGE
  - 'half' → CARDINAL
  - '2002' → DATE
  - '1984' → DATE
  ... and 2 more

Processing ID: 1-s2.0-S0264837715302131-main_147
Text preview: About 26 and 31% of the total area of natural vegetation ([forest], woodland and tree [savanna]) wil...
Found 11 entities:
  - '26' → CARDINAL
  - '31%' → PERCENT
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  ... and 6 more

Processing ID: 1-s2.0-S0264837715302131-main_103
Text preview: Assuming the dynamics recorded in the second period , the amounts of land covered by [forest], woodl...
Found 11 entities:
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  - 'decrease' → CHANGE
  - '5, 9' → COORDINATES
  ... and 6 more

Processing ID: 1-s2.0-S0140196310000893-main_115
Text preview: Conversely the decrease in the herbaceous standing [crop], due to the shortening of the [fallow] per...
Found 3 entities:
  - 'decrease' → CHANGE
  - 'crop' → LULC
  - 'fallow' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_317
Text preview: describes Rwandan [agriculture] as caught in a "low investment trap"; less than 10% of cropland is i...
Found 4 entities:
  - 'Rwandan' → LOC
  - 'agriculture' → LULC
  - 'less than 10%' → PERCENT
  - 'cropland' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_41
Text preview: Due to the weeding practice, [bare soil] dominates in cropped fields in the early growing season whi...
Found 4 entities:
  - 'bare soil' → LULC
  - 'early growing season' → DATE
  - 'grow' → CHANGE
  - 'fallows' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_82
Text preview: In 1986, the grazing land had much higher proportion of the total regional area than other [land use...
Found 3 entities:
  - '1986' → DATE
  - 'croplands' → LULC
  - '16 years' → DATE

Processing ID: 1-s2.0-S0264837715302131-main_74
Text preview: In 1990, woodland and tree [savanna] were still the dominant [land cover] types...
Found 3 entities:
  - '1990' → DATE
  - 'tree' → LULC
  - 'savanna' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_4
Text preview: In fact, some NTFP-providing trees, such as the baobab (Adansonia digitata) and the shea tree (Vitel...
Found 4 entities:
  - 'trees' → LULC
  - 'tree' → LULC
  - 'cultivation' → PROCESS
  - 'fallows' → LULC

Processing ID: 1-s2.0-S0140196322000143-main_273
Text preview: In rangelands, the main cause of woody vegetation decrease is the increasing pressure on wood resour...
Found 7 entities:
  - 'cause' → CHANGE
  - 'decrease' → CHANGE
  - 'increasing' → CHANGE
  - 'growing' → CHANGE
  - 'urban' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S0140196313000608-main_184
Text preview: In Saloum Senegal, with the increase of cultivated land and shortening of [fallow] cycles, soils hav...
Found 6 entities:
  - 'Saloum' → LOC
  - 'Senegal' → LOC
  - 'increase' → CHANGE
  - 'fallow' → LULC
  - 'fallow' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0301479717300713-main_134
Text preview: Irrigation from rivers is regarded as minor driver of [LULCC]...
Found 1 entities:
  - 'driver' → CHANGE

Processing ID: 1-s2.0-S0303243414001718-main_164
Text preview: On the one hand, tree growth and [agroforestry] on fields have led to an increase of woody cover in ...
Found 4 entities:
  - 'tree' → LULC
  - 'growth' → CHANGE
  - 'agroforestry' → LULC
  - 'increase' → CHANGE

Processing ID: 1-s2.0-S0140196322000143-main_50
Text preview: Rangelands are grazed year-round under communal access but grazing also extends to fallows, year-rou...
Found 5 entities:
  - 'year-round' → DATE
  - 'fallows' → LULC
  - 'year-round' → DATE
  - 'the dry season' → DATE
  - 'crop' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_563b
Text preview: Ratios of [fallow] to cultivated area are 0.8 in Woure, where the bushfallow system is "already defu...
Found 12 entities:
  - 'fallow' → LULC
  - '0.8' → CARDINAL
  - 'Woure' → LOC
  - 'ow' → LULC
  - '1.6' → CARDINAL
  ... and 7 more

Processing ID: 1-s2.0-S0140196314000536-main_305
Text preview: Regular [cultivation] keeps the soil penetrable and farmers are aware of the benefits of trees in th...
Found 2 entities:
  - 'cultivation' → PROCESS
  - 'trees' → LULC

Processing ID: 1-s2.0-S0140196314000536-main_330
Text preview: Since the 1960s, the natural vegetation has been completely transformed and today many trees and [sh...
Found 5 entities:
  - 'the 1960s' → DATE
  - 'transformed' → CHANGE
  - 'today' → DATE
  - 'trees' → LULC
  - 'shrubs' → LULC

Processing ID: 1-s2.0-S0006320709005400-main_5
Text preview: The available evidence suggests that [forest] loss and degradation has been caused primarily by agri...
Found 4 entities:
  - 'forest' → LULC
  - 'loss' → CHANGE
  - 'caused' → CHANGE
  - 'expansion' → CHANGE

Processing ID: 1-s2.0-S095937809800003X-main_240
Text preview: Thus, changes in [land use] strategies result not only in a simple expansion of fields to new and le...
Found 2 entities:
  - 'changes' → CHANGE
  - 'expansion' → CHANGE

Processing ID: 1-s2.0-S003442571730041X-main_192
Text preview: Whereas most [shrubs] are annually coppiced in fields prior to [cultivation], they are left to grow ...
Found 6 entities:
  - 'shrubs' → LULC
  - 'annually' → DATE
  - 'cultivation' → PROCESS
  - 'grow' → CHANGE
  - 'fallowed fields' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0301479717300713-main_44
Text preview: In a small Sahelian catchment in Niger, the increase in cultivated land from 1950 to 1998 was associ...
Found 7 entities:
  - 'Sahelian' → LOC
  - 'Niger' → LOC
  - 'increase' → CHANGE
  - '1950 to 1998' → DATE
  - 'increase' → CHANGE
  ... and 2 more

Processing ID: 1-s2.0-S0264837701000205-main_126
Text preview: New settlements caused an initial decrease of the vegetation due to [[land use]] change (bushland to...
Found 4 entities:
  - 'caused' → CHANGE
  - 'decrease' → CHANGE
  - 'change' → CHANGE
  - 'bushland' → LULC

Processing ID: 1-s2.0-S095937809800003X-main_192
Text preview: Apparently, the proximity of Yale ´to the road made influx of people higher than Boala, which is in ...
Found 6 entities:
  - 'road' → LULC
  - 'Boala' → LOC
  - 'cause' → CHANGE
  - 'effect' → CHANGE
  - 'expansion' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S003442571730041X-main_18
Text preview: Recently, obtained a [deforestation] rate of 11% in the [grassland] areas and a degradation of 17% i...
Found 7 entities:
  - 'deforestation' → PROCESS
  - '11%' → PERCENT
  - 'grassland' → LULC
  - '17%' → PERCENT
  - 'Ghana' → LOC
  ... and 2 more

Processing ID: 1-s2.0-S0140196322000143-main_174
Text preview: However, conflicting hypotheses have been reported: on the one hand an expansion (into native [savan...
Found 6 entities:
  - 'expansion' → CHANGE
  - 'savanna' → LULC
  - 'cropland' → LULC
  - 'cultivation' → PROCESS
  - 'caused' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S0140196313000608-main_187
Text preview: The decrease in rainfall has been associated with a concentration of the [cultivation] of the sandy ...
Found 1 entities:
  - 'decrease' → CHANGE

Processing ID: 1-s2.0-S0168192311001122-main_62b
Text preview: The decrease in rainfall has been associated with a concentration of the [cultivation] of the sandy ...
Found 1 entities:
  - 'decrease' → CHANGE

Processing ID: 1-s2.0-S0169204617300270-main_294
Text preview: In the period 1975-1990, 1.28 million ha (26%) of natural vegetation was converted to degraded [sava...
Found 12 entities:
  - 'the period' → DATE
  - '1975-1990' → COORDINATES
  - '1.28 million' → COORDINATES
  - '26' → PERCENT
  - 'converted' → CHANGE
  ... and 7 more

Processing ID: 1-s2.0-S0301479717300713-main_20
Text preview: At the local scale, the size of [crop] and grazing lands increased at the expense of shrinking of [f...
Found 4 entities:
  - 'crop' → LULC
  - 'increased' → CHANGE
  - 'forest' → LULC
  - 'of change' → CHANGE

Processing ID: 1-s2.0-S095937809800003X-main_90a
Text preview: The decrease in woodland, [shrub] savannas, grass savannas and [water] body occurred mainly between ...
Found 13 entities:
  - 'decrease' → CHANGE
  - 'shrub' → LULC
  - 'savannas' → LULC
  - 'grass' → LULC
  - 'savannas' → LULC
  ... and 8 more

Processing ID: 1-s2.0-S0264837715302131-main_81
Text preview: The main finding of this study is the loss of vegetation cover over a 29 year period which is the re...
Found 3 entities:
  - 'loss' → CHANGE
  - '29 year' → DATE
  - 'agriculture' → LULC

Processing ID: 1-s2.0-S0308521X12000157-main_52
Text preview: From 1984 to 2001, [tree] savannas, bare soils and agricultural lands increased by 17.55%, 18.79% an...
Found 18 entities:
  - '1984 to 2001' → DATE
  - 'tree' → LULC
  - 'savannas' → LULC
  - 'bare soils' → LULC
  - 'increased' → CHANGE
  ... and 13 more

Processing ID: 1-s2.0-S0301479717300713-main_914
Text preview: At regional scale, the annual rate of change in [forest] land, grazing land, gallery [forest] and cr...
Found 6 entities:
  - 'annual' → DATE
  - 'of change' → CHANGE
  - 'forest' → LULC
  - 'forest' → LULC
  - 'cropland' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0140196314000536-main_371
Text preview: Most of the transformed [forest] converted to woodland (3.6%) and [tree] [savanna] (1.5%)...
Found 7 entities:
  - 'transformed' → CHANGE
  - 'forest' → LULC
  - 'converted' → CHANGE
  - '3.6' → PERCENT
  - 'tree' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S0006320709005400-main_118
Text preview: #text': 'While natural [forest] has declined across West Africa, plantations, often but not always o...
Found 4 entities:
  - 'forest' → LULC
  - 'declined' → CHANGE
  - 'West Africa' → LOC
  - 'increased' → CHANGE

Processing ID: 1-s2.0-S0168192311001122-main_96
Text preview: P11: (Interviewer: But if I\'m thinking of the Vea catchment, mainly here it\'s [rice].) Cause there...
No entities found

Processing ID: 1-s2.0-S0301479717300713-main_131b
Text preview: According to it was assumed .'}, {'ref': {'@type': 'table', '@target': '#tab_0', '#text': '1'}, '#te...
Found 6 entities:
  - '1' → CARDINAL
  - 'only 25%' → PERCENT
  - 'cropped' → LULC
  - 'savanna' → LULC
  - 'fallow' → LULC
  ... and 1 more

Processing ID: remotesensing-12-03817-v2_162
Text preview: In the surroundings of the cities in the north of Nigeria for example in 2000 patches of grassland a...
Found 8 entities:
  - 'cities' → LULC
  - 'Nigeria' → LOC
  - '2000' → DATE
  - 'grassland' → LULC
  - 'shrubland' → LULC
  ... and 3 more

Processing ID: 010074873_166
Text preview: In second hand the increase in shrubs The evergreen forest and forest cover mainly the south eastern...
Found 6 entities:
  - 'increase' → CHANGE
  - 'shrubs' → LULC
  - 'evergreen forest' → LULC
  - 'forest' → LULC
  - 'Volta' → LOC
  ... and 1 more

Processing ID: remotesensing-07-04048-v2_73
Text preview: reported a moderate land cover change from 1965 to 2000 a decrease in savanna from 74% to 70% concur...
Found 9 entities:
  - 'change' → CHANGE
  - '1965 to 2000' → DATE
  - 'decrease' → CHANGE
  - 'savanna' → LULC
  - '74% to 70%' → PERCENT
  ... and 4 more

Processing ID: s41598-024-52138-9_58
Text preview: Large scale cropland was the third highest driver of forest loss in Africa 9% with the highest propo...
Found 15 entities:
  - 'cropland' → LULC
  - 'driver' → CHANGE
  - 'forest' → LULC
  - 'loss' → CHANGE
  - 'Africa' → LOC
  ... and 10 more

Processing ID: 1-s2.0-S0264837701000205-main_131
Text preview: From 1955 to 1986 the area on the dune above Mare Yomboli was cleared and used for cultivation and f...
Found 2 entities:
  - '1955 to 1986' → DATE
  - 'cultivation' → PROCESS

Processing ID: s10980-017-0553-4_46
Text preview: The Upper Guinean forest is a global biodiversity hotspot and has become one of the most human modif...
Found 7 entities:
  - 'forest' → LULC
  - 'modified' → CHANGE
  - 'forest' → LULC
  - 'over 80%' → PERCENT
  - 'forest' → LULC
  ... and 2 more

Processing ID: s10113-015-0891-1_304
Text preview: With the exception of Eastern Africa area in forest declined in all regions with the most pronounced...
Found 6 entities:
  - 'Eastern Africa' → LOC
  - 'forest' → LULC
  - 'declined' → CHANGE
  - 'reduction' → CHANGE
  - 'Northern Africa' → LOC
  ... and 1 more

Processing ID: 1-s2.0-S0341816222001990-main_236
Text preview: Precipitation factors dominated the spatial distribution of desertification in the Sahel q value 0.9...
Found 2 entities:
  - 'desertification' → PROCESS
  - '0.9269' → CARDINAL

Processing ID: science.abm9267_210
Text preview: The most prominent example of this is pasture expansion which is tightly linked to soy expansion and...
Found 4 entities:
  - 'pasture' → LULC
  - 'expansion' → CHANGE
  - 'expansion' → CHANGE
  - 'Latin America' → LOC

Processing ID: rudel-2013-the-national-determinants-of-deforestation-in-sub-saharan-africa_24
Text preview: Finally five of the six Congo basin countries that contain almost all of the continent s humid fores...
Found 6 entities:
  - 'five' → CARDINAL
  - 'six' → CARDINAL
  - 'Congo' → LOC
  - 'forests' → LULC
  - 'effects' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S2468227619307070-main_14
Text preview: Human activities have degraded about 85% of Ghana s Guinea Forest Region...
Found 3 entities:
  - 'about 85%' → PERCENT
  - 'Ghana' → LOC
  - 'Forest' → LULC

Processing ID: IBRAHIMetal_HJ2014_175b
Text preview: Actually present day cultivation cycles in southwestern Niger could be considered to consist of 10 y...
Found 6 entities:
  - 'cultivation' → PROCESS
  - 'Niger' → LOC
  - '10 years' → DATE
  - 'millet' → LULC
  - '5 years' → DATE
  ... and 1 more

Processing ID: Asenso Barnieh et al. - 2020 - Mapping Land Use Land Cover Transitions at Differe_433
Text preview: and Hausermann confirm that the expansion of water bodies we detected in the Tain District see Figur...
Found 6 entities:
  - 'expansion' → CHANGE
  - 'water bodies' → LULC
  - 'the Tain District' → LOC
  - 'Ghana' → LOC
  - 'Ghana' → LOC
  ... and 1 more

Processing ID: Asenso Barnieh et al. - 2020 - Mapping Land Use Land Cover Transitions at Differe_302
Text preview: The annual rate i.e. 0.8% of water bodies loss per year was higher in 2000 2013 i.e. the postdrought...
Found 7 entities:
  - 'annual' → DATE
  - '0.8%' → PERCENT
  - 'water bodies' → LULC
  - 'loss' → CHANGE
  - '2000 2013' → DATE
  ... and 2 more

Processing ID: 1-s2.0-S2214581823000575-main_146
Text preview: 2020 The major LULC changes in LCB from 1975 to 2013 stated by were the transition of water bodies a...
Found 11 entities:
  - 'changes' → CHANGE
  - '1975' → DATE
  - '2013' → DATE
  - 'transition' → CHANGE
  - 'water bodies' → LULC
  ... and 6 more

Processing ID: 1-s2.0-S0341816222001990-main_164
Text preview: During 2000 2010 the level of desertification has reduced whereas from 2010 to 2015 most areas have ...
Found 9 entities:
  - '2000 2010' → COORDINATES
  - 'desertification' → PROCESS
  - '2010' → DATE
  - '2015' → DATE
  - 'shifted' → CHANGE
  ... and 4 more

Processing ID: 010074873_289
Text preview: Nevertheless the shrubs cluster has increased over time within Volta basin and this could be attribu...
Found 4 entities:
  - 'shrubs' → LULC
  - 'increased' → CHANGE
  - 'Volta' → LOC
  - 'agroforestry' → LULC

Processing ID: 1-s2.0-S2468227619307070-main_4
Text preview: We observed deforestation patterns in the Ashanti region of Ghana from 1986 to 2015 using Landsat im...
Found 6 entities:
  - 'deforestation' → PROCESS
  - 'Ghana' → LOC
  - '1986 to' → DATE
  - '2015' → DATE
  - 'causes' → CHANGE
  ... and 1 more

Processing ID: 010076607_252
Text preview: The savanna cluster presents an increasing trend during 2002 2016 period probably due to agroforestr...
Found 4 entities:
  - 'savanna' → LULC
  - 'increasing' → CHANGE
  - '2002 2016' → DATE
  - 'agroforestry' → LULC

Processing ID: Kouassi et al. - 2021 - Assessing Land Use and Land Cover Change and Farme_121
Text preview: The majority of other cash crops was converted to food crop fallow areas 1067.98 km 2...
Found 6 entities:
  - 'crops' → LULC
  - 'converted' → CHANGE
  - 'crop' → LULC
  - 'fallow' → LULC
  - '1067.98 km' → SURFACE_UNIT
  ... and 1 more

Processing ID: Asenso Barnieh et al. - 2020 - Mapping Land Use Land Cover Transitions at Differe_237
Text preview: In contrast relative net gain in open water bodies was observed in the humid region during the perio...
Found 6 entities:
  - 'gain' → CHANGE
  - 'water bodies' → LULC
  - 'the period of' → DATE
  - '1975 2000' → DATE
  - 'loss' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S0264837701000205-main_64
Text preview: The land use is dominated by cultivation however cultivation intensity varies significantly within t...
Found 4 entities:
  - 'cultivation' → PROCESS
  - 'cultivation' → PROCESS
  - 'varies' → CHANGE
  - '10% to 74%' → PERCENT

Processing ID: 1-s2.0-S003442571730041X-main_50
Text preview: In Fakara the landscape was converted from a Sahelian savanna to largely eroded agricultural agrofor...
Found 6 entities:
  - 'Fakara' → LOC
  - 'converted' → CHANGE
  - 'Sahelian' → LOC
  - 'savanna' → LULC
  - 'agroforestry' → LULC
  ... and 1 more

Processing ID: 010074873_180b
Text preview: The result reveals that the Mono basin Table land cover presents an increase in built up agricultura...
Found 8 entities:
  - 'increase' → CHANGE
  - 'built up' → LULC
  - 'water bodies' → LULC
  - 'forest' → LULC
  - 'savanna' → LULC
  ... and 3 more

Processing ID: 1-s2.0-S0140196313000608-main_165
Text preview: In the Peanut Basin West Central eco region in Senegal cultivated area peaked to 80% of the land in ...
Found 7 entities:
  - 'Senegal' → LOC
  - '80%' → PERCENT
  - 'the mid 1980s' → DATE
  - 'declining' → CHANGE
  - 'about 67%' → PERCENT
  ... and 2 more

Processing ID: s43247-020-00053-y_93
Text preview: In West Africa the land cover category settlement made up 0.3% and 0.7% of the total study region in...
Found 5 entities:
  - 'West Africa' → LOC
  - '0.3%' → PERCENT
  - '0.7%' → PERCENT
  - '1975' → DATE
  - '2013' → DATE
✅ Label Studio config saved to: label_studio_output/ner_label_studio_config.xml

✅ Processing complete!
📄 Results saved to: label_studio_output/label_studio_ner_tasks.json
📊 Total tasks: 67
🏷️ Total entities extracted: 391
🏷️ Unique labels found: ['CARDINAL', 'CHANGE', 'COORDINATES', 'DATE', 'LOC', 'LULC', 'PERCENT', 'PROCESS', 'SURFACE_UNIT']

📝 To import in Label Studio:
1. Create a new project in Label Studio
2. Go to Settings > Labeling Interface > Code
3. Paste the content from: label_studio_output/ner_label_studio_config.xml

In [15]:
import spacy
import pandas as pd
import json
from transformers import pipeline
from itertools import groupby

# Load your NER model
ner_pipeline = pipeline(
    "ner",
    model="./final_ner_model",  # Update with your model path
    tokenizer="./final_ner_model",
    aggregation_strategy="simple"  # Groups sub-word tokens
)

def ner_to_spans(text, entities):
    """Convert NER output to Label Studio spans format"""
    results = []
    unique_labels = set()
    
    for entity in entities:
        # Skip 'O' labels
        if entity.get('entity_group', entity.get('entity', '')).endswith('-O'):
            continue
            
        # Extract clean label (remove B-, I- prefixes)
        label = entity.get('entity_group', entity.get('entity', '')).replace('B-', '').replace('I-', '')
        
        # Add to unique labels set
        unique_labels.add(label)
        
        # Create span in Label Studio format
        results.append({
            'from_name': 'label',
            'to_name': 'text',
            'type': 'labels',
            'value': {
                'start': entity['start'],
                'end': entity['end'],
                'text': text[entity['start']:entity['end']],
                'labels': [label]
            }
        })
    
    return results, unique_labels

# Load your CSV file
print("📂 Loading CSV file...")
csv_file = 'annotated_corpus_for_dataverse.csv'  # Update with your file path
df = pd.read_csv(csv_file)

# Filter for rows where relevance_label is not 'zero' (optional)
print("🔍 Filtering data...")
filtered_df = df[df['relevance_label'] ==2].copy()
print(f"✅ Filtered to {len(filtered_df)} rows")

# Prepare Label Studio tasks
all_entities = set()
tasks = []

print("\n📊 Processing texts and extracting entities...")

for index, row in filtered_df.iterrows():
    text = row['text_segment']
    article_id = row['id_segment']
    
    print(f"\nProcessing ID: {article_id}")
    print(f"Text preview: {text[:100]}...")
    
    # Extract entities using your model
    entities = ner_pipeline(text)
    
    # Convert to Label Studio format
    spans, unique_labels = ner_to_spans(text, entities)
    all_entities.update(unique_labels)
    
    # Create task with predictions
    task = {
        'data': {
            'text': text
        },
        'predictions': [{
            'model_version': 'ner_model_v1',
            'result': spans
        }]
    }
    
    tasks.append(task)
    
    # Print extracted entities for verification
    if spans:
        print(f"Found {len(spans)} entities:")
        for span in spans[:5]:  # Show first 5
            print(f"  - '{span['value']['text']}' → {span['value']['labels'][0]}")
        if len(spans) > 5:
            print(f"  ... and {len(spans) - 5} more")
    else:
        print("No entities found")

# Create output directory
output_dir = "label_studio_output"
os.makedirs(output_dir, exist_ok=True)

# Save tasks as Label Studio JSON format
output_file = os.path.join(output_dir, 'tasks.json')
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(tasks, f, indent=2, ensure_ascii=False)

# Save entity labels
labels_file = os.path.join(output_dir, 'named_entities.txt')
with open(labels_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(sorted(all_entities)))

print(f"\n✅ Processing complete!")
print(f"📄 Tasks saved to: {output_file}")
print(f"📄 Entity labels saved to: {labels_file}")
print(f"📊 Total tasks: {len(tasks)}")
print(f"🏷️ Total unique entities: {len(all_entities)}")
print(f"🏷️ Entity types: {sorted(all_entities)}")

# XML Configuration for Label Studio
xml_config = """<View>
  <Text name="text" value="$text"/>
  <Labels name="label" toName="text">
"""
for label in sorted(all_entities):
    xml_config += f'    <Label value="{label}" background="yellow"/>\n'
xml_config += """  </Labels>
</View>"""

config_file = os.path.join(output_dir, 'label_studio_config.xml')
with open(config_file, 'w', encoding='utf-8') as f:
    f.write(xml_config)

print("\n📝 To import in Label Studio:")
print("1. Create a new project")
print(f"2. Go to Settings > Labeling Interface > Code")
print(f"3. Paste the content from: {config_file}")
print(f"4. Go to Import and upload: {output_file}")

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

📂 Loading CSV file...
🔍 Filtering data...
✅ Filtered to 67 rows

📊 Processing texts and extracting entities...

Processing ID: 1-s2.0-S0303243414001718-main_19b
Text preview: #text': 'After the droughts in the 1970s and 1980s, the observed loss of woody vegetation cover was ...
Found 2 entities:
  - 'the 1970s and 1980s' → DATE
  - 'loss' → CHANGE

Processing ID: 1-s2.0-S0006320709005400-main_16b
Text preview: #text': 'The forests of West and Central Africa probably originally covered a combined area of about...
Found 5 entities:
  - 'forests' → LULC
  - 'West' → LOC
  - 'Central Africa' → LOC
  - 'area of about 3 million km' → SURFACE_UNIT
  - '2' → CARDINAL

Processing ID: 1-s2.0-S0140196322000143-main_121
Text preview: ).'}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': {'@n': '4.2.', '#text': '[Land use ]change...
Found 9 entities:
  - '4.2' → CARDINAL
  - 'change' → CHANGE
  - '1996 to 2017' → DATE
  - 'increased' → CHANGE
  - '40% to 51.3%' → PERCENT
  ... and 4 more

Processing ID: 1-s2.0-S0264837715302131-main_119
Text preview: [Agriculture] in this region has been dominated over the past three decades by [cotton] production...
Found 3 entities:
  - 'Agriculture' → LULC
  - 'the past three decades' → DATE
  - 'cotton' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_76
Text preview: [Forest] land was decreased nearly by half in 2002 compared to its coverage in 1984, while the size ...
Found 7 entities:
  - 'Forest' → LULC
  - 'decreased' → CHANGE
  - 'half' → CARDINAL
  - '2002' → DATE
  - '1984' → DATE
  ... and 2 more

Processing ID: 1-s2.0-S0264837715302131-main_147
Text preview: About 26 and 31% of the total area of natural vegetation ([forest], woodland and tree [savanna]) wil...
Found 11 entities:
  - '26' → CARDINAL
  - '31%' → PERCENT
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  ... and 6 more

Processing ID: 1-s2.0-S0264837715302131-main_103
Text preview: Assuming the dynamics recorded in the second period , the amounts of land covered by [forest], woodl...
Found 11 entities:
  - 'forest' → LULC
  - 'tree' → LULC
  - 'savanna' → LULC
  - 'decrease' → CHANGE
  - '5, 9' → COORDINATES
  ... and 6 more

Processing ID: 1-s2.0-S0140196310000893-main_115
Text preview: Conversely the decrease in the herbaceous standing [crop], due to the shortening of the [fallow] per...
Found 3 entities:
  - 'decrease' → CHANGE
  - 'crop' → LULC
  - 'fallow' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_317
Text preview: describes Rwandan [agriculture] as caught in a "low investment trap"; less than 10% of cropland is i...
Found 4 entities:
  - 'Rwandan' → LOC
  - 'agriculture' → LULC
  - 'less than 10%' → PERCENT
  - 'cropland' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_41
Text preview: Due to the weeding practice, [bare soil] dominates in cropped fields in the early growing season whi...
Found 4 entities:
  - 'bare soil' → LULC
  - 'early growing season' → DATE
  - 'grow' → CHANGE
  - 'fallows' → LULC

Processing ID: 1-s2.0-S016788090800131X-main_82
Text preview: In 1986, the grazing land had much higher proportion of the total regional area than other [land use...
Found 3 entities:
  - '1986' → DATE
  - 'croplands' → LULC
  - '16 years' → DATE

Processing ID: 1-s2.0-S0264837715302131-main_74
Text preview: In 1990, woodland and tree [savanna] were still the dominant [land cover] types...
Found 3 entities:
  - '1990' → DATE
  - 'tree' → LULC
  - 'savanna' → LULC

Processing ID: 1-s2.0-S003442571730041X-main_4
Text preview: In fact, some NTFP-providing trees, such as the baobab (Adansonia digitata) and the shea tree (Vitel...
Found 4 entities:
  - 'trees' → LULC
  - 'tree' → LULC
  - 'cultivation' → PROCESS
  - 'fallows' → LULC

Processing ID: 1-s2.0-S0140196322000143-main_273
Text preview: In rangelands, the main cause of woody vegetation decrease is the increasing pressure on wood resour...
Found 7 entities:
  - 'cause' → CHANGE
  - 'decrease' → CHANGE
  - 'increasing' → CHANGE
  - 'growing' → CHANGE
  - 'urban' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S0140196313000608-main_184
Text preview: In Saloum Senegal, with the increase of cultivated land and shortening of [fallow] cycles, soils hav...
Found 6 entities:
  - 'Saloum' → LOC
  - 'Senegal' → LOC
  - 'increase' → CHANGE
  - 'fallow' → LULC
  - 'fallow' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0301479717300713-main_134
Text preview: Irrigation from rivers is regarded as minor driver of [LULCC]...
Found 1 entities:
  - 'driver' → CHANGE

Processing ID: 1-s2.0-S0303243414001718-main_164
Text preview: On the one hand, tree growth and [agroforestry] on fields have led to an increase of woody cover in ...
Found 4 entities:
  - 'tree' → LULC
  - 'growth' → CHANGE
  - 'agroforestry' → LULC
  - 'increase' → CHANGE

Processing ID: 1-s2.0-S0140196322000143-main_50
Text preview: Rangelands are grazed year-round under communal access but grazing also extends to fallows, year-rou...
Found 5 entities:
  - 'year-round' → DATE
  - 'fallows' → LULC
  - 'year-round' → DATE
  - 'the dry season' → DATE
  - 'crop' → LULC

Processing ID: 1-s2.0-S030438781000043X-mainext_563b
Text preview: Ratios of [fallow] to cultivated area are 0.8 in Woure, where the bushfallow system is "already defu...
Found 12 entities:
  - 'fallow' → LULC
  - '0.8' → CARDINAL
  - 'Woure' → LOC
  - 'ow' → LULC
  - '1.6' → CARDINAL
  ... and 7 more

Processing ID: 1-s2.0-S0140196314000536-main_305
Text preview: Regular [cultivation] keeps the soil penetrable and farmers are aware of the benefits of trees in th...
Found 2 entities:
  - 'cultivation' → PROCESS
  - 'trees' → LULC

Processing ID: 1-s2.0-S0140196314000536-main_330
Text preview: Since the 1960s, the natural vegetation has been completely transformed and today many trees and [sh...
Found 5 entities:
  - 'the 1960s' → DATE
  - 'transformed' → CHANGE
  - 'today' → DATE
  - 'trees' → LULC
  - 'shrubs' → LULC

Processing ID: 1-s2.0-S0006320709005400-main_5
Text preview: The available evidence suggests that [forest] loss and degradation has been caused primarily by agri...
Found 4 entities:
  - 'forest' → LULC
  - 'loss' → CHANGE
  - 'caused' → CHANGE
  - 'expansion' → CHANGE

Processing ID: 1-s2.0-S095937809800003X-main_240
Text preview: Thus, changes in [land use] strategies result not only in a simple expansion of fields to new and le...
Found 2 entities:
  - 'changes' → CHANGE
  - 'expansion' → CHANGE

Processing ID: 1-s2.0-S003442571730041X-main_192
Text preview: Whereas most [shrubs] are annually coppiced in fields prior to [cultivation], they are left to grow ...
Found 6 entities:
  - 'shrubs' → LULC
  - 'annually' → DATE
  - 'cultivation' → PROCESS
  - 'grow' → CHANGE
  - 'fallowed fields' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0301479717300713-main_44
Text preview: In a small Sahelian catchment in Niger, the increase in cultivated land from 1950 to 1998 was associ...
Found 7 entities:
  - 'Sahelian' → LOC
  - 'Niger' → LOC
  - 'increase' → CHANGE
  - '1950 to 1998' → DATE
  - 'increase' → CHANGE
  ... and 2 more

Processing ID: 1-s2.0-S0264837701000205-main_126
Text preview: New settlements caused an initial decrease of the vegetation due to [[land use]] change (bushland to...
Found 4 entities:
  - 'caused' → CHANGE
  - 'decrease' → CHANGE
  - 'change' → CHANGE
  - 'bushland' → LULC

Processing ID: 1-s2.0-S095937809800003X-main_192
Text preview: Apparently, the proximity of Yale ´to the road made influx of people higher than Boala, which is in ...
Found 6 entities:
  - 'road' → LULC
  - 'Boala' → LOC
  - 'cause' → CHANGE
  - 'effect' → CHANGE
  - 'expansion' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S003442571730041X-main_18
Text preview: Recently, obtained a [deforestation] rate of 11% in the [grassland] areas and a degradation of 17% i...
Found 7 entities:
  - 'deforestation' → PROCESS
  - '11%' → PERCENT
  - 'grassland' → LULC
  - '17%' → PERCENT
  - 'Ghana' → LOC
  ... and 2 more

Processing ID: 1-s2.0-S0140196322000143-main_174
Text preview: However, conflicting hypotheses have been reported: on the one hand an expansion (into native [savan...
Found 6 entities:
  - 'expansion' → CHANGE
  - 'savanna' → LULC
  - 'cropland' → LULC
  - 'cultivation' → PROCESS
  - 'caused' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S0140196313000608-main_187
Text preview: The decrease in rainfall has been associated with a concentration of the [cultivation] of the sandy ...
Found 1 entities:
  - 'decrease' → CHANGE

Processing ID: 1-s2.0-S0168192311001122-main_62b
Text preview: The decrease in rainfall has been associated with a concentration of the [cultivation] of the sandy ...
Found 1 entities:
  - 'decrease' → CHANGE

Processing ID: 1-s2.0-S0169204617300270-main_294
Text preview: In the period 1975-1990, 1.28 million ha (26%) of natural vegetation was converted to degraded [sava...
Found 12 entities:
  - 'the period' → DATE
  - '1975-1990' → COORDINATES
  - '1.28 million' → COORDINATES
  - '26' → PERCENT
  - 'converted' → CHANGE
  ... and 7 more

Processing ID: 1-s2.0-S0301479717300713-main_20
Text preview: At the local scale, the size of [crop] and grazing lands increased at the expense of shrinking of [f...
Found 4 entities:
  - 'crop' → LULC
  - 'increased' → CHANGE
  - 'forest' → LULC
  - 'of change' → CHANGE

Processing ID: 1-s2.0-S095937809800003X-main_90a
Text preview: The decrease in woodland, [shrub] savannas, grass savannas and [water] body occurred mainly between ...
Found 13 entities:
  - 'decrease' → CHANGE
  - 'shrub' → LULC
  - 'savannas' → LULC
  - 'grass' → LULC
  - 'savannas' → LULC
  ... and 8 more

Processing ID: 1-s2.0-S0264837715302131-main_81
Text preview: The main finding of this study is the loss of vegetation cover over a 29 year period which is the re...
Found 3 entities:
  - 'loss' → CHANGE
  - '29 year' → DATE
  - 'agriculture' → LULC

Processing ID: 1-s2.0-S0308521X12000157-main_52
Text preview: From 1984 to 2001, [tree] savannas, bare soils and agricultural lands increased by 17.55%, 18.79% an...
Found 18 entities:
  - '1984 to 2001' → DATE
  - 'tree' → LULC
  - 'savannas' → LULC
  - 'bare soils' → LULC
  - 'increased' → CHANGE
  ... and 13 more

Processing ID: 1-s2.0-S0301479717300713-main_914
Text preview: At regional scale, the annual rate of change in [forest] land, grazing land, gallery [forest] and cr...
Found 6 entities:
  - 'annual' → DATE
  - 'of change' → CHANGE
  - 'forest' → LULC
  - 'forest' → LULC
  - 'cropland' → LULC
  ... and 1 more

Processing ID: 1-s2.0-S0140196314000536-main_371
Text preview: Most of the transformed [forest] converted to woodland (3.6%) and [tree] [savanna] (1.5%)...
Found 7 entities:
  - 'transformed' → CHANGE
  - 'forest' → LULC
  - 'converted' → CHANGE
  - '3.6' → PERCENT
  - 'tree' → LULC
  ... and 2 more

Processing ID: 1-s2.0-S0006320709005400-main_118
Text preview: #text': 'While natural [forest] has declined across West Africa, plantations, often but not always o...
Found 4 entities:
  - 'forest' → LULC
  - 'declined' → CHANGE
  - 'West Africa' → LOC
  - 'increased' → CHANGE

Processing ID: 1-s2.0-S0168192311001122-main_96
Text preview: P11: (Interviewer: But if I\'m thinking of the Vea catchment, mainly here it\'s [rice].) Cause there...
No entities found

Processing ID: 1-s2.0-S0301479717300713-main_131b
Text preview: According to it was assumed .'}, {'ref': {'@type': 'table', '@target': '#tab_0', '#text': '1'}, '#te...
Found 6 entities:
  - '1' → CARDINAL
  - 'only 25%' → PERCENT
  - 'cropped' → LULC
  - 'savanna' → LULC
  - 'fallow' → LULC
  ... and 1 more

Processing ID: remotesensing-12-03817-v2_162
Text preview: In the surroundings of the cities in the north of Nigeria for example in 2000 patches of grassland a...
Found 8 entities:
  - 'cities' → LULC
  - 'Nigeria' → LOC
  - '2000' → DATE
  - 'grassland' → LULC
  - 'shrubland' → LULC
  ... and 3 more

Processing ID: 010074873_166
Text preview: In second hand the increase in shrubs The evergreen forest and forest cover mainly the south eastern...
Found 6 entities:
  - 'increase' → CHANGE
  - 'shrubs' → LULC
  - 'evergreen forest' → LULC
  - 'forest' → LULC
  - 'Volta' → LOC
  ... and 1 more

Processing ID: remotesensing-07-04048-v2_73
Text preview: reported a moderate land cover change from 1965 to 2000 a decrease in savanna from 74% to 70% concur...
Found 9 entities:
  - 'change' → CHANGE
  - '1965 to 2000' → DATE
  - 'decrease' → CHANGE
  - 'savanna' → LULC
  - '74% to 70%' → PERCENT
  ... and 4 more

Processing ID: s41598-024-52138-9_58
Text preview: Large scale cropland was the third highest driver of forest loss in Africa 9% with the highest propo...
Found 15 entities:
  - 'cropland' → LULC
  - 'driver' → CHANGE
  - 'forest' → LULC
  - 'loss' → CHANGE
  - 'Africa' → LOC
  ... and 10 more

Processing ID: 1-s2.0-S0264837701000205-main_131
Text preview: From 1955 to 1986 the area on the dune above Mare Yomboli was cleared and used for cultivation and f...
Found 2 entities:
  - '1955 to 1986' → DATE
  - 'cultivation' → PROCESS

Processing ID: s10980-017-0553-4_46
Text preview: The Upper Guinean forest is a global biodiversity hotspot and has become one of the most human modif...
Found 7 entities:
  - 'forest' → LULC
  - 'modified' → CHANGE
  - 'forest' → LULC
  - 'over 80%' → PERCENT
  - 'forest' → LULC
  ... and 2 more

Processing ID: s10113-015-0891-1_304
Text preview: With the exception of Eastern Africa area in forest declined in all regions with the most pronounced...
Found 6 entities:
  - 'Eastern Africa' → LOC
  - 'forest' → LULC
  - 'declined' → CHANGE
  - 'reduction' → CHANGE
  - 'Northern Africa' → LOC
  ... and 1 more

Processing ID: 1-s2.0-S0341816222001990-main_236
Text preview: Precipitation factors dominated the spatial distribution of desertification in the Sahel q value 0.9...
Found 2 entities:
  - 'desertification' → PROCESS
  - '0.9269' → CARDINAL

Processing ID: science.abm9267_210
Text preview: The most prominent example of this is pasture expansion which is tightly linked to soy expansion and...
Found 4 entities:
  - 'pasture' → LULC
  - 'expansion' → CHANGE
  - 'expansion' → CHANGE
  - 'Latin America' → LOC

Processing ID: rudel-2013-the-national-determinants-of-deforestation-in-sub-saharan-africa_24
Text preview: Finally five of the six Congo basin countries that contain almost all of the continent s humid fores...
Found 6 entities:
  - 'five' → CARDINAL
  - 'six' → CARDINAL
  - 'Congo' → LOC
  - 'forests' → LULC
  - 'effects' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S2468227619307070-main_14
Text preview: Human activities have degraded about 85% of Ghana s Guinea Forest Region...
Found 3 entities:
  - 'about 85%' → PERCENT
  - 'Ghana' → LOC
  - 'Forest' → LULC

Processing ID: IBRAHIMetal_HJ2014_175b
Text preview: Actually present day cultivation cycles in southwestern Niger could be considered to consist of 10 y...
Found 6 entities:
  - 'cultivation' → PROCESS
  - 'Niger' → LOC
  - '10 years' → DATE
  - 'millet' → LULC
  - '5 years' → DATE
  ... and 1 more

Processing ID: Asenso Barnieh et al. - 2020 - Mapping Land Use Land Cover Transitions at Differe_433
Text preview: and Hausermann confirm that the expansion of water bodies we detected in the Tain District see Figur...
Found 6 entities:
  - 'expansion' → CHANGE
  - 'water bodies' → LULC
  - 'the Tain District' → LOC
  - 'Ghana' → LOC
  - 'Ghana' → LOC
  ... and 1 more

Processing ID: Asenso Barnieh et al. - 2020 - Mapping Land Use Land Cover Transitions at Differe_302
Text preview: The annual rate i.e. 0.8% of water bodies loss per year was higher in 2000 2013 i.e. the postdrought...
Found 7 entities:
  - 'annual' → DATE
  - '0.8%' → PERCENT
  - 'water bodies' → LULC
  - 'loss' → CHANGE
  - '2000 2013' → DATE
  ... and 2 more

Processing ID: 1-s2.0-S2214581823000575-main_146
Text preview: 2020 The major LULC changes in LCB from 1975 to 2013 stated by were the transition of water bodies a...
Found 11 entities:
  - 'changes' → CHANGE
  - '1975' → DATE
  - '2013' → DATE
  - 'transition' → CHANGE
  - 'water bodies' → LULC
  ... and 6 more

Processing ID: 1-s2.0-S0341816222001990-main_164
Text preview: During 2000 2010 the level of desertification has reduced whereas from 2010 to 2015 most areas have ...
Found 9 entities:
  - '2000 2010' → COORDINATES
  - 'desertification' → PROCESS
  - '2010' → DATE
  - '2015' → DATE
  - 'shifted' → CHANGE
  ... and 4 more

Processing ID: 010074873_289
Text preview: Nevertheless the shrubs cluster has increased over time within Volta basin and this could be attribu...
Found 4 entities:
  - 'shrubs' → LULC
  - 'increased' → CHANGE
  - 'Volta' → LOC
  - 'agroforestry' → LULC

Processing ID: 1-s2.0-S2468227619307070-main_4
Text preview: We observed deforestation patterns in the Ashanti region of Ghana from 1986 to 2015 using Landsat im...
Found 6 entities:
  - 'deforestation' → PROCESS
  - 'Ghana' → LOC
  - '1986 to' → DATE
  - '2015' → DATE
  - 'causes' → CHANGE
  ... and 1 more

Processing ID: 010076607_252
Text preview: The savanna cluster presents an increasing trend during 2002 2016 period probably due to agroforestr...
Found 4 entities:
  - 'savanna' → LULC
  - 'increasing' → CHANGE
  - '2002 2016' → DATE
  - 'agroforestry' → LULC

Processing ID: Kouassi et al. - 2021 - Assessing Land Use and Land Cover Change and Farme_121
Text preview: The majority of other cash crops was converted to food crop fallow areas 1067.98 km 2...
Found 6 entities:
  - 'crops' → LULC
  - 'converted' → CHANGE
  - 'crop' → LULC
  - 'fallow' → LULC
  - '1067.98 km' → SURFACE_UNIT
  ... and 1 more

Processing ID: Asenso Barnieh et al. - 2020 - Mapping Land Use Land Cover Transitions at Differe_237
Text preview: In contrast relative net gain in open water bodies was observed in the humid region during the perio...
Found 6 entities:
  - 'gain' → CHANGE
  - 'water bodies' → LULC
  - 'the period of' → DATE
  - '1975 2000' → DATE
  - 'loss' → CHANGE
  ... and 1 more

Processing ID: 1-s2.0-S0264837701000205-main_64
Text preview: The land use is dominated by cultivation however cultivation intensity varies significantly within t...
Found 4 entities:
  - 'cultivation' → PROCESS
  - 'cultivation' → PROCESS
  - 'varies' → CHANGE
  - '10% to 74%' → PERCENT

Processing ID: 1-s2.0-S003442571730041X-main_50
Text preview: In Fakara the landscape was converted from a Sahelian savanna to largely eroded agricultural agrofor...
Found 6 entities:
  - 'Fakara' → LOC
  - 'converted' → CHANGE
  - 'Sahelian' → LOC
  - 'savanna' → LULC
  - 'agroforestry' → LULC
  ... and 1 more

Processing ID: 010074873_180b
Text preview: The result reveals that the Mono basin Table land cover presents an increase in built up agricultura...
Found 8 entities:
  - 'increase' → CHANGE
  - 'built up' → LULC
  - 'water bodies' → LULC
  - 'forest' → LULC
  - 'savanna' → LULC
  ... and 3 more

Processing ID: 1-s2.0-S0140196313000608-main_165
Text preview: In the Peanut Basin West Central eco region in Senegal cultivated area peaked to 80% of the land in ...
Found 7 entities:
  - 'Senegal' → LOC
  - '80%' → PERCENT
  - 'the mid 1980s' → DATE
  - 'declining' → CHANGE
  - 'about 67%' → PERCENT
  ... and 2 more

Processing ID: s43247-020-00053-y_93
Text preview: In West Africa the land cover category settlement made up 0.3% and 0.7% of the total study region in...
Found 5 entities:
  - 'West Africa' → LOC
  - '0.3%' → PERCENT
  - '0.7%' → PERCENT
  - '1975' → DATE
  - '2013' → DATE

✅ Processing complete!
📄 Tasks saved to: label_studio_output/tasks.json
📄 Entity labels saved to: label_studio_output/named_entities.txt
📊 Total tasks: 67
🏷️ Total unique entities: 9
🏷️ Entity types: ['CARDINAL', 'CHANGE', 'COORDINATES', 'DATE', 'LOC', 'LULC', 'PERCENT', 'PROCESS', 'SURFACE_UNIT']

📝 To import in Label Studio:
1. Create a new project
2. Go to Settings > Labeling Interface > Code
3. Paste the content from: label_studio_output/label_studio_config.xml
4. Go to Import and upload: label_studio_output/tasks.json

In [59]:
def detailed_tokenization_check():
    """
    Deep dive into how tokenizer handles built-up area
    """
    print("\n🔧 DETAILED TOKENIZATION ANALYSIS:")
    print("=" * 50)
    
    test_sentence = "Agricultural land decreased by 30% while built-up area increased significantly SUB SAHARA."
    
    # Tokenize the full sentence
    encoding = tokenizer(
        test_sentence,
        return_offsets_mapping=True,
        add_special_tokens=True
    )
    
    tokens = tokenizer.convert_ids_to_tokens(encoding['input_ids'])
    offsets = encoding['offset_mapping']
    
    print(f"📝 Full sentence: {test_sentence}")
    print(f"\n🔤 Tokenization:")
    
    for i, (token, (start, end)) in enumerate(zip(tokens, offsets)):
        text_span = test_sentence[start:end] if start != 0 or end != 0 else "[SPECIAL]"
        print(f"  {i:2d}: '{token}' → '{text_span}' (pos {start}-{end})")
        
        # Highlight built-up area tokens
        if 'built' in token.lower() or 'up' in token.lower() or 'area' in token.lower():
            print(f"      ⭐ BUILT-UP AREA RELATED TOKEN!")
    
    # Find where "built-up area" should be
    buildup_start = test_sentence.find("SUB SAHARA")
    buildup_end = buildup_start + len("SUB SAHARA")
    
    print(f"\n🎯 'built-up area' spans characters {buildup_start}-{buildup_end}")
    
    # Find which tokens cover this span
    covering_tokens = []
    for i, (start, end) in enumerate(offsets):
        if start != 0 or end != 0:  # Skip special tokens
            if not (end <= buildup_start or start >= buildup_end):  # Overlaps
                covering_tokens.append((i, tokens[i], start, end))
    
    print(f"🔍 Tokens covering 'built-up area':")
    for i, token, start, end in covering_tokens:
        print(f"  Token {i}: '{token}' (pos {start}-{end})")
    
    return covering_tokens

covering_tokens = detailed_tokenization_check()

🔧 DETAILED TOKENIZATION ANALYSIS:
==================================================
📝 Full sentence: Agricultural land decreased by 30% while built-up area increased significantly SUB SAHARA.

🔤 Tokenization:
   0: '<s>' → '[SPECIAL]' (pos 0-0)
   1: 'Ag' → 'Ag' (pos 0-2)
   2: 'ric' → 'ric' (pos 2-5)
   3: 'ultural' → 'ultural' (pos 5-12)
   4: 'Ġland' → 'land' (pos 13-17)
   5: 'Ġdecreased' → 'decreased' (pos 18-27)
   6: 'Ġby' → 'by' (pos 28-30)
   7: 'Ġ30' → '30' (pos 31-33)
   8: '%' → '%' (pos 33-34)
   9: 'Ġwhile' → 'while' (pos 35-40)
  10: 'Ġbuilt' → 'built' (pos 41-46)
      ⭐ BUILT-UP AREA RELATED TOKEN!
  11: '-' → '-' (pos 46-47)
  12: 'up' → 'up' (pos 47-49)
      ⭐ BUILT-UP AREA RELATED TOKEN!
  13: 'Ġarea' → 'area' (pos 50-54)
      ⭐ BUILT-UP AREA RELATED TOKEN!
  14: 'Ġincreased' → 'increased' (pos 55-64)
  15: 'Ġsignificantly' → 'significantly' (pos 65-78)
  16: 'ĠSUB' → 'SUB' (pos 79-82)
  17: 'ĠSA' → 'SA' (pos 83-85)
  18: 'H' → 'H' (pos 85-86)
  19: 'ARA' → 'ARA' (pos 86-89)
  20: '.' → '.' (pos 89-90)
  21: '</s>' → '[SPECIAL]' (pos 0-0)

🎯 'built-up area' spans characters 79-89
🔍 Tokens covering 'built-up area':
  Token 16: 'ĠSUB' (pos 79-82)
  Token 17: 'ĠSA' (pos 83-85)
  Token 18: 'H' (pos 85-86)
  Token 19: 'ARA' (pos 86-89)

In [60]:
def check_buildup_labeling(found_examples):
    """
    Check if built-up area patterns are properly labeled as LULC
    """
    print("🔍 CHECKING IF BUILT-UP PATTERNS ARE LABELED AS LULC:")
    print("=" * 60)
    
    labeled_count = 0
    unlabeled_count = 0
    labeling_issues = []
    
    for example in found_examples[:20]:  # Check first 20 examples
        print(f"\n📝 Sentence: {example['sentence']}")
        print(f"🎯 Pattern: '{example['pattern']}'")
        
        if example['is_labeled_lulc']:
            print(f"✅ CORRECTLY LABELED as LULC")
            labeled_count += 1
        else:
            print(f"❌ NOT LABELED as LULC!")
            unlabeled_count += 1
            labeling_issues.append(example)
            
            # Show what entities ARE labeled in this sentence
            print("🏷️ Entities that ARE labeled:")
            for entity in example['all_entities']:
                print(f"   - '{entity['text']}' → {entity['label']}")
        
        print("-" * 40)
    
    print(f"\n📊 LABELING SUMMARY (from sample):")
    print(f"✅ Correctly labeled: {labeled_count}")
    print(f"❌ Not labeled: {unlabeled_count}")
    
    if unlabeled_count > 0:
        print(f"\n⚠️ WARNING: {unlabeled_count} examples have 'built-up area' in text but NOT labeled as LULC!")
        print("This could explain why your model doesn't recognize it.")
    
    return labeled_count, unlabeled_count, labeling_issues

# Run the labeling check
labeled_count, unlabeled_count, labeling_issues = check_buildup_labeling(found_examples)

🔍 CHECKING IF BUILT-UP PATTERNS ARE LABELED AS LULC:
============================================================

📝 Sentence: The analysis of land use and land cover change presented above reveals mostly a decrease in vegetative areas and an increase built up areas agricultural land and water bodies
🎯 Pattern: 'built up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: The analysis of land use and land cover change presented above reveals mostly a decrease in vegetative areas and an increase built up areas agricultural land and water bodies
🎯 Pattern: 'built up areas'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: The study observed a significant increase (12.77%) in built-up area from 2002 (52.88%) to 2018 (65.5%), followed by a slight increase in the cover of bare ground.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Under the business as usual scenario, prediction analysis for the year 2050 show that built up area will consume almost all of the city area (73.21%) with forest significantly reduced to patches making up only about 16% of the city.
🎯 Pattern: 'built up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Using the outputs from remote sensing imagery, field surveys, and topped expert knowledge of the study area, five LULC types were classified; water body, bare ground, built-up area, forest, and agriculture ( Fig.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Studies by | LULC transition between years: To deepen our understanding of the evolving nature of the LULC types in the city, we created confusion matrices for changes in 2002 and 2018 ( Table The potential for these trends to continue remain high with transition probabilities of 0.83 for bare ground and 0.58 for forest to transition to built-up area.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Although small, agriculture land shows a significant probability to transition to built-up area which has been the trend in many cities The findings indicate that rapid development of urban built will lead to sharp declines in forest and agriculture and increase in urban population.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Significant increase in built-up areas were associated with parallel loss of important land cover types such as forest and agriculture.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Significant increase in built-up areas were associated with parallel loss of important land cover types such as forest and agriculture.
🎯 Pattern: 'built-up areas'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: The satisfactory results can be summarized in four main aspects: (1) built-up areas, including industry, residential and commercial areas, have slowed down their growth due to socio-economical drivers such as security and null monetary investments; (2) vegetation such as mixed forest and low density vegetation (bare surfaces, sparse vegetation and grassland) has been sustained and increased over time due to reforestation or migration from other classes; (3) swamps experienced considerable degradation over the past five years and (4) high and medium vegetation densities have transformed mostly to low vegetation densities due to climate drives such as low precipitation and possible high soil evaporation, which might also increase the overland flow for those areas.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: The satisfactory results can be summarized in four main aspects: (1) built-up areas, including industry, residential and commercial areas, have slowed down their growth due to socio-economical drivers such as security and null monetary investments; (2) vegetation such as mixed forest and low density vegetation (bare surfaces, sparse vegetation and grassland) has been sustained and increased over time due to reforestation or migration from other classes; (3) swamps experienced considerable degradation over the past five years and (4) high and medium vegetation densities have transformed mostly to low vegetation densities due to climate drives such as low precipitation and possible high soil evaporation, which might also increase the overland flow for those areas.
🎯 Pattern: 'built-up areas'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: For example, The reasons for the national scale studies have been to: understand the spatial and temporal land use and carbon stock changes in Uganda | Methods/data employed: The review has indicated that the most used method/data was earth observation, particularly Landsat imagery (30 m resolution) employed in 95.2% of cases and then MODIS (250 m and 500 m) employed in 2.4% of cases, and transect walk plus interview in 2.4% of studies (Figure | Land use and land cover change statistics in Uganda: The review points that generally, agriculture and built up areas (from here on used interchangeably with settlements) have increased while forest and woodland have decreased over the period The numbers of urban centers increased from 67 in 1991 to 259 in 2014, while urban population increased from 0.6 million people in 1969 to 6.4 million people in 2014 .
🎯 Pattern: 'built up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: For example, The reasons for the national scale studies have been to: understand the spatial and temporal land use and carbon stock changes in Uganda | Methods/data employed: The review has indicated that the most used method/data was earth observation, particularly Landsat imagery (30 m resolution) employed in 95.2% of cases and then MODIS (250 m and 500 m) employed in 2.4% of cases, and transect walk plus interview in 2.4% of studies (Figure | Land use and land cover change statistics in Uganda: The review points that generally, agriculture and built up areas (from here on used interchangeably with settlements) have increased while forest and woodland have decreased over the period The numbers of urban centers increased from 67 in 1991 to 259 in 2014, while urban population increased from 0.6 million people in 1969 to 6.4 million people in 2014 .
🎯 Pattern: 'built up areas'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Generally, agriculture and built up areas are increasing at the expense of forest, wetland and woodland.
🎯 Pattern: 'built up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Generally, agriculture and built up areas are increasing at the expense of forest, wetland and woodland.
🎯 Pattern: 'built up areas'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Results of the study reveal that over time both the cities have witnessed a dramatic growth in built-up area, systematic reduction in green space and increase in LST.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: There is 85% increase in builtup area in Surat in the past 2 decades and 31% increase in built-up area in Bharuch during the same period.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: vegetation, water body, built-up area and bare soil (Figs.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: The SEZs have acquired farmland and pastoral land for different industrial projects Increase in surface temperature coupled with loss of vegetation to built-up area over the years has made both the cities more vulnerable to natural hazards, viz.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📝 Sentence: Urban expansion in Surat along the banks of the river on both the sides has greatly modified the hydrology by increasing the built-up areas, encroachment of constructions in the floodplains adjacent to the river and construction of new bridges which has reduced the capacity of the river and the open space for the floodwaters to spread out.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
----------------------------------------

📊 LABELING SUMMARY (from sample):
✅ Correctly labeled: 20
❌ Not labeled: 0

In [77]:
# Debug Cell 1: Check what terms are actually loaded
print("=== VOCABULARY CHECK ===")
print(f"\nLULC vocabulary size: {len(lulc_vocab)}")
print("Sample LULC terms:")
for term in sorted(list(lulc_vocab))[:20]:  # Show first 20
    print(f"  - '{term}'")

print(f"\nPROCESS vocabulary size: {len(process_vocab)}")
print("Sample PROCESS terms:")
for term in sorted(list(process_vocab))[:20]:  # Show first 20
    print(f"  - '{term}'")

# Check if specific terms are in vocabularies
test_terms = ['bare ground', 'bare soil', 'built-up area', 'built up area', 'increase', 'decrease']
print("\nChecking specific terms:")
for term in test_terms:
    in_lulc = term.lower() in lulc_vocab
    in_process = term.lower() in process_vocab
    print(f"  '{term}': LULC={in_lulc}, PROCESS={in_process}")

=== VOCABULARY CHECK ===

NameError: name 'lulc_vocab' is not defined

In [50]:
def check_term_labeling_consistency(found_examples, search_term, expected_label, max_examples=20):
    
    print("=" * 70)
    
    labeled_count = 0
    unlabeled_count = 0    
    labeling_issues = []
    
    for example in found_examples[:max_examples]:
        print(f"\n📝 Sentence: {example['sentence']}")
        print(f"🎯 Pattern: '{example['pattern']}'")
        
        # Check if the pattern is labeled with the expected entity type
        is_labeled_correctly = any(
            expected_label.lower() in entity['label'].lower() and 
            example['pattern'].lower() in entity['text'].lower()
            for entity in example['all_entities']
        )
        
        if is_labeled_correctly:
            print(f"✅ CORRECTLY LABELED as {expected_label}")
            labeled_count += 1
        else:
            print(f"❌ NOT LABELED as {expected_label}!")
            unlabeled_count += 1
            labeling_issues.append(example)
            
            # Show what entities ARE labeled in this sentence
            print("🏷️ Entities that ARE labeled:")
            for entity in example['all_entities']:
                print(f"   - '{entity['text']}' → {entity['label']}")
        
        print("-" * 50)
    
    print(f"\n📊 LABELING SUMMARY for '{search_term}' → '{expected_label}':")
    print(f"✅ Correctly labeled: {labeled_count}")
    print(f"❌ Not labeled as {expected_label}: {unlabeled_count}")
    
    # Calculate consistency percentage
    total_checked = labeled_count + unlabeled_count
    if total_checked > 0:
        consistency_rate = (labeled_count / total_checked) * 100
        print(f"📈 Labeling consistency: {consistency_rate:.1f}%")
        
        if consistency_rate < 80:
            print(f"⚠️ WARNING: Low consistency rate! Only {consistency_rate:.1f}% of '{search_term}' examples are labeled as '{expected_label}'")
            print("This inconsistency could affect model performance.")
        elif consistency_rate == 100:
            print(f"🎉 PERFECT! All '{search_term}' examples are consistently labeled as '{expected_label}'!")
        else:            print(f"✅ Good consistency rate: {consistency_rate:.1f}%")
    
    return labeled_count, unlabeled_count, labeling_issues

def search_and_check_term_labeling(fixed_raw_data, search_patterns, expected_label, term_description="term"):
    """
    Complete function to search for patterns and check their labeling consistency
    
    Args:
        raw_data: Your training data
        search_patterns: List of regex patterns to search for
        expected_label: Expected entity label (e.g., 'LULC', 'LOC', 'CHANGE')
        term_description: Description of what you're searching for (for display)
    """
    print(f"🔍 SEARCHING AND CHECKING LABELING FOR: {term_description.upper()}")
    print("=" * 80)    
    # Search for patterns
    found_examples = []
    pattern_counts = {pattern: 0 for pattern in search_patterns}
    
    for item in fixed_raw_data:  # Use fixed_raw_data here
        text = item['original_sentence'].lower()
        entities = item['entities']
        
        for pattern in search_patterns:
            if pattern.lower() in text:
                pattern_counts[pattern] += 1
                
                # Check if pattern is labeled with expected entity type
                is_labeled_correctly = any(
                    pattern.lower() in entity['text'].lower() and 
                    entity['label'].lower() == expected_label.lower()  # Case-insensitive comparison
                    for entity in entities
                )
                
                found_examples.append({
                    'sentence': item['original_sentence'],
                    'pattern': pattern,
                    'is_labeled_correctly': is_labeled_correctly,
                    'all_entities': entities
                })
    
    # Display search results
    print(f"\n📊 SEARCH RESULTS for {term_description}:")
    print("-" * 50)
    for pattern, count in pattern_counts.items():
        print(f"'{pattern}': {count} occurrences")
    
    print(f"\nTotal examples found: {len(found_examples)}")
    
    if found_examples:
        # Check labeling consistency
        labeled_count, unlabeled_count, labeling_issues = check_term_labeling_consistency(
            found_examples, term_description, expected_label
        )
        
        return found_examples, pattern_counts, labeled_count, unlabeled_count, labeling_issues
    else:
        print(f"\n❌ NO EXAMPLES FOUND for {term_description}!")
        return [], pattern_counts, 0, 0, []

# Example usage functions for different entity types:

def check_lulc_terms(fixed_raw_data): # Pass fixed_raw_data
    """Check LULC term consistency"""
    lulc_patterns = [
        "built-up area", "built up area", "built-up areas",
        "forest area", "agricultural land", "urban areas",
        "commercial zones", "industrial parks", "green spaces",
        "residential areas", "wetlands", "grasslands"
    ]
    
    return search_and_check_term_labeling(
        fixed_raw_data, lulc_patterns, "LULC", "LULC terms"    )

def check_location_terms(fixed_raw_data):
    """Check LOC term consistency"""
    location_patterns = [
        "Sub-Saharan", "southern region", "Miombo ", "western region",
        "coastal areas", "rural areas", "mountain region", "central region"
    ]
    
    return search_and_check_term_labeling(
        fixed_raw_data, location_patterns, "LOC", "Location terms"
    )

def check_change_terms(fixed_raw_data):
    """Check CHANGE term consistency"""
    change_patterns = [
        "increased", "decreased", "expansion", "reduction",
        "conversion", "development", "urbanization", "deforestation"
    ]
    
    return search_and_check_term_labeling(
        fixed_raw_data, change_patterns, "CHANGE", "Change terms"
    )

def check_coordinate_terms(fixed_raw_data):
    """Check COORDINATES term consistency"""
    coord_patterns = [
        "23.5°N", "87.3°E", "coordinates", "latitude", "longitude"
    ]
    
    return search_and_check_term_labeling(
        fixed_raw_data, coord_patterns, "COORDINATES", "Coordinate terms"
    )

# Custom check function
def check_custom_terms(fixed_raw_data, patterns, expected_label, description):
    """
    Check any custom terms for any entity label
    
    Example usage:
    check_custom_terms(
        raw_data, 
        ["climate change", "global warming"],         "PROCESS", 
        "Climate terms"
    )
    """
    return search_and_check_term_labeling(
        fixed_raw_data, patterns, expected_label, description
    )

In [76]:
location_results = check_lulc_terms(raw_data)

🔍 SEARCHING AND CHECKING LABELING FOR: LULC TERMS
================================================================================

📊 SEARCH RESULTS for LULC terms:
--------------------------------------------------
'built-up area': 247 occurrences
'built up area': 8 occurrences
'built-up areas': 122 occurrences
'forest area': 82 occurrences
'agricultural land': 265 occurrences
'urban areas': 76 occurrences
'commercial zones': 0 occurrences
'industrial parks': 0 occurrences
'green spaces': 12 occurrences
'residential areas': 21 occurrences
'wetlands': 86 occurrences
'grasslands': 79 occurrences

Total examples found: 998
======================================================================

📝 Sentence: I doubt that this is for [agricultural land]
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
--------------------------------------------------

📝 Sentence: However, conflicting hypotheses have been reported: on the one hand an expansion (into native [savanna]) and intensification (fertilizer) of cropland [cultivation], and on the other hand [agricultural land] abandonment, caused by, e.g., the civil war in Sudan may both contribute to the observed positive trends
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'expansion' → CHANGE
   - 'savanna' → LULC
   - 'cropland' → LULC
   - 'cultivation' → PROCESS
   - 'caused' → CHANGE
   - 'Sudan' → LOC
--------------------------------------------------

📝 Sentence: Therefore, they deserve to be taken into account in theoretical thinking."}]}, {'@xmlns': 'http://www.tei-c.org/ns/1.0', 'head': 'Putting light and shade into the explanation of agricultural landscape evolution', 'p': ['Based on empirical experience from the Sudano-Sahelian region, the following will discuss trajectories of [[land use]] changes, and the appropriateness of understanding changes as abrupt and driven by events as opposed to evolving gradually will be considered.', {'ref': [{'@type': 'figure', '@target': '#fig_0', '#text': '1'}, {'@type': 'bibr', '@target': '#b17'
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'changes' → CHANGE
   - 'changes' → CHANGE
   - 'driven' → CHANGE
--------------------------------------------------

📝 Sentence: From 1984 to 2001, [tree] savannas, bare soils and agricultural lands increased by 17.55%, 18.79% and 21778.79%, respectively, while woodland, gallery [forest], [shrub] savannas and [[water] bodies] decreased by 22.02%, 5.03%, 40.08% and 31.2%, respectively
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - '1984 to 2001' → DATE
   - 'tree' → LULC
   - 'savannas' → LULC
   - 'bare soils' → LULC
   - 'increased' → CHANGE
   - '17.55%' → PERCENT
   - '18.79% and' → PERCENT
   - '21778.79%' → PERCENT
   - 'forest' → LULC
   - 'shrub' → LULC
   - 'savannas' → LULC
   - 'water' → LULC
   - 'decreased' → CHANGE
   - '22.02%' → PERCENT
   - '5.03%' → PERCENT
   - '40.08%' → PERCENT
   - '31.2%' → PERCENT
--------------------------------------------------

📝 Sentence: 2013), and only 4 percent of [agricultural land] is irrigated compared to 18 percent globally (You et al
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - '2013' → DATE
   - 'only 4 percent' → PERCENT
   - '18 percent' → PERCENT
--------------------------------------------------

📝 Sentence: Substantial changes in [land cover] and [[land use]] are referred to, although systematic studies which deal with spatial aspects are still scarce in spite of the growing evidence concerning other aspects of [agricultural land] use changes in Africa .'}, {'ref': [{'@type': 'bibr', '@target': '#b35', '#text': '(Naveh, 1989)'}, {'@type': 'bibr', '@target': '#b9', '#text': '(Brouwers, 1993;'}, {'@type': 'bibr', '@target': '#b28', '#text': 'Mazzucato and Niemeijer, 2000)'}, {'@type': 'bibr', '@target': '#b9', '#text': '(Brouwers, 1993)'}],
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'changes' → CHANGE
   - 'growing' → CHANGE
   - 'changes' → CHANGE
   - 'Africa' → LOC
   - '1989' → DATE
   - '1993' → DATE
   - '2000' → DATE
   - '1993' → DATE
--------------------------------------------------

📝 Sentence: For example expansion of agricultural land is related to the distance to irrigation by dams to settlements to roads and population change see Table
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'expansion' → CHANGE
   - 'roads' → LULC
   - 'change' → CHANGE
--------------------------------------------------

📝 Sentence: The share of urban population is also higher in Ghana than in West Africa where in 2010 about 42% of the West African population lived in urban areas
🎯 Pattern: 'urban areas'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'urban' → LULC
   - 'Ghana' → LOC
   - 'West Africa' → LOC
   - '2010' → DATE
   - 'about 42%' → PERCENT
   - 'West African' → LOC
   - 'urban' → LULC
--------------------------------------------------

📝 Sentence: Indirectly population growth leads to changes in agricultural land use practices due to land pressure
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'growth' → CHANGE
   - 'changes' → CHANGE
--------------------------------------------------

📝 Sentence: Table shows the extent of forest regeneration in some Sahelian countries for both natural and planted forest area.
🎯 Pattern: 'forest area'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'forest' → LULC
   - 'Sahelian' → LOC
   - 'forest' → LULC
--------------------------------------------------

📝 Sentence: Afforestation and natural regeneration of forests and woodlands in some countries have reduced the loss of forest area significantly at the global level
🎯 Pattern: 'forest area'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'Afforestation' → PROCESS
   - 'forests' → LULC
   - 'loss' → CHANGE
   - 'forest' → LULC
--------------------------------------------------

📝 Sentence: The losses were then divided by forest area in 2000 in order to obtain the deforestation rate Oil and gas receipts as a proportion of all receipts from exports 2000
🎯 Pattern: 'forest area'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'losses' → CHANGE
   - 'forest' → LULC
   - '2000' → DATE
   - 'deforestation' → PROCESS
   - '2000' → DATE
--------------------------------------------------

📝 Sentence: The first question is whether adverse changes in climate push people out of rural areas into urban areas
🎯 Pattern: 'urban areas'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'changes' → CHANGE
   - 'urban' → LULC
--------------------------------------------------

📝 Sentence: Agricultural intensification on existing farmlands may reduce farm expansion into the remaining forest areas
🎯 Pattern: 'forest area'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'expansion' → CHANGE
   - 'forest' → LULC
--------------------------------------------------

📝 Sentence: Deforestation can also be followed by several successive agricultural land uses
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'Deforestation' → PROCESS
--------------------------------------------------

📝 Sentence: The analysis of land use and land cover change presented above reveals mostly a decrease in vegetative areas and an increase built up areas agricultural land and water bodies
🎯 Pattern: 'built up area'
✅ CORRECTLY LABELED as LULC
--------------------------------------------------

📝 Sentence: The analysis of land use and land cover change presented above reveals mostly a decrease in vegetative areas and an increase built up areas agricultural land and water bodies
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'change' → CHANGE
   - 'decrease' → CHANGE
   - 'increase' → CHANGE
   - 'built up areas' → LULC
   - 'water bodies' → LULC
--------------------------------------------------

📝 Sentence: The result reveals that the Mono basin Table land cover presents an increase in built up agricultural land and water bodies while the vegetative clusters such as forest savanna and herbaceous savanna have declined for the three study periods
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'increase' → CHANGE
   - 'water bodies' → LULC
   - 'forest' → LULC
   - 'savanna' → LULC
   - 'savanna' → LULC
   - 'declined' → CHANGE
   - 'three' → CARDINAL
--------------------------------------------------

📝 Sentence: The expert interviews revealed that the crop fallow system is rarely practiced today and all agricultural land is under permanent use
🎯 Pattern: 'agricultural land'
❌ NOT LABELED as LULC!
🏷️ Entities that ARE labeled:
   - 'crop' → LULC
   - 'fallow' → LULC
   - 'today' → DATE
--------------------------------------------------

📝 Sentence: The study observed a significant increase (12.77%) in built-up area from 2002 (52.88%) to 2018 (65.5%), followed by a slight increase in the cover of bare ground.
🎯 Pattern: 'built-up area'
✅ CORRECTLY LABELED as LULC
--------------------------------------------------

📊 LABELING SUMMARY for 'LULC terms' → 'LULC':
✅ Correctly labeled: 2
❌ Not labeled as LULC: 18
📈 Labeling consistency: 10.0%
⚠️ WARNING: Low consistency rate! Only 10.0% of 'LULC terms' examples are labeled as 'LULC'
This inconsistency could affect model performance.